### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by radasbona** [Donnnno/Arcticons#1]
Hi,
Thanks for your awesome Icon Set. It looks great. 😀
Here a few icons you maybe want to use.

[20201219_010615.zip](https://github.com/Donnnno/Arcticons/files/5719370/20201219_010615.zip)

**Comment by Donnnno** [comment]
Thanks! I'll take a look at it :)

**Comment by Donnnno** [comment]
- [x] appmanager
- [x] compass
- [x] coronatracking
- [ ] deltachat
- [ ] familygem
- [x] link2sd
- [ ] nina
- [x] osesfrandroid
- [x] powerapp
- [ ] radiodroid
- [ ] raspicheck
- [ ] vr-banking
- [x] webmediashare
- [ ] websiteshortcut

**Comment by Donnnno** [comment]
Hi! I've added some icons: 

![image](https://user-images.githubusercontent.com/31142286/102725963-1dea3b80-431b-11eb-97e5-136a5c37d7d4.png)

Idk if I'll create all of them (some of them are pretty complicated). But I've also created basic letters and numbers you can use as placeholder:

![image](https://user-images.githubusercontent.com/31142286/102726014-76213d80-431b-11eb-8f77-6c30efd9e6c9.png)

**Comment by radasbona** [comment]
Don't make yourself too much work. 🙂 I'm thankful for every icon.
