### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Aircan** [Donnnno/Arcticons#1002]
<item component="ComponentInfo{com.appseleration.android.selfcare/com.vis.meinvodafone.view.activity.load.VfLoadPhoneActivity}" drawable="meinvodafone"/>
Although this is a non-fdroid App. 
Thank you in advance.

**Comment by Donnnno** [comment]
?

**Comment by Aircan** [comment]
<item component="ComponentInfo{com.appseleration.android.selfcare/com.vis.meinvodafone.view.activity.load.VfLoadPhoneActivity}" drawable="meinvodafone"/>

How to provide the icon? 
To Providence the information above I used Turtle APP.

**Comment by Aircan** [comment]
Oh, Herr I found another missing icon:

https://image.winudf.com/v2/image1/ZGUuYWthZmxpZWdfZnJlaWJ1cmcuZW5yb3V0ZV9pY29uXzE2NDI0MzMwMDZfMDkz/icon.png?w=100&fakeurl=1

**Comment by Donnnno** [comment]
We really need the turtl information to do anything with it..

**Comment by Aircan** [comment]
I updates the posts. And succeeded in providing the information.

**Comment by Donnnno** [comment]
Thanks.

I've completed your request (Vodafone had already an icon, so I updated that entry), and here's a small preview:

![image](https://user-images.githubusercontent.com/31142286/151523321-7cac0879-e13f-4028-8c82-fe8d3747f3fb.png)

If you like what we do, consider donating to support the development :^)

**Comment by Aircan** [comment]
Thank you very much and have nice weekend.

**Comment by Donnnno** [comment]
Thanks, have a nice weekend too!
