### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by pflocko** [Donnnno/Arcticons#103]
[20210316_115306.zip](https://github.com/Donnnno/Arcticons/files/6148287/20210316_115306.zip)

Hey there, would love to see those in the future.. They're a bit specific for swiss users but i guess there are some more to appreciate them but me.

**Comment by Donnnno** [comment]
Hi, I'll take a look at it when I have some time. 
The meteoswiss icon should already be working :thinking:

**Comment by pflocko** [comment]
Thank you for the fast reply.
It doesn't automatically show up and i can't find it in the pack..
Anyways, no need to hurry.
Thanks for your work!
Cheers

**Comment by Donnnno** [comment]
Ah I see, I've added the line in the past but never created an icon for it, oops.

**Comment by Donnnno** [comment]
Hi, I've created the icons, they will be in the next update!

![image](https://user-images.githubusercontent.com/31142286/111500879-c0f8f880-8744-11eb-86b7-8f8cbdadd46c.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.

**Comment by pflocko** [comment]
Awesome! Thanks a lot!
They look great and i absolutely consider leaving a few bucks. Will do so when i'm back home tomorrow.
Cheers 

Am 17. März 2021 17:19:30 MEZ schrieb Donno ***@***.***>:

**Comment by Donnnno** [comment]
Thank you! I'm planning to release a new version this weekend 🙂
