### ISSUE TITLE
Difficulty with Tables in Markor

### ISSUE THREAD

**Issue by km53** [Donnnno/Arcticons#1042]
Firstly, thank-you for the app, it is really useful and much better than others I have seen.

I use Ghostwriter (1.8.0) on my Windows laptop with files on Onedrive which are syched with files locallatly on my phone for which I use Markor (2.8.5).

I can see tables created in Markor in Ghostwriter without any issues.
At times I get a table previously created in Markor and put it to a new md note in Ghoswriter and add new records as needed.
But when I open this up later in Markod it does not look like a table. 

Questions:
1) Why does this happen?  
2) Does Markor depend on tables and rows created using its menu item rather than externally?

**Comment by Donnnno** [comment]
Uhhh... What?

This is an icon pack app

**Comment by km53** [comment]
Ooops, sorry!
Wrong area for me to post to.. :-(

**Comment by Donnnno** [comment]
No problem! :^)
