### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by aintyourcat** [Donnnno/Arcticons#106]
Hello, i would like to request some icons for:

1. EKA2L1
2. J2ME-Loader
3. Insular
4. QuickTiles
5. Simple Keyboard

Here's the zip: [20210317_010403.zip](https://github.com/Donnnno/Arcticons/files/6153875/20210317_010403.zip)
Thank you!

**Comment by Donnnno** [comment]
Hi, icons for:
- Insular
- QuickTiles
- Simple Keyboard 

should already work.

I'll take a look at the other ones when I have some time.

**Comment by Donnnno** [comment]
Hi again, just created the two remaining icons (pixel art to lines is kinda tricky, but I tried). They will be available in the next update:

![image](https://user-images.githubusercontent.com/31142286/111502643-547ef900-8746-11eb-9011-29b3e1bffafc.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.
