### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by SolarisSonne** [Donnnno/Arcticons#1070]
*Info*

7 new icons, in the other folder

---
*Zip file here*

[IconRequest 5.zip](https://github.com/Donnnno/Arcticons/files/7980623/IconRequest.5.zip)

**Comment by Donnnno** [comment]
We only accept icon requests, larger than 1 at this time

**Comment by Donnnno** [comment]
Oh wait! Did you create them already?

**Comment by SolarisSonne** [comment]
Yes, I hope it fits

**Comment by Kaiserdragon2** [comment]
Your Icons look really good, but you should only use lines not fills and instead of an Issue you should make a pull request.

**Comment by SolarisSonne** [comment]
But when I scale an icon with an outline of 1px at 48px,48px to 256px,256px, the icon's proportions are not preserved. So I turned the 1px outline into a fill. Or do I have a thinking mistake?

**Comment by Kaiserdragon2** [comment]
If you scale in Inkscape their are different options tho the proportions are preserved.
And it works with the other icons too so lines should work fine.

**Comment by SolarisSonne** [comment]
Well, I don't work with Inscape. In Adobe AI I do not know this function.
If it fits better I'll do it again and with contour. ;)

**Comment by Kaiserdragon2** [comment]
You only need to do the white version the black version is done by a script.

**Comment by Donnnno** [comment]
If you can make it line only I can do the rest, but right now, the icons have fills.

![image](https://user-images.githubusercontent.com/31142286/156593812-036f4c82-b7f2-4c3b-af6c-24679d00be2a.png)

**Comment by Donnnno** [comment]
Fixed these things!
