### ISSUE TITLE
Website is down (or at least secure server)

### ISSUE THREAD

**Issue by braniii** [Donnnno/Arcticons#1072]
I just wanted to let you know that there seems to be an issue with your ssl certificate. You can check the issue on Qualys SSL Labs:

https://www.ssllabs.com/ssltest/analyze.html?d=arcticons.com

PS: Congratulations on the new domain :tada:

**Comment by Donnnno** [comment]
Thanks! I'm aware of this, and gonna look into it soon :)

**Comment by Donnnno** [comment]
it should work again now! Made a little typo
