### ISSUE TITLE
[discussion] Pushing FOSS icon packs

### ISSUE THREAD

**Issue by braniii** [Donnnno/Arcticons#1073]
Hi @Donnnno,

I am currently the maintainer of ameixa and would like to ease up the development of FOSS icon packs. I guess that an icon pack consists mainly out of 3 parts, namely

1. the maintenance of the appfilters,
2. the creation of the icons, and
3. the maintenance of the android app.

So far many projects are sharing the 3rd step (in your case formerly using the frost icon app and now the pretty candybar). I guess it would boost the FOSS community if (especially the part which does not feel comfortable with Java, e.g., like me ;) one would provide not only a FOSS-fork of candybar but also a repository bundling all appfilters belonging to a given app. So to say that that every icon pack has only an assignment list of icon name to appfilter id and that the appfilter file is dynamically created.

As you can imagine, this is still a somewhat vague vision. Since I have to work a lot lately, I won't be the driving force either. Nevertheless, I believe that if one merges several communities, e.g. articons, ameixa, and frost, they will all benefit from the common app filters. However, to make a project like this feasible, one should probably create a Github/Gitlab organization. I realize that articons is the most active project right now, and that's why I'm writing here first.

I'd be happy to know what you think of it.

Best
Daniel

**Comment by Donnnno** [comment]
Gonna reply to this soon when I have some time, but this sounds interesting already :^)

**Comment by Donnnno** [comment]
Gonna react in small parts, this is the first bit:

I've started working on a FOSS version of candybar last week, so we can make it easier to use that when it's finished :) Right now I need to remove some last parts but [Snow](https://github.com/baitmooth/snow), the successor of Frost already uses it!

**Comment by Donnnno** [comment]
Oh for the first part thing: we have a script that sorts our appfilter! We can just paste the new lines without having to worry about the placements. 

And that's not the only thing people can benefit from, we've boosted the scrips from frost to a more all in one solution. The only thing contributors need to do now is providing an icon and place the lines in there. After that, I check the new icons and run the script.

I'm not a coder myself too, so I struggle with a lot of issues too, but I became somewhat better at this stuff in the last year. :)

**Comment by Donnnno** [comment]
Hi @braniii, I've taken the first big steps towards making it easier to use the candybar dashboard. The FOSS version is available here: 

https://github.com/Donnnno/candybar-foss
https://github.com/Donnnno/candybar-foss-sample

It still requires a bit of tinkering if you support for multiple flavors, but that's also pretty easy to do :)

**Comment by Donkey-Doug** [comment]
> Gonna react in small parts, this is the first bit:
> 
> I've started working on a FOSS version of candybar last week, so we can make it easier to use that when it's finished :) Right now I need to remove some last parts but [Snow](https://github.com/baitmooth/snow), the successor of Frost already uses it!

How do I install snow?

**Comment by Donnnno** [comment]
@Donkey-Doug you have to wait a little lomger, it's almost ready for FDroid!

**Comment by Donkey-Doug** [comment]
Will it be a seperate app, or will arcticons and snow be provided through the same app?

**Comment by Donnnno** [comment]
@Donkey-Doug a seperate app that makes use of the candybar-foss dashboard, see: https://github.com/baitmooth/snow

**Comment by Donnnno** [comment]
@braniii btw, I made a proposal for Ameixa to use Candybar-FOSS :-)
https://gitlab.com/xphnx/ameixa/-/issues/173

And also one for Papirus:
https://github.com/PapirusDevelopmentTeam/papirus_icons/pull/14

**Comment by Aman9das** [comment]
Another: https://github.com/mirrorkeydev/Appstract

**Comment by Donnnno** [comment]
Can I close this one?
