### ISSUE TITLE
Icon request for Findroid

### ISSUE THREAD

**Issue by Elbullazul** [Donnnno/Arcticons#1078]
*Info*

The icon for findroid is the same icon used for Jellyfin, which makes it a bit hard to differentiate the apps.

The current findroid logo has a small android icon in the center:
![findroid-logo](https://github.com/jarnedemeulemeester/findroid/raw/main/images/findroid-banner.png)

**Comment by Elbullazul** [comment]
I thought the app was supported, but on a closer look, it is assigned the jellyfin icon, so there is no icon for this app.

I'd like to submit an icon request for the app

Here is the [zip file](https://github.com/Donnnno/Arcticons/files/8041963/IconRequest_10022022_095456.zip)

**Comment by Donnnno** [comment]
We have  a small android asset we can put in there :^)

**Comment by Donnnno** [comment]
Here's a preview:

![image](https://user-images.githubusercontent.com/31142286/153766044-30568221-5319-4f23-b10d-d70b35a393ec.png)

If you like the icon pack, consider donating to support the project :^)
