### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by michas0602** [Donnnno/Arcticons#108]
[20210317_085803.zip](https://github.com/Donnnno/Arcticons/files/6159409/20210317_085803.zip)

Soundcloud made an update which broke your icon.
Many thanks and with best regards

**Comment by Donnnno** [comment]
Hi, I've created the icon for the Math app and updated the SoundCloud one:

![image](https://user-images.githubusercontent.com/31142286/111552881-8bbfcb00-8783-11eb-86e4-4eab4f99689d.png)

Enjoy!

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.
