### ISSUE TITLE
Muzei integration doesn't work

### ISSUE THREAD

**Issue by TheLastProject** [Donnnno/Arcticons#1097]
It identifies itself as "Your Art Source Name" and when pressing Settings, will show nothing.

Arcticons Dark (com.donnnno.arcticons) 3.7.3 from F-Droid
Muzei (net.nurik.roman.muzei) 3.4.5-rc03 from F-Droid

![image](https://user-images.githubusercontent.com/1885159/154321850-a8ab2dbb-b33d-4f5b-aa6c-02a2257a52f0.png)
![image](https://user-images.githubusercontent.com/1885159/154321870-416b6d6f-5f9c-4277-9749-b7d1144af9dd.png)

P.S.: I don't care about this feature myself, but I noticed this issue so I figured I should report it as I found no issue for it (neither open nor closed). Please don't prioritize dealing with this for me :)

**Comment by Donnnno** [comment]
Oh we don't have muzei things, so that makes sense, I guess!

**Comment by Donnnno** [comment]
I'll take a look at it, thanks!

**Comment by Donnnno** [comment]
Turned off the source for Arcticons, because we don't use it :) 

https://github.com/Donnnno/Arcticons/commit/60bca6d799db1248aadd8f8d3130ae86f8a36685
