### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Turbolqk** [Donnnno/Arcticons#1098]
Icon request - Phonograph Music Player

Link to the app:
https://play.google.com/store/apps/details?id=com.kabouzeid.gramophone&hl=en_US&gl=US

Thanks!

**Comment by Donnnno** [comment]
We already have an icon for Phonograph, but apparently it doesn't work anymore.

Can you provide the data here by using the icon request app: https://github.com/Kaiserdragon2/IconRequest

Thanks!

**Comment by Donnnno** [comment]
Thanks! Updated it :)
