### ISSUE TITLE
OsmAnd and OSMTracker have same icon

### ISSUE THREAD

**Issue by grrrrr** [Donnnno/Arcticons#1105]
`OsmAnd Plus` and `OSMTracker` have the same icon which causes confusion as to which icon opens which app

example

![osmand-osmtracker](https://user-images.githubusercontent.com/1025506/156836527-f3dd8447-dcd4-4251-8c6f-fc520d9f3879.jpg)

From left to right these icons are `OsmAnd Plus`,  `OSMTracker`, `StreetComplete` (for comparison)

* OsmAnd Plus
  * net.osmand.plus
  * Version: 1,4.1.11
  * Store: F-Droid

* OSMTracker
  * net.osmtracker
  * Version: 1.0.1
  * Store: F-Droid

* Arcticons Dark
  * com.donnnno.arcticons
  * Version: 3.7.6 
  * Store: F-Droid

**Comment by Donnnno** [comment]
How should the osm tracker look?

**Comment by grrrrr** [comment]
This is it on their github - https://github.com/labexp/osmtracker-android/blob/master/app/src/main/assets/ic_launcher.svg

**Comment by Donnnno** [comment]
new icon for osmtracker, and one generic rss icon for ttrss :)

![image](https://user-images.githubusercontent.com/31142286/156887857-726d5957-a36f-4963-8977-5d1d2129fe88.png)
