### ISSUE TITLE
TTRSS-Reader unclear

### ISSUE THREAD

**Issue by grrrrr** [Donnnno/Arcticons#1106]
The `TTRSS-Reader` icon is a bit ambiguous as to what it is compared to the original,  I'd initially though it was for "t for telephone" :)

* TTRSS-Reader
  * org.ttrssreader
  * version 1.96.6 
  * Store: F-Droid

Original Icon: https://github.com/nilsbraden/ttrss-reader-fork/blob/master/ttrssreader/src/main/res/drawable-xhdpi/icon.png
Arcticons Icon: https://github.com/Donnnno/Arcticons/blob/main/icons/black/tinytinyrss.svg

**Comment by Donnnno** [comment]
You're right, I'll take a look at it when I have some time :^)
