### ISSUE TITLE
Reddit icon not automatically detecting

### ISSUE THREAD

**Issue by ObsidianChickenz** [Donnnno/Arcticons#111]
Tested in both Nova Launcher and OpenLauncher. Whenever I apply the entire icon pack, the Reddit icon is not updated. I can manually set the icon in Nova Launcher, but I figured I should still make this known.

Nova Launcher screenshot: [https://imgur.com/a/4U9cKgf](https://imgur.com/a/4U9cKgf)
OpenLauncher screenshot: [https://imgur.com/a/KzYxLAH](https://imgur.com/a/KzYxLAH)

The other non-styled apps are PilferShush Jammer, Puffin Browser, Remind, Samsung Notes, and Scam Shield, but those do not currently have icons, while Reddit does. I can try to give any other info as necessary.

**Comment by Donnnno** [comment]
Hi,
The Reddit icon issue is already resolved #94 

If you want to see other icons you can create an icon request or try to create them yourself!

**Comment by ObsidianChickenz** [comment]
Oh, I didn't notice. My bad! Thanks for the excellent icon pack!
