### ISSUE TITLE
Icon request: PinDroid

### ISSUE THREAD

**Issue by grrrrr** [Donnnno/Arcticons#1110]
*Info*

Icon request for **PinDroid**

- GitHub: https://github.com/maxpower47/PinDroid
- appfilter.xml: in the attached zip file
- logo: in the attached zip file (and below for reference)

![com_pindroid_com_pindroid_activity_Main](https://user-images.githubusercontent.com/1025506/157927052-6b7fdf44-e06a-494f-ad62-8cf75e6d553d.png)

---
*Zip file:*
[20220311_015831.zip](https://github.com/Donnnno/Arcticons/files/8234419/20220311_015831.zip)

**Comment by Donnnno** [comment]
Reused this icon for your request: https://raw.githubusercontent.com/Donnnno/Arcticons/main/icons/black/sharetopinboard.svg
