### ISSUE TITLE
BubbleUPnP icon not applied

### ISSUE THREAD

**Issue by Ngisk** [Donnnno/Arcticons#1113]
Hello,
the BubbleUPnP icon is present but not automatically applied. I have to select it manually.
I noticed that the name of the `.svg` file in the source is `bubleupnp.svg`, a `b` is missing.
I don't know, maybe this is the cause.

Thanks for the attention.

**Comment by Donnnno** [comment]
Thanks for the heads up! Fixed it and should be working in the next release :)
