### ISSUE TITLE
Icon request: LibreTube

### ISSUE THREAD

**Issue by Elbullazul** [Donnnno/Arcticons#1118]
*Info*
```
<!-- LibreTube -->
<item component="ComponentInfo{com.github.libretube/com.github.libretube.MainActivity}" drawable="libretube"/>
```
---
*Zip file here*

[IconRequest_20032022_095018.zip](https://github.com/Donnnno/Arcticons/files/8311440/IconRequest_20032022_095018.zip)

**Comment by Donnnno** [comment]
Already created by @joelchrono12 in #1117 !

**Comment by Elbullazul** [comment]
Sorry, I missed that issue

**Comment by Donnnno** [comment]
No problem :)
