### ISSUE TITLE
18 icon contributions

### ISSUE THREAD

**Issue by JapanYoshi** [Donnnno/Arcticons#1120]
- **0h h1:** {com.q42.ohhi/com.q42.ohhi.MainActivity}
  - Submitted icon `oh_hi`.
  - Popular donationware game app.
  - Did not show up in the Icon Request screen.
- **0h n0:** {com.q42.ohno/com.q42.ohno.MainActivity}
  - Submitted icon `oh_no`.
  - Popular donationware game app.
- **7zipper:** {org.joa.zipperplus7/org.test.flashtest.StartPageActivity}
  - Submitted icon `a7zipper`.
  - Archive compressor/extractor and file explorer for power users.
- **8vim:** {inc.flide.vi8/inc.flide.vi8.ui.SettingsActivity}
  - Submitted icon `a8vim`.
  - FOSS implementation of 8pen.
  - Fun fact: The trail spells out the word "pen".
- **App Cloner Premium & Add-ons:** {com.applisto.appcloner.premium/com.applisto.appcloner.premium.StartActivity}
  - Use existing icon for App Cloner.
  - A workaround for donations and subscriptions in App Cloner, now that App Cloner proper has been banned from Google Play.
- **Bandcamp for Artists:** {com.bandcamp.artistapp/com.bandcamp.artistapp.RootTabActivity}
  - Use existing icon for Bandcamp.
  - A version of Bandcamp for artists as opposed to listeners.
  - Though, it may get confusing for people who are both artists and listeners on Bandcamp, since the two icons originally differ only by fill.
- **Bejeweled Stars:** {com.ea.gp.bejeweledskies/com.ea.nimble.plugin.NimbleActivity}
  - Submitted icon `bejeweled_stars`.
  - A version of Bejeweled that rips Candy Crush back off.
- **Bejeweled Blitz:** {com.ea.BejeweledBlitz_na/com.popcap.BejeweledBlitz.BejeweledBlitzGameActivity}
  - Submitted icon `bejeweled_blitz`.
  - A version of Bejeweled where games last 1 minute, and special items spice up the game.
- **Bejeweled Classic:** {com.ea.gp.bej3/com.ea.gp.bej3.Main}
  - Submitted icon `bejeweled3`.
  - A freemium port of Bejeweled 3 to Android.
- **Desmos Scientific Calculator:** {com.desmos.scientific/com.desmos.calculator.MainActivity}
  - Submitted icon `desmos_scientific`.
  - A scientific calculator from the makers of Desmos Graphing Calculator.
- **dotpict:** {net.dotpicko.dotpict/net.dotpicko.dotpict.RoutingActivity}
  - Submitted icon `dotpict`.
  - A pixel art creation tool and sharing platform.
- **I Can’t Wake Up!:** {com.kog.alarmclock/com.7mobile.icantwakeup.ui.MainActivity}
  - Submitted icon `i_cant_wake_up`.
  - Alarm clock that forces you up and out of bed with various tasks.
- **Just Dance Now:** {com.ubisoft.dance.JustDance/com.ubisoft.dance.JustDance.JustDanceLaunchActivity}
  - Submitted icon `just_dance_now`.
  - A controller app for the browser dance game Just Dance Now.
- **Keyman:** {com.tavultesoft.kmapro/com.tavultesoft.kmapro.SplashScreenActivity}
  - Submitted icon `just_dance_now`.
  - A cross-platform custom keyborad app and keyboard layout system.
- **Minesweeper: The Clean One:** {ee.dustland.android.minesweeper/ee.dustland.android.minesweeper.MinesweeperHostActivity}
  - Use existing icon for Minesweeper.
  - A visually uncluttered implementation of Minesweeper.
- **Multiling O Keyboard:** {kl.ime.oh/kl.ime.oh.M}
  - Submitted icon `multiling_o_keyboard`.
  - An insanely customizable keyboard app.
  - I hope the æ glyph is satisfactory.
- **Osaifu-Keitai:** {{com.felicanetworks.mfm.main/com.felicanetworks.mfm.main.ServiceListActivity}}
  - Submitted icon `osaifu_keitai`.
  - Developed by NTT Docomo, the de-facto mobile payment standard of Japan since the flip phone era.
  - This app is preinstalled on many Japanese phones.
- **QR Code (arara):** {com.arara.q/com.arara.q.AppStartActivity}
  - Submitted icon `qr_code`.
  - QR Code, barcode, and Frame QR Code reader. It cannot, however, read SQRC (which the current QR Code icon seems to represent).
  - Fun fact: When scanned, it links to this GitHub repository.
- **SmartNews:** {jp.gocro.smartnews.android/jp.gocro.smartnews.android.activity.SmartNewsActivity}
  - Submitted icon `smartnews`.
  - A popular tabbed news app from Japan.
- **tenki.jp:** {jwa.or.jp.tenkijp3/jwa.or.jp.tenkijp3.SplashActivity}
  - Submitted icon `tenki_jp`.
  - Official forecast app of the Japan Weather Association.
- **WaveEditor:** {io.sbaud.wavstudio/io.sbaud.wavstudio.activities.LoadActivity}
  - Use existing icon for Recorder.
  - An audio recorder and editor that supports recording in WAV format.
- **Wordfeud:** {com.hbwares.wordfeud.free/com.hbwares.wordfeud.ui.WordFeudActivity} and {com.hbwares.wordfeud.full/com.hbwares.wordfeud.ui.WordFeudActivity}
  - Submitted icon `wordfeud`.
  - A Scrabble-like online competitive word game, with the feature to randomize the location of bonus tiles.

Here are the SVG files:
[arcticons.zip](https://github.com/Donnnno/Arcticons/files/8322450/arcticons.zip)

**Comment by Donnnno** [comment]
Hi @JapanYoshi these icons look great! I'll add them to the next update.

Some points of feedback for the next time:

- make sure all lines are white, a lot of them are black now
- the QR icon has a fun concept but is too cluttered and doesn't uses outlines, so I replaced it with our standard QR icons
- the dots icon is nice but is very out-of-place in Arcticons, so had to replace that as well unfortunately.

![image](https://user-images.githubusercontent.com/31142286/160249545-e98145c4-b454-4992-821a-2c74ae147a25.png)

(It's always a struggle to translate dots/pixelart to lines)

**Comment by Donnnno** [comment]
Also, please use the Icon Request app instead of a long list, the XML that it generates saves me a lot of time!

**Comment by JapanYoshi** [comment]
Please just delete the Dotpict icon. It looks horrible.

**Comment by Donnnno** [comment]
haha sorry, do you have an alternative in mind?

**Comment by JapanYoshi** [comment]
No, but there are other official pixel artworks for the Dotpict app, so one of them could be converted.

**Comment by Donnnno** [comment]
You can also try to create a version with more natural lines or something

**Comment by JapanYoshi** [comment]
![dotpict_20220327_090050](https://user-images.githubusercontent.com/8707990/160261005-117b44a2-6baf-4e29-ad5a-98835713b5b8.png)
I’ve attempted a smaller-res version of the official mascot.

**Comment by Donnnno** [comment]
looks nice, but does not fit into arcticons

**Comment by JapanYoshi** [comment]
![6a016ce69094881d8b8a84e235919be486d81863_hq](https://user-images.githubusercontent.com/8707990/160261030-c05637ef-d27e-4890-ac4d-84581013dd3d.jpg)
There are (were) official smaller versions of the mascot, but they’re multicolored.

**Comment by Donnnno** [comment]
The dots are nice, but icons in this pack are line-based. Dot's should be used complimentary and not as the main part..

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/160264380-c8197111-21b9-482b-b155-4b91408b2fdf.png)

**Comment by Donnnno** [comment]
Nice work!!

**Comment by Donnnno** [comment]
If you'll send me the svg I'll include it in the next release :)

**Comment by JapanYoshi** [comment]
[dotpict.zip](https://github.com/Donnnno/Arcticons/files/8360688/dotpict.zip)

**Comment by Donnnno** [comment]
Thanks!
