### ISSUE TITLE
Icon request: Buddha Quotes

### ISSUE THREAD

**Issue by grrrrr** [Donnnno/Arcticons#1122]
*Info*

Icon request for PinDroid

- GitHub: https://github.com/BanDev/Buddha-Quotes
- appfilter.xml: in the attached zip file
- logo: in the attached zip file (and below for reference)

![buddha_quotes](https://user-images.githubusercontent.com/1025506/159528519-a285b458-089c-4241-9875-45618fa75116.png)

---

[buddha_quotes.icon_request_10_03_2022_21_02_44.zip](https://github.com/Donnnno/Arcticons/files/8326184/buddha_quotes.icon_request_10_03_2022_21_02_44.zip)

**Comment by Donnnno** [comment]
Can you use the in app function to request icons? Thanks :)

**Comment by grrrrr** [comment]
Oh, sorry, my bad.  I don't have email on phone so couldn't submit that way.
