### ISSUE TITLE
Icon request for Mysterum VPN

### ISSUE THREAD

**Issue by Lucas-101** [Donnnno/Arcticons#1126]
Manufacturer : motorola
Model : moto g power
Product : sofia_retail
Screen Resolution : 1080 x 2121 pixels
Android Version : 11
App Version : 3.9.0
CandyBar Version : 3.13.3

MysteriumVPN
network.mysterium.vpn/updated.mysterium.vpn.ui.splash.SplashActivity
https://f-droid.org/en/packages/network.mysterium.vpn/

**Comment by Donnnno** [comment]
Can you use the in-app function for icon requests?

**Comment by Lucas-101** [comment]
> 

it does not seem to work with protonmail as your email client

**Comment by Donnnno** [comment]
You can share it to protonmail, but you have to add the adress manually: arcticons @ onnno . nl
