### ISSUE TITLE
Google Calendar Icon not working properly

### ISSUE THREAD

**Issue by sasukeiscool** [Donnnno/Arcticons#1127]
Google Calendar doesn't use Arcticons icon even  when set to use.
![Screenshot_20220328-214821_KISS launcher](https://user-images.githubusercontent.com/73827127/160401883-f17370e6-5201-40b8-9eff-df53ac7aab83.jpg)
![Screenshot_20220328-214848_KISS launcher](https://user-images.githubusercontent.com/73827127/160401893-ab654556-3b02-4fe7-ae4c-514e42ff8c6f.jpg)

DEVICE: Samsung Galaxy S20
OS: Android 12
LAUNCHER: KISS launcher

**Comment by Donnnno** [comment]
can you use the icon request app to give us the appfilter data?

**Comment by sasukeiscool** [comment]
Is this it?
[20220328_104556.zip](https://github.com/Donnnno/Arcticons/files/8363294/20220328_104556.zip)

**Comment by Donnnno** [comment]
yes, it should be working tho according to the code..

**Comment by Donnnno** [comment]
have you tried clearing KISS's or Arcticons' cache?

**Comment by sasukeiscool** [comment]
> have you tried clearing KISS's or Arcticons' cache?

i have but that did not fix it

**Comment by Donnnno** [comment]
I think it's a KISS issue then.. 

https://github.com/Neamar/KISS/issues/1578

Try opening an issue there, it may have something to do with dynamic calendar icons:

https://github.com/teslacoil/Example_NovaTheme/blob/master/DynamicCalendarIconAPI.md

**Comment by Donnnno** [comment]
Is this still an issue for you?

**Comment by sasukeiscool** [comment]
yes, it still is an issue for me

**Comment by Donnnno** [comment]
I've looked into this, unfortunately it's not an issue on our side. I've compared it with different launchers, but it only happens with KISS

**Comment by Donnnno** [comment]
Closing this because it is out of our scope to solve.

**Comment by sasukeiscool** [comment]
I just wanted to update that an update for the KISS launcher fixed this issue.

**Comment by Donnnno** [comment]
Great!

**Comment by michaelblyons** [comment]
Is there a way to reset a custom icon or switch icon packs?

**Comment by Donnnno** [comment]
my guess would be to clear the cache or use the menu from kiss to switch to another one ;)

**Comment by michaelblyons** [comment]
Right. I accidentally set the icon to a static one, not the rotating date. I don't know how to pick a pack. 😅
