### ISSUE TITLE
StreetComplete icon stopped working

### ISSUE THREAD

**Issue by grrrrr** [Donnnno/Arcticons#1129]
With the release of [StreetComplete 42.0](https://github.com/streetcomplete/StreetComplete/releases/tag/v42.0) the Arcticons icon has stopped working.

This is seen in  `Android 11` with `NovaLauncher` 

[icon_request_streetcomplete.zip](https://github.com/Donnnno/Arcticons/files/8366133/icon_request_streetcomplete.zip)

**Comment by grrrrr** [comment]
thanks @Kaiserdragon2 and @Donnnno   just to check, this made it into 4.0.0 release right?  As I am still seeing the original icon rather than the arcticon one.

I've cleared cache for both arcticons and nova,  any other suggestions when this does not work?

**Comment by Donnnno** [comment]
No, this is fixed in the next release!

**Comment by grrrrr** [comment]
ah ok,  thought i was going mad :)
