### ISSUE TITLE
Icon request for Odysee

### ISSUE THREAD

**Issue by perz1val-git** [Donnnno/Arcticons#1136]
*Info*

Odysee just made an app and it's missing an icon.
Playstore url:
https://play.google.com/store/apps/details?id=com.odysee.app&hl=en_US&gl=US
Icon url:
https://github.com/OdyseeTeam/odysee-android/blob/master/app/src/main/res/mipmap-hdpi/ic_launcher.png

I'm making an issue manually, because the in app functionality doesn't detect the app

---
*Zip file here*

**Comment by Donnnno** [comment]
Done by @Kaiserdragon2 !
