### ISSUE TITLE
Add (trivial) icon support for facebook and messenger lite

### ISSUE THREAD

**Issue by sherlach** [Donnnno/Arcticons#1151]
The "Lite" versions of [facebook](https://play.google.com/store/apps/details?id=com.facebook.lite&gl=US) and [messenger](https://play.google.com/store/apps/details?id=com.facebook.mlite&gl=US) can easily have support added by using the same icons currently used for the default versions of the apps.

**Comment by Donnnno** [comment]
Sure, can you gather the code we need with icon request?

https://github.com/Kaiserdragon2/IconRequest/releases

**Comment by Donnnno** [comment]
![image](https://user-images.githubusercontent.com/31142286/163565774-c4fd3497-568b-4930-a9c3-7ffdac529e27.png)

I've made variations for the lite ones
