### ISSUE TITLE
Existing icon not used

### ISSUE THREAD

**Issue by sasukeiscool** [Donnnno/Arcticons#1154]
Icon already exist but is not used
OPENREC.tv
jp.co.cyber_z.openrecviewapp/jp.co.cyber_z.openrecviewapp.feature.main.ui.MainActivity
https://play.google.com/store/apps/details?id=jp.co.cyber_z.openrecviewapp
[icon_request_14_04_2022_22_00_50.zip](https://github.com/Donnnno/Arcticons/files/8489339/icon_request_14_04_2022_22_00_50.zip)

**Comment by CyberaxAnnon** [comment]
Additional icons are also not used

- Mega
- Trial Sense

**Comment by rYR79435** [comment]
Another one
- StreetComplete

**Comment by Ngisk** [comment]
With latest update I lost automatic usage of some google-related icons (eg. Gmail, Google TV, Google Keep).
I had to re-set them manually.

**Comment by Donnnno** [comment]
@Ngisk a fix is already in one of the PR's! I renamed a bunch of google icons, so that's why

**Comment by Donnnno** [comment]
@CyberaxAnnon @rYR79435 please send the appfilter data with icon request:
https://github.com/Kaiserdragon2/IconRequest/releases

**Comment by rYR79435** [comment]
StreetComplete doesn't show up in the "missed apps" section of the app. I doubt that it is different.

I have already cleared the cache of KISS, Arcticons multiple times and have even restarted my device, all to no avail.

**Comment by CyberaxAnnon** [comment]
> @CyberaxAnnon @rYR79435 please send the appfilter data with icon request: https://github.com/Kaiserdragon2/IconRequest/releases

I have done this before and was told to send it via the in app request that you get per update, of which I only have one of. Can they not just be added back to the database with the current icons?

**Comment by Kaiserdragon2** [comment]
If the icons exist they can added back, but therefore we need the new appfilter code of these apps. You can send these here.

**Comment by Donnnno** [comment]
> Trial Sense

updated these!

**Comment by Donnnno** [comment]
fixed the openrec one
