### ISSUE TITLE
Icons already made still present in requestes.txt

### ISSUE THREAD

**Issue by EdwinRodger** [Donnnno/Arcticons#1158]
I was searching to make some app icons and I found that two icons from the app [requests.txt](https://github.com/Donnnno/Arcticons/blob/main/other/requests.txt) are already made
- [ダンカグ](https://github.com/Donnnno/Arcticons/blob/00cd0e78e7cdd7fb7466b77181d4aefbf8f4025a/other/requests.txt#L5) https://github.com/Donnnno/Arcticons/blob/00cd0e78e7cdd7fb7466b77181d4aefbf8f4025a/other/appfilter.xml#L6
- [DigiLocker](https://github.com/Donnnno/Arcticons/blob/00cd0e78e7cdd7fb7466b77181d4aefbf8f4025a/other/requests.txt#L1321) https://github.com/Donnnno/Arcticons/blob/00cd0e78e7cdd7fb7466b77181d4aefbf8f4025a/other/appfilter.xml#L2948

**Comment by Donnnno** [comment]
removed them!
