### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by sasukeiscool** [Donnnno/Arcticons#116]
[20210327_101926.zip](https://github.com/Donnnno/Arcticons/files/6215705/20210327_101926.zip)

**Comment by Donnnno** [comment]
Applied the existing ones and created these new ones:

![image](https://user-images.githubusercontent.com/31142286/112724134-15a12e00-8f12-11eb-8dbd-74c383808e2c.png)

Available in the next update :)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.
