### ISSUE TITLE
Arcticons shows up in file picker

### ISSUE THREAD

**Issue by Donkey-Doug** [Donnnno/Arcticons#1167]
![Screenshot_20220418-190407_Files_1](https://user-images.githubusercontent.com/50382414/163844634-8baf17f7-7e15-40d0-b319-919b3a71db84.png)

Is it possible to make arcticons not appear in the file picker? Seems unnecessary.

**Comment by Donnnno** [comment]
Yeah, you can choose png files from the app!

**Comment by Donkey-Doug** [comment]
But why? Haha

**Comment by Kaiserdragon2** [comment]
For Tasker as symbols for shortcuts

**Comment by Donnnno** [comment]
Idk why, but I see it as a _feature_
