### ISSUE TITLE
Building Instructions Guide

### ISSUE THREAD

**Issue by EdwinRodger** [Donnnno/Arcticons#1174]
As you know, I made a [red variant](https://github.com/EdwinRodger/Arcticons_Red) of Arcticons icon pack but I can't able to build it's app due to some version errors shown by android studio. (I used this [Create_Varients_Guide](https://github.com/Donnnno/Arcticons/blob/main/guides/Create_Variants_Guide.md), error came when I was on sync gradle step in [Build App](https://github.com/Donnnno/Arcticons/blob/main/guides/Create_Variants_Guide.md#build-app))

I was exploring this repository when I found this [Building Instructions](https://github.com/Donnnno/Arcticons/projects/1) issue still pending in To-Do section.

Can you complete building instructions guide so that it will be easier for me and many other users to make a new variant app for Arcticons

**Comment by Donnnno** [comment]
Currently, I don't have much time for that, unfortunately. You can also check out the candybar guide ⇾ https://github.com/zixpo/candybar-sample/wiki

Arcticons follows a lot of the same steps

**Comment by Aman9das** [comment]
i would suggest building vanilla arcticons successfully first, then following the guide

**Comment by Donnnno** [comment]
Closing this, because it's a double of #287

**Comment by EdwinRodger** [comment]
But that documentation is outdated 😐
but no problem I can wait

**Comment by Donnnno** [comment]
@EdwinRodger I've added the new build instructions there !
