### ISSUE TITLE
Use an icon for a different app.

### ISSUE THREAD

**Issue by jamesorgan** [Donnnno/Arcticons#1191]
The icons for apps like barclays, chase and amex exist but are not applied to the apps I am using, these are the UK versions of the apps. I would like to be able to choose an icon for the apps with no arcticons icon. For example use the 'Where's my train' icon for the Ontime app. I'm using the fdroid release of arcticons dark.

**Comment by Donnnno** [comment]
Depending on your launcher, you can choose custom icons for apps by long pressing it most of the time.
Works with launchers like nova and lawnchair
