### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by txapito** [Donnnno/Arcticons#12]
First of all, thanks for your great work!
I would like icon for
-ungoogled chrome (or ungoogled chrome extension)
-flym
Thanks again

**Comment by txapito** [comment]
[20210106_090111.zip](https://github.com/Donnnno/Arcticons/files/5774544/20210106_090111.zip)
Here it is

**Comment by Donnnno** [comment]
Done! Two new icons, and I've used existing icons for galleria & chromium.

![image](https://user-images.githubusercontent.com/31142286/103758664-c9c9a180-5012-11eb-96ae-4071de9b0548.png)
