### ISSUE TITLE
Websites added to home screen and app function shortcuts

### ISSUE THREAD

**Issue by AnonymousSeal** [Donnnno/Arcticons#1200]
One thing that is left out are Websites linked to the home screen. They show up normally with the browser icon formatted. This looks really distracting.

The other problem is app function shortcuts, the ones you get, when you long press on an app that has them eg standard android clock. (Like: Set Alarm)

Would it be possible to have Icons for those?

For the first: I was thinking you could maybe use the catch-all method you described in another issue: Just design all letters and use the starting letter as the icon for the app.

For the second: If its possible maybe design them?  At least for the more important apps.

There should probably be a toggle in settings to disable this...

I'm very new to this icon pack and icon packs in general an I have to say, that I really like your app. It has a very nice design :)

**Comment by Donnnno** [comment]
Hi, thanks for your feedback.
> One thing that is left out are Websites linked to the home screen. They show up normally with the browser icon formatted. This looks really distracting.

This is something that the launcher handles, depending on the launcher that you're using you can change the site's icon manually.

> The other problem is app function shortcuts, the ones you get, when you long press on an app that has them eg standard android clock. (Like: Set Alarm)

This is also something that the launcher does, and not the icon pack.

Arcticons is an icon pack and not a launcher :)
