### ISSUE TITLE
support for trebuchet

### ISSUE THREAD

**Issue by pragyanone** [Donnnno/Arcticons#1203]
It is not supported on the LineageOS launcher trebuchet.
blank icons rendering

**Comment by Donnnno** [comment]
Hi, unfortunately, this is an issue on trebuchet's side. We can't do anything about it until the LineageOS team fixes it.

See:
https://gitlab.com/LineageOS/issues/android/-/issues/3326

You can let the devs know on GitLab that it's important to you :) 

and
https://github.com/Donnnno/Arcticons/issues/127
