### ISSUE TITLE
Android 11?

### ISSUE THREAD

**Issue by michas0602** [Donnnno/Arcticons#121]
Hi,
not sure if its a question or request - is
your icon pack already tested on Android 11?

One of my mobiles got an update to Lineage 18.1 yesterday and since then Arcticons are just white/not loaded.

I am not sure if its possibly a problem/bug with Lineage 18, or a sort of incompatibility with Android 11...
Greets Michael

**Comment by MonsterSwagger** [comment]
Its the launcher's fault. Not from developer's side.
I'm also using a custom rom running android 11 and can confirm this.

If you have rooted your phone, you can install Shady Launcher as a magisk module and apply the icon pack. That's what i'm doing currently.

**Comment by Donnnno** [comment]
Yes, I also use Android 11, and it works perfectly with nova launcher. What launcher are you using right now?

**Comment by Donnnno** [comment]
@michas0602 Any updates on this issue?

**Comment by michas0602** [comment]
Hi, its Trebuchet and yes, its still actual.
But as said, it happened after the switch from Lineage 17.1 to 18.1, so I think youre right and there is a Problem somewhere in LOS.
Have not updated in the last days, [here](https://download.lineageos.org/vs995/changes/)  is the changelog, it does not look as if there changed something in the last few days in Trebuchet.

**Comment by Donnnno** [comment]
Hmm okey, maybe it's better to open a issue there or test different icon packs and see of those work.

**Comment by michas0602** [comment]
Youre right, I also think its a LineageOS 18.1-problem and close the issue here as its working fine in older Lineage 17.1

**Comment by Donnnno** [comment]
Ah okay, I hope it gets fixed soon ;)
