### ISSUE TITLE
Amaze not recognized?

### ISSUE THREAD

**Issue by spinoza-dat** [Donnnno/Arcticons#122]
Amaze File Manager seems to be included in the icon pack, but it's not recognized automatically.
I'm currently using the com.amaze.filemanager package on version 3.5.3 from IzzyOnDroid, but the same happens when installing from other sources.
Tested with both Arcticons 1.5.0 and 1.4.6 on different launchers based on Lawnchair and Kiss, Android 9.
Thanks for your attention.

**Comment by Donnnno** [comment]
Hey thanks for the heads up. Can you use the Turtl app to collect the information needed to fix it. 

There's a more detailed explanation in the README :)

**Comment by spinoza-dat** [comment]
Of course!


<item component="ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}" drawable="amaze"/>

**Comment by spinoza-dat** [comment]
Here is the .zip file if you need this too.

[20210406_062303.zip](https://github.com/Donnnno/Arcticons/files/6266145/20210406_062303.zip)

**Comment by Donnnno** [comment]
Thanks, just fixed it!
It may take a while to reappear because I released 1.5.2 yesterday, but in the meantime you can change it manually depending on witch launcher you use.
