### ISSUE TITLE
Themed Icons for Material You

### ISSUE THREAD

**Issue by jasons393** [Donnnno/Arcticons#1223]
There is a project that has themed icons (https://github.com/LawnchairLauncher/lawnicons), but it only supports Lawnchair, and it does not have that as many icons as to Arcticons. Because Arcticons is monotone and line-based, it would be nice to have themed icons that match the system colorscheme.

Here is an image of Lawnicons,

![Screenshot_20220622-201233](https://user-images.githubusercontent.com/75338427/175192730-84067bb9-eabf-40f7-adba-0929f4430063.png)

**Comment by jasons393** [comment]
It would be nice to have a workaround, though. I was thinking about the app generating only the icons for the apps installed on the system, so you don't have to generate all the 4000+ icons. It would also be pleasant to pick which colours for the foreground and background.

**Comment by Donnnno** [comment]
You should check out Icon Pack Studio if you want functionality like that! 

For example, this is my Arcticons setup right now:

![image](https://user-images.githubusercontent.com/31142286/175773498-a245b409-3105-409a-9237-7ed2e32086ae.png)

**Comment by jasons393** [comment]
Looks pretty cool, though I would like to avoid proprietary apps as much as possible.

**Comment by Donnnno** [comment]
Understandable, but this is unfortunately out of my scope to create.

**Comment by jasons393** [comment]
I found out that Posidion Launcher allows you to put a custom background for the icons

**Comment by Donnnno** [comment]
Cool!

**Comment by jasons393** [comment]
I found some icon packs in the play store that support material you, so it may be possible to do this.

**Comment by Donnnno** [comment]
can you link it here?

**Comment by jasons393** [comment]
I can't find it in the app store anymore, but it is `com.akbon.myd`

**Comment by Donnnno** [comment]
I'd suggest finding a launcher, or a tool like Icon Pack Studio. Or just buy the material you icon pack ;)

We're focused on the monotone icons for now. 

(Feel free to give it a try yourself!)
