### ISSUE TITLE
Colourative configuration is impossible.

### ISSUE THREAD

**Issue by rokejulianlockhart** [Donnnno/Arcticons#1241]
Arcticons Light is forced to utilize its light theme, whereas Arcticons Dark correctly adapts.

**Comment by Donnnno** [comment]
But what's the problem then?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
That the options provided do not work. They should adhere to the light or dark theme of the system, no?

**Comment by Donnnno** [comment]
I just checked:
Arcticons dark works as intended

Light doesn't have a dark mode. But that's not really necessary for an app that has a focus on the light theme users.

**Comment by Aman9das** [comment]
I'll fix it, my bad..
