### ISSUE TITLE
Odysee from F-Droid does not use Arcticons' icon

### ISSUE THREAD

**Issue by potatoes1286** [Donnnno/Arcticons#1248]
Tested this on two android devices.
Recreation steps:
- Download Niagara Launcher (Have not tested with another launcher that supports icon packs)
- Download F-Droid
- Download Odysee from F-Droid
- Download and apply Arcticons Dark from F-Droid
- Odysee retains its default logo, and must be manually set to Arcticons' Odysee logo

Odysee through Play Store does not exhibit this behaviour.

**Comment by Donnnno** [comment]
Can you send the appfilter name with the icon request qpp?

**Comment by potatoes1286** [comment]
Sent through e-mail.
Just to make sure, here's the details (minus my phone details):
```
Android Version : 12
App Version : 4.3.8
CandyBar Version : 3.14.2


Odysee
com.odysee.floss/com.odysee.floss.MainActivity
https://f-droid.org/en/packages/com.odysee.floss/ 
```
Oddly enough, `com.odysee.floss/com.odysee.floss.MainActivity` seems to already be in appfilter.xml?
I've now tested this with Lawnchair and Rootless Pixel Launcher, both of them also fail to apply Odysee F-Droid.

**Comment by Donnnno** [comment]
very strange, can you try it with another launcher? or clear the cache?

**Comment by Donnnno** [comment]
Works for me with lawnchair and nova, so I'd suggest clearing the cache from arcticons and niagra, or reapply it.

**Comment by prirai** [comment]
Works for me as well. However the themes icon (rocket) looks very different from the original one (bird, perhaps).

**Comment by Donnnno** [comment]
Hmm, maybe it's a typo..

![Screenshot_20220716-014127_Arcticons Light.png](https://user-images.githubusercontent.com/31142286/179324892-a0777df9-0b9a-4593-8abe-6ba7f834d46f.png)

![Screenshot_20220716-014053_Arcticons Light.png](https://user-images.githubusercontent.com/31142286/179324899-0f725792-e75e-47cf-a8c1-62bba6051bb1.png)

**Comment by Donnnno** [comment]
![image](https://user-images.githubusercontent.com/31142286/179395295-cbff6ec7-4a9f-44db-8870-6a0f2f39f3e7.png)

looks all good...

**Comment by prirai** [comment]
Yeah, looks good to me as well. I made a typo there.

**Comment by Donnnno** [comment]
is this solved with the latest version? @prirai

**Comment by prirai** [comment]
Yes, checked it just now. It looks good.
