### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by coxackie** [Donnnno/Arcticons#125]
[20210410_012702.zip](https://github.com/Donnnno/Arcticons/files/6289829/20210410_012702.zip)

Many thanks for your awesome work!

**Comment by Donnnno** [comment]
Hi, Thank you!
I've completed the icons. They will appear in the next update :)
Here's a preview of the new icons:

![image](https://user-images.githubusercontent.com/31142286/114317754-e42b8380-9b09-11eb-8938-4aa84bbf2fed.png)

![image](https://user-images.githubusercontent.com/31142286/114317760-e7267400-9b09-11eb-9ff0-0f237b8bc6f2.png)

Other icons are already in the icon pack, but I've updated those to work. Enjoy!

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks.

**Comment by coxackie** [comment]
Thanks a lot @Donnnno Just to make sure, there were 3 other icons (Librera, Internet Security and Compass). Are you saying that these are already in the icon set? Because I am using the latest version, and they appear as stock icons (like in the zip). I can send you secreenshots if you wish.

**Comment by Donnnno** [comment]
Hi! With the latest update 1.5.5 (not on f-droid yet) those 3 icons should look like this:

**Librera**
![image](https://user-images.githubusercontent.com/31142286/114376433-ea5f4580-9b85-11eb-853b-e59025c01121.png)

**Compass**
![image](https://user-images.githubusercontent.com/31142286/114376459-ee8b6300-9b85-11eb-8a27-3d9f2c24a3a6.png)

**Internet Security**
![image](https://user-images.githubusercontent.com/31142286/114376469-f0edbd00-9b85-11eb-86d4-76c6732cc85c.png)

**Comment by coxackie** [comment]
ok, awesome then - many thanks once again. I will wait for the update!
