### ISSUE TITLE
Amount of available icon-requests resets when storage of Arcticons is reset.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [Donnnno/Arcticons#1252]
The amount of available icon-requests resets when the storage of any of the Arcticons applications is reset. This easily bypasses all restriction, and consequently, I expect is undesirable.

**Comment by Donnnno** [comment]
People who abuse the system will be filtered out. It's pretty easy to notice. ;)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@Donnnno, eek. Apologies!
