### ISSUE TITLE
If opening e-mail app fails, icons are recorded as having been requested anyway.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [Donnnno/Arcticons#1253]
"http://github.com/zixpo/candybar/issues/87#issue-1301111300".

**Comment by Donnnno** [comment]
We use the [Candybar dashboard](https://github.com/zixpo/candybar) and are limited by those features (and sometimes bugs), I'd suggest opening an issue there instead of here because this is out of our scope to solve.
