### ISSUE TITLE
Add option to export image

### ISSUE THREAD

**Issue by DreadedLama** [Donnnno/Arcticons#1257]
There are few webapps creating apps ( like Native Alpha) which allow us to create widgets with custom icons. It would be great if we could export the icons that are already made in Arcticons as images and save them so that we can later use them as widget icons.

Feature Request - Add an option to export images as png or any format.

**Comment by DreadedLama** [comment]
My bad, I see there is already an option to use Arcticons icons.
Hence closing the issue.

**Comment by Donnnno** [comment]
Hey, you can also grab the svg's directly from github or use the search function at arcticons.onnno.nl
