### ISSUE TITLE
Bromite icon issue

### ISSUE THREAD

**Issue by DreadedLama** [Donnnno/Arcticons#1258]
The bromite icon in the "Recents menu" does not use the icon pack icons. 

https://user-images.githubusercontent.com/21179059/178694790-184be0c7-34da-477b-b881-430f43658b2b.mp4

**Comment by dgcampbe** [comment]
Odd. No icons work for me. They are all unthemed.

**Comment by Donnnno** [comment]
Strange indeed, but this is definitely a system thing. So, we can't help you with that, unfortunately.
