### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by dies00irae** [Donnnno/Arcticons#126]
Hi,

A Simple Tools Dialer icon would be great.  Thanks.

**Comment by Donnnno** [comment]
Hi, can you follow the icon request steps explained in the readme? Thanks :)

**Comment by dies00irae** [comment]
I attached the file. Thanks.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Donnnno** [comment]
I don't see it anywhere, where did you attach it?

**Comment by dies00irae** [comment]
I thought I did, but the file is not selectable when I try to attach it.

**Comment by dies00irae** [comment]
I don't know if this info helps, but I got it off of Turtl.  I can attach the png file but not the xml.  

com.simplemobiletools.dialer
com.simplemobiletools.dialer.activities.SplashActivity.Deep_purple

![dialer](https://user-images.githubusercontent.com/39891752/114307634-629a0e00-9a95-11eb-8cd2-f988a2c0074b.png)

**Comment by Donnnno** [comment]
Yes, that's all I need! thanks :)

**Comment by Donnnno** [comment]
Updated it and it should work in the coming update :) 

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks.
