### ISSUE TITLE
Neo Backup (OAndBackupX)

### ISSUE THREAD

**Issue by yetanother-user** [Donnnno/Arcticons#1271]
OAndBackupX has changed its name and icon, it is now called [Neo Backup](https://f-droid.org/en/packages/com.machiav3lli.backup/).

Since the Neo Backup icon is practically identical to the Neo Store icon (#1269 by @prirai) I would like to ask if anyone can create the icon by modifying the Neo Store icon.

---

Neo Backup icon:  

<img src="https://f-droid.org/repo/com.machiav3lli.backup/en-US/icon_B2nW9q-KD-q31G4NZBozmRVebrX1Kmi_u1r5UBFUDJM=.png" width="20%" height="20%">

Neo Store icon:  

<img src="https://f-droid.org/repo/com.machiav3lli.fdroid/en-US/icon_3Z3xAiy1YgGMVf9AveNisZ1l1FiOLexcxkYtN7utlcQ=.png" width="20%" height="20%">

---

[NeoBackup.zip](https://github.com/Donnnno/Arcticons/files/9126883/NeoBackup.zip)

**Comment by Donnnno** [comment]
![Screenshot_20220717-101656_Arcticons Dark_1.png](https://user-images.githubusercontent.com/31142286/179389971-2ebad891-02f4-4de8-bbe8-1edf384cd62d.png)

We already have them, but I've never updated the code ;)
