### ISSUE TITLE
Icon request Osmand Nightly

### ISSUE THREAD

**Issue by basings** [Donnnno/Arcticons#1283]
*Info*
I don't want to open another PR as long as I can't open one properly. Currently, Arcticons doesn't include Osmand nightly. Since osmand and osmand~ share the same icon osmand_nightly.svg, I thought the nightly should have the same icon as well. Is that a good idea?

appfilter.xml

````
	<!-- OsmAnd Nightly -->
	<item component="ComponentInfo{net.osmand.dev/net.osmand.plus.activities.MapActivity}" drawable="osmand_nightly"/>
````

---
*Zip file here*

**Comment by Donnnno** [comment]
Yeah of course, I'll add it when I have some time!

**Comment by basings** [comment]
Cheers! No worries, take your time!

**Comment by Donnnno** [comment]
done
