### ISSUE TITLE
Clock widget does not open Clock app

### ISSUE THREAD

**Issue by basings** [Donnnno/Arcticons#1286]
Problem: Clicking the clock widget does not open the "Clock" app.

I guess this was briefly discussed in #366 but I'm not sure if it was postponed or completed?

os: grapheneos, Android 12

**Comment by Donnnno** [comment]
This has something to do with the Candybar dashboard: https://github.com/zixpo/candybar/issues/81

**Comment by prismacolorgold** [comment]
I have a small request on the clock widget: Can we have the option to enable/disable touch input?

On my note 8 (android 9), when I tap on the clock widget, it doesn't do anything, which is what I want.

On my note 10 (android 12), it opens arcticons homepage. I can't get it to open clock nor calendar app, I'd prefer it not have an action when I tap on it.

**Comment by Donnnno** [comment]
there is a fix on its way, just have to merge it and then people are able again to open the clock app with the widget :)

**Comment by Donnnno** [comment]
Fixed the bug ! 
https://github.com/Donnnno/candybar-foss/pull/6
