### ISSUE TITLE
Two nearly identical icons

### ISSUE THREAD

**Issue by Aliervo** [Donnnno/Arcticons#1297]
I noticed that there are two nearly identical Dolby icons in the pack; "dolby" and "dolbyon".  I would assume these were designed because a Dolby app did not automatically get assigned an icon.  Perhaps we should delete one of the icons and just adjust the appfilter.

Happy to PR this, just figured I would check before I brought the ax to any lovingly crafted icons.

**Comment by Kaiserdragon2** [comment]
These Icons seem to be for different Dolby Apps even so they look similar it might even be better to add something to one icon to distinguish them better

**Comment by Aliervo** [comment]
I just attempted to check the app filter against the playstore. "Dolby On" does show up, but the ``com.dolby.daxappUI`` does not bring up anything. Perhaps it is a old Dolby app or possibly one that comes vendor installed on some phones?

Either way, it seems reasonable to me to just use the one Dolby icon for the both of them as it seems relatively unlikely that someone would have both installed. However, if we do decide to change one of the two, perhaps make Dolby On into a microphone with the Dolby logo on it? [The store page](https://play.google.com/store/apps/details?id=com.dolby.dolby234) says it's a recording app.

**Comment by Donnnno** [comment]
Hey, thanks for the notice, we should delete the dolbyon one ;)

**Comment by Aliervo** [comment]
Pushed to my fork. Should be in my [PR](https://github.com/Donnnno/Arcticons/pull/1298).
