### ISSUE TITLE
Mullvad Icon not Automatically Applying

### ISSUE THREAD

**Issue by MetalNeo** [Donnnno/Arcticons#130]
The Mullvad icon does not get applied automatically to the Mullvad VPN application when installed.

**Comment by Donnnno** [comment]
Hi, thanks for the headsup. Can you use the Turtl app to collect the information needed to fix it.

There's a more detailed explanation in the readme :)

**Comment by Donnnno** [comment]
reminder

**Comment by MetalNeo** [comment]
I followed the directions within the app and was able to get this info out of it:

```
<!-- Mullvad VPN -->
<item component="ComponentInfo{net.mullvad.mullvadvpn/net.mullvad.mullvadvpn.ui.MainActivity}" drawable="mullvadvpn"/>

```

**Comment by Donnnno** [comment]
Thank you, that's all I need to have. 

The next update will come out in the next few days.
