### ISSUE TITLE
Icon request 4pcs

### ISSUE THREAD

**Issue by Aircan** [Donnnno/Arcticons#1304]
`
<item component="ComponentInfo{de.pskiwi.avrremote/de.pskiwi.avrremote.AVRRemote}" drawable="avr-remote"/>`

`
<item component="ComponentInfo{com.github.muellerma.prepaidbalance/com.github.muellerma.prepaidbalance.ui.MainActivity}" drawable="prepaid-guthaben"/>`

`
<item component="ComponentInfo{org.billthefarmer.print/org.billthefarmer.print.Print}" drawable="print"/>`

`
<item component="ComponentInfo{com.github.characterdog.share_my_number/com.github.characterdog.share_my_number.MainActivity}" drawable="teilemeinenummer"/>`

---
Links:

https://github.com/pskiwi/avr-remote

https://f-droid.org/de/packages/com.github.muellerma.prepaidbalance/

https://f-droid.org/de/packages/org.billthefarmer.print/

https://f-droid.org/de/packages/com.github.characterdog.share_my_number/

**Comment by Donnnno** [comment]
Hey, icon requests go through our app, not here.
