### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by rikonten** [Donnnno/Arcticons#131]
Vía explorer
Play store
Mi O2
Ringdroid
"Phone" (the phone botón un havocOS)
The configuración botón un havocOS

Thx

**Comment by Donnnno** [comment]
Hi, Can you use the Turtl app to collect the information needed to create the icons? I can't do anything with this information.

There's a more detailed explanation in the README :)

**Comment by Donnnno** [comment]
reminder

**Comment by Donnnno** [comment]
reminder

**Comment by mubashir-rehman** [comment]
Currently PlayStore app uses AuroraStore icon. However, it should be using PlayStore icon. Even though Aurora Store icon has PlayStore icon as its part in center of it. I will add screenshots later if needed.

**Comment by Donnnno** [comment]
@mubashir-rehman Can you screenshot it?

This should be the playstore icon:

![IMG_20210512_133304.jpg](https://user-images.githubusercontent.com/31142286/117968724-caf33e00-b326-11eb-866b-8a31e41a5ad7.jpg)

And this should be the aurora one:

![IMG_20210512_133242.jpg](https://user-images.githubusercontent.com/31142286/117968762-d6df0000-b326-11eb-83c3-0dda14e5e8f1.jpg)

**Comment by RyuKurisu** [comment]
Play Store shows the correct icon for me.  BTW, why is the basket added in Arcticon icons for the stores?

**Comment by Donnnno** [comment]
@RyuKurisu mostly to give the pack a consistent look. 
There are some other basic shapes like books, files & folders.

**Comment by mubashir-rehman** [comment]
Oh! The default basket shape for stores is confusing. Specially, when fdroid app icon doesn't follow that.

**Comment by Donnnno** [comment]
Ehh, never had a problem with it, I could create two alt icons for google play & aurora that people can select in the launcher.

**Comment by RyuKurisu** [comment]
That would be great, because the 'basket' or 'shopping bag' has been removed from the official Play Store icon since 2014 (https://www.freepik.com/blog/evolution-google-logo-well-play-store-logo/) and I personally think that it should also be the default for them with this icon theme 😎👍

**Comment by Donnnno** [comment]
@RyuKurisu @mubashir-rehman, just updated the Google play icon, now the big triangle is the main one again with an optional basket icon. 

![image](https://user-images.githubusercontent.com/31142286/118407513-5d764300-b681-11eb-8461-80743e84d003.png)

**Comment by mubashir-rehman** [comment]
Thanks. It looks better.

**Comment by mubashir-rehman** [comment]
Can you please change the icons for Google Go Apps(apps for lower end devices) Like GoogleGo, GalleryGo, AssistantGo, Files, CameraGo, etc? The main thing in these icons is word Go within the icon.
