### ISSUE TITLE
Email Parser problem

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#1311]
With the mail provider change to proton mail, I've encountered an issue with our [email parser](https://github.com/Donnnno/Arcticons/blob/main/other/email_parser.py):

The parser doesn't know where to look for the right lines of code...

This is how a normal mails body looks:

```
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
<div>Manufacturer : Fairphone
Model : FP3
Product : FP3
Screen Resolution : 1080 x 2112 pixels
Android Version : 10
App Version : 4.3.8
CandyBar Version : 3.14.2


Time Cop
ca.hamaluik.timecop/ca.hamaluik.timecop.MainActivity
https://f-droid.org/en/packages/ca.hamaluik.timecop/</div>  </body>
</html>
```

And this is proton:

```
<div dir=3D"auto">Manufacturer : Xiaomi<br>Model : M2006C3MG<br>Product : a=
ngelica_global<br>Screen Resolution : 720 x 1449 pixels<br>Android Version =
: 10<br>App Version : 4.6.2<br>CandyBar Version : 3.14.2<br><br><br>airasia=
<br>com.airasia.mobile/com.airasia.mobile.SplashScreenActivity<br><a href=
=3D"https://play.google.com/store/apps/details?id=3Dcom.airasia.mobile">htt=
ps://play.google.com/store/apps/details?id=3Dcom.airasia.mobile</a><br><br>=
Merriam-Webster Dictionary<br>com.merriamwebster/com.merriamwebster.diction=
ary.activity.dictionary.DictionaryActivity<br><a href=3D"https://play.googl=
e.com/store/apps/details?id=3Dcom.merriamwebster">https://play.google.com/s=
tore/apps/details?id=3Dcom.merriamwebster</a><br><br>Shopee<br><a href=3D"h=
ttp://com.shopee.my/com.shopee.app.ui.home.HomeActivity_">com.shopee.my/com=
.shopee.app.ui.home.HomeActivity_</a><br><a href=3D"https://play.google.com=
/store/apps/details?id=3Dcom.shopee.my">https://play.google.com/store/apps/=
details?id=3Dcom.shopee.my</a><br><br>TikTok Lite<br>com.zhiliaoapp.musical=
ly.go/com.ss.android.ugc.aweme.main.homepage.MainActivity<br><a href=3D"htt=
ps://play.google.com/store/apps/details?id=3Dcom.zhiliaoapp.musically.go">h=
ttps://play.google.com/store/apps/details?id=3Dcom.zhiliaoapp.musically.go<=
/a>=C2=A0</div>
```

**Comment by Donnnno** [comment]
Hi @S1SYPHOS ! Thanks for the help.

It's a script that takes lines from icon request emails and put's it in [a large request file](https://github.com/Donnnno/Arcticons/blob/main/other/requests.txt).

The mails look like this:
![image](https://user-images.githubusercontent.com/31142286/186487262-483ba2a2-c92d-4c29-b6ba-8016a98956a5.png)

and like this in the request list:

![image](https://user-images.githubusercontent.com/31142286/186487387-8f3d1573-eddf-4714-ae77-61abc8754650.png)

This is the command I use to run the script
`python email_parser.py ./mail appfilter.xml requests.txt`

**Comment by S1SYPHOS** [comment]
Alright, so basically I'd need a proton mail `eml` file :smiley:

**Comment by Donnnno** [comment]
Thanks, I've just looked at some different emails, but a problem is that they all are slightly different in the way they're formatted..


[emls.zip](https://github.com/Donnnno/Arcticons/files/9418391/emls.zip)

**Comment by Donnnno** [comment]
Haha thanks a lot!

Looks more like hell to me 🙃

**Comment by S1SYPHOS** [comment]
Alright, it's a bit weird, but I tried not using external dependencies for further parsing:

around line 80, when checking `if parsed is None`, I did this:

```python
if parsed is None:
	parsed = msg.get_body().get_content()
	emailBody = "\n".join([TAG_RE.sub('', string) for string in parsed.split('<br>')])

else:
	emailBody = parsed.get_content()
```

.. which gives me this - and no further errors:

```
-------------------------------------------------------
3 Requested Apps Pending (Updated 24 August 2022)
-------------------------------------------------------

<!-- Action Blocks -->
<item component="ComponentInfo{com.google.android.apps.accessibility.maui.actionblocks/com.google.android.apps.accessibility.maui.actionblocks.home.HomeActivity}" drawable="action_blocks" />
https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.maui.actionblocks
https://f-droid.org/en/packages/com.google.android.apps.accessibility.maui.actionblocks/
Requested 1 times
Last requested 1659958279.0
```

**Comment by Donnnno** [comment]
woah sounds great! but I'm getting this message right now:

`"TAG_RE" is not defined`

where should I put that tag?

**Comment by S1SYPHOS** [comment]
Sorry, it's the compiled regex, just at the top, line 47 or so:

```python
TAG_RE = re.compile(r'<[^<]+?>')  # or maybe some other name, something more descriptive
```

**Comment by Donnnno** [comment]
YESSS GREAT!!! it works again, thank you so much!

**Comment by S1SYPHOS** [comment]
It seems to me that this script is used throughout many "icon" pack android apps, correct? 🙃

**Comment by Donnnno** [comment]
Yeah, that's correct. There are other projects using it too :-)

**Comment by S1SYPHOS** [comment]
Well, if it were my project, I'd harden the parser by adding tests - and probably using third party libraries for special cases (mangled HTML being such a special case) 😃

**Comment by Donnnno** [comment]
Thanks! I'm gonna loon into that :+)

**Comment by S1SYPHOS** [comment]
If you need anything , let me know / give a ping!

**Comment by Donnnno** [comment]
Just checked, 10 out of 627 mails weren't working, so that's a huge win!
