### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Trojgarb** [Donnnno/Arcticons#132]
Hi, would be so kind and add few icons for the following apps in next releases?:

    Windy Weather
    Supermemo
    Tresorit
    Nextbike
    MyPhoneExplorer
    Investing
    Mbank

Thank you.

**Comment by Donnnno** [comment]
Hi, Can you use the Turtl app to collect the information needed to create the icons? I can't do anything with this information.

There's a more detailed explanation in the README :)

**Comment by Trojgarb** [comment]
[20210422_095224.zip](https://github.com/Donnnno/Arcticons/files/6360889/20210422_095224.zip)

I hope it will help.

**Comment by Donnnno** [comment]
Yes, thanks

**Comment by Donnnno** [comment]
I've completed the icons. They will appear in the next update :)
Here's a preview of the new icons:

![image](https://user-images.githubusercontent.com/31142286/115835196-4d6a9b00-a416-11eb-8d56-34f866e2b9ac.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks.
