### ISSUE TITLE
Icon request: Nike Running, Tonies, Xing and Stocks Widget

### ISSUE THREAD

**Issue by TobiasDev** [Donnnno/Arcticons#1321]
[20220830_090056.zip](https://github.com/Donnnno/Arcticons/files/9455799/20220830_090056.zip)

**Comment by Donnnno** [comment]
Hi, can you send your icon request per mail? Github is not the place for that.

**Comment by TobiasDev** [comment]
Ah. Sorry! I missed that it was changed. Will do!
