### ISSUE TITLE
Icon request (Threema Libre, +4 more)

### ISSUE THREAD

**Issue by revuwa** [Donnnno/Arcticons#1323]
App Version : 4.6.3
CandyBar Version : 3.14.2

**_Note: [Threema Libre](https://threema.ch/en/blog/posts/threema-libre) is the FOSS version of Threema, which has an existing [icon](https://github.com/Donnnno/Arcticons/issues/1093), what could be used. 
Thanks in advance for any support_** ❤

Battery Charge Notifier
com.utopi.batterychargenotifier/com.utopi.batterychargenotifier.HomepageActivity
https://play.google.com/store/apps/details?id=com.utopi.batterychargenotifier

Fun With Kanji
krillefear.funwithkanji/krillefear.funwithkanji.MainActivity
https://f-droid.org/en/packages/krillefear.funwithkanji/

Infinite English
com.jernung.infinite.eng/com.jernung.infinite.eng.MainActivity
https://play.google.com/store/apps/details?id=com.jernung.infinite.eng

Infinite French
com.jernung.infinite.fra/com.jernung.infinite.fra.MainActivity
https://play.google.com/store/apps/details?id=com.jernung.infinite.fra

Threema Libre
ch.threema.app.libre/ch.threema.app.activities.MainActivity
https://play.google.com/store/apps/details?id=ch.threema.app

---
[icon_request_31_08_2022_23_21_31.zip](https://github.com/Donnnno/Arcticons/files/9465253/icon_request_31_08_2022_23_21_31.zip)

**Comment by Donnnno** [comment]
Hi, I'll update the threema icon, but this isn't the place for icon requests. Can you use the in-app function and send it per mail?
Thanks.

**Comment by revuwa** [comment]
Sure I can, thanks a lot.

**Comment by Donnnno** [comment]
cool! thanks :)
