### ISSUE TITLE
Icon not detected

### ISSUE THREAD

**Issue by Donkey-Doug** [Donnnno/Arcticons#1324]
The app icon for seal is not applied and cannot be manually applied. The Seal app down not show in the icon request section though (unlike stocks widget, see #1325).

https://user-images.githubusercontent.com/50382414/188029036-8a25ba53-cc3b-41af-9783-28cef4f55b88.mp4

**Comment by Donnnno** [comment]
what launcher is this?

**Comment by Donkey-Doug** [comment]
Lawnchair

**Comment by Donnnno** [comment]
And what version? Because I can see it in lawnchair

**Comment by Donkey-Doug** [comment]
Lawnchair 12.1.0 alpha 4

**Comment by Donnnno** [comment]
strange!

**Comment by Donkey-Doug** [comment]
I force restarted lawmchair and now it does show up! So I assume it was a lawnchair issue and not an arcticons issue. 

It still does not detect it automatically though.

**Comment by Donkey-Doug** [comment]
I force restarted lawmchair and now it does show up!

**Comment by Donkey-Doug** [comment]
I also think the stocks widget issue might be fixed by the restart of lawnchair.

**Comment by Donnnno** [comment]
cool!
