### ISSUE TITLE
Icon not detected

### ISSUE THREAD

**Issue by Donkey-Doug** [Donnnno/Arcticons#1325]
The app "stocks widget" has an arcticon icon, but it is not applied/detected. Unlike Seal (see #1324) the icon for stocks widget does show up in "request icons". Maybe it is because there is a play store and fdroid version?

**Comment by Donnnno** [comment]
can you create a bug report in the app and send it here?

**Comment by Donkey-Doug** [comment]
Done

**Comment by Donnnno** [comment]
Fixed the activity for stock widget, pushing an update soon :)
