### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by fractal-fumbler** [Donnnno/Arcticons#134]
Hello :) 
thanks a lot for your work, really fitted in my life styles of icons, love it so much.
submitting few icons, mostly free apps:
1. ru.fourpda.client (4PDA)
2. de.markusfisch.android.libra (Decisions)
3. com.silentlexx.ffmpeggui (GUI for ffmpeg)
4. org.forkclient.messenger.beta (Forkclient - foss fork of telegram app)
5. io.github.forkmaintainers.iceraven (Iceraven - fork of mozilla firefox app)
6. fr.twentynine.keepon 
7. com.leavjenn.longshot
8. org.ibeccato.photoczip
9. com.github.cvzi.screenshottile (Screenshot tile)
10. com.shazam.encore.android
11. com.rom1v.sndcpy (https://github.com/rom1v/sndcpy)
12. com.keramidas.TitaniumBackup
These 2 (com.google.android.GoogleCameraEng & org.codeaurora.snapcam/com.android.camera.CameraLauncher) mods of google camera.

[20210425_105736.zip](https://github.com/Donnnno/Arcticons/files/6372929/20210425_105736.zip)

Thanks in advance :)

**Comment by Donnnno** [comment]
Hi, thank you!
Just took a quick look, some icons already existed but didn't have the code to make it work. Also used some existing ones for other icons.

- 3pda > `number4.svg`
- camera > `googlecamera.svg`
- iceraven >`iceraven.svg`
- shazamencore > `shazam.svg`
- sndcpy > `android.svg`
- titaniumbackup > `tibackup.svg`

(you can see them in the icons folder)

I'll take a look at the others when I have some more time.

**Comment by Donnnno** [comment]
And the remaining icons, I'll add them in the next update.

![image](https://user-images.githubusercontent.com/31142286/116081616-c37f3400-a69a-11eb-86fd-75b410697903.png)

Enjoy.

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
