### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by frpst** [Donnnno/Arcticons#135]
Hello! Loving your pack. Almost all my apps where included already but these ones. Orgzly is the only FLOSS one, sadly. (Podcasts is the Google podcast app)

[20210426_122956.zip](https://github.com/Donnnno/Arcticons/files/6376340/20210426_122956.zip)

**Comment by Donnnno** [comment]
Hi, thanks! Created these icons:
(Orgzly already has an icon)

![image](https://user-images.githubusercontent.com/31142286/116077140-6cc32b80-a695-11eb-822c-d5b354a698f2.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)

**Comment by frpst** [comment]
Thank you so much! They look great. I use the Orgzly version from the play store (to get the Dropbox function), could you perhaps make it so that one has the same logo as Orgzly from f-droid :)? 

What happens next? Are these pushed to the official release eventually? Or should I try to get them in myself somehow? Thanks again.

**Comment by Donnnno** [comment]
> could you perhaps make it so that one has the same logo as Orgzly from f-droid :)?

Already did that!

> What happens next?

I'll probably push an update later this week or next week (depends on how busy I am). And then you can find it on F-Droid or download it from here. 

F-Droid builds do take some time, yesterday I published 1.6.0, so it needs to build that one first.

Oh, and thanks for the coffee :)

**Comment by Donnnno** [comment]
![image](https://user-images.githubusercontent.com/31142286/116083675-31c4f600-a69d-11eb-9af1-9331758c6ffc.png)
 
this is the orgzly icon btw
