### ISSUE TITLE
Omega Launcher disappeared (detected as NEO Launcher)

### ISSUE THREAD

**Issue by totoroot** [Donnnno/Arcticons#1357]
Hey Donnno,

With the recent update to Arcticons Dark v4.7.0, the Android launcher I've been using for a while with this icon set, Omega Launcher, has disappeared from the launcher selection menu in the app.

When I click on "Apply Arcticons Dark", I'm prompted to install the NEO Launcher.

![Apply Prompt](https://i.imgur.com/Oj130gR.jpg)

For the icons that got added with the v4.7.0 update, the apps still show the old icons, so I believe the new, most recent version of the icon set did not get applied to the launcher, although it is installed.

![Omega Launcher Icon Set](https://i.imgur.com/XAhnS2t.jpg)

I've got the most recent version of Omega Launcher installed:
Version: 0.8.1
Build: 280

![Omega Launcher Version](https://i.imgur.com/f8NPd51.jpg)

Not sure how to troublehsoot this, but let me know, if I should provide some additional information.

Thanks in advance!

**Comment by Donnnno** [comment]
Hey, Neo Launcher is the same as Omega Launcher, but just with a different name. It's part of a rebranding to unify some apps.

You should check it out :-)

**Comment by Donnnno** [comment]
![Screenshot_20221007-151513_Neo Launcher.png](https://user-images.githubusercontent.com/31142286/194562520-9108b872-0076-41a3-8819-4ae7afa1a1a9.png)
