### ISSUE TITLE
Icon Request from app not proceeding to email app

### ISSUE THREAD

**Issue by clayb91** [Donnnno/Arcticons#1374]
Hi!

I am trying to request app icons via the app. When I select the 5 icons, then tap the send arrow, it asks which app to use (GMail is the only option for me). It then just disappears, says that the icons were requested, but no email was sent.

Phone is Pixel 7 Pro, app was downloaded from F-Droid, installed version is 4.8.5

**Comment by Donnnno** [comment]
Yes this is fixed now, an update will be released soon! 
https://github.com/Donnnno/candybar-foss/commit/2c321a48bf13a773f1a9d13cbdc92398d85ca3ff
