### ISSUE TITLE
Sonic Runners Revival not using existing icon.

### ISSUE THREAD

**Issue by TwinniDev** [Donnnno/Arcticons#1378]
It is as the title says. Of course the original Sonic Runners is now defunct, so reusing the existing icon for the fan-hosted "revival" would be nice. [This project](https://sonicrunners.com/#/) by the way. If it's relevant, it is under "com.sonicrunners.revival".

**Comment by Kaiserdragon2** [comment]
Could you gather the appfilter code with this app: https://github.com/Kaiserdragon2/IconRequest/releases and
provide it here.

**Comment by TwinniDev** [comment]
<item component="ComponentInfo{com.sonicrunners.revival/com.unity3d.player.UnityPlayerNativeActivity}" drawable="sonic_runners_revival"/>
