### ISSUE TITLE
Dynamic calendar icons not working

### ISSUE THREAD

**Issue by coxackie** [Donnnno/Arcticons#139]
I am not sure whether this is related to #100, but the google calendar icon does not behave "dynamically". I mean, I can see the (arct)icon ok, but it always shows "31". I am using 1.6.1, but the issue was there since 1.5, I am sure, as I never noticed it working. I thought it was not possible to display date dynamically, but I checked the icons and there seems to be one for each day of the month, so I though something is amiss... Using Arrow OS, with stock (Arrow) launcher fyi.

**Comment by RyuKurisu** [comment]
I am seeing the dynamic numbering with Google calendar on Lawnchair, so maybe it is a launcher issue?

**Comment by Donnnno** [comment]
Hi! It's a launcher issue for sure. It's on the launcher's side to implement the dynamic feature. If it doesnt support it, it uses a fallback (the 31 icon). 

You can ask the launcher devs to implement it ;)

**Comment by coxackie** [comment]
Many thanks. Have confirmed it is indeed the case. Closing this.

**Comment by Donnnno** [comment]
Cool, you could use another launcher that does support it if you want it :)
