### ISSUE TITLE
Appfilter entries lost

### ISSUE THREAD

**Issue by petlyh** [Donnnno/Arcticons#1399]
Hi,
I just downloaded the latest release and noticed some apps no longer showed icons on my device.
It appears that some appfilter entries got lost in this commit: 78df8910cb2276dc44a6d572484ff9fe532f3312
Although I haven't checked all of them, it seems like all entries that were added in the previous release 4.8.5 may be affected.

**Comment by Donnnno** [comment]
Hi! I'm aware that something has gone wrong! Gonna look at a quick fix tomorrow!!

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Donnnno** [comment]
These are fixed now I think, for in the future, place all your appfilter entries in one place, it's easier to track for me that way :)

**Comment by petlyh** [comment]
Got it
Congrats on 5K icons, by the way :-)
