### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by starbuckbok** [Donnnno/Arcticons#140]
five icons, if possible please. one is a discreet icon for an adult app, so I understand if you do not want to do it.
 
[icons.zip](https://github.com/Donnnno/Arcticons/files/6421843/icons.zip)

**Comment by Donnnno** [comment]
Hi, just finished your request, I released an update 3 days ago so you'll have to wait a bit for the next release.

Here's a preview of the new icons:

![image](https://user-images.githubusercontent.com/31142286/117171248-004dd800-adcb-11eb-8941-09869a87182f.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
