### ISSUE TITLE
add "silver" version to mixplorer icon

### ISSUE THREAD

**Issue by coxackie** [Donnnno/Arcticons#141]
this will require minimal amount of effort: please use the `com.mixplorer` icon also for `com.mixplorer.silver`. See attached - they use the same icon, really.

[20210505_060530.zip](https://github.com/Donnnno/Arcticons/files/6428948/20210505_060530.zip)

**Comment by Donnnno** [comment]
Sure

**Comment by coxackie** [comment]
many thanks for this. Could I ask for a similar add of the icon of `dk.tacit.android.foldersync.lite` (which is FolderSync, free version, and you have already created it) to `dk.tacit.android.foldersync.full` (FolderSync, paid version, which should have the same (arct-)icon but at this point it does not exist)?
