### ISSUE TITLE
Icons not detected

### ISSUE THREAD

**Issue by s-slash** [Donnnno/Arcticons#1410]
Icons for Airbnb and a banking app are available in the app but are not applied.
I tested 4 differents launchers (1+, posidon, lawnchair, neolauncher).
When requesting icons for these 2 apps, I got : 

"Airbnb
com.airbnb.android/com.airbnb.android.feat.splashscreen.SplashScreenActivity
https://f-droid.org/en/packages/com.airbnb.android/"

Icon shoud be : Airbnb

"Ma Banque
fr.creditagricole.androidapp/fr.ca.cats.nmb.start.StartActivity
https://f-droid.org/en/packages/fr.creditagricole.androidapp/"

Icon should be : Creditagricole

Thanks you for your work.

**Comment by Donnnno** [comment]
Thanks for reporting, updated it!
