### ISSUE TITLE
[Crash Report] Arcticons light crash after launching from nova launcher.

### ISSUE THREAD

**Issue by subham2024** [Donnnno/Arcticons#1414]
Icon Pack Name : Arcticons Light
Manufacturer : samsung
Model : SM-M325F
Product : m32dd
Screen Resolution : 1080 x 2196 pixels
Android Version : 13
App Version : 5.0.1
CandyBar Version : 3.16.1
Crash Time : 2022-12-31 11:20:45
Class Name : java.lang.NullPointerException
Caused By : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference

o1.l.R1(Unknown Source:36)
o1.l.Q1(Unknown Source:0)
o1.k.a(Unknown Source:2)
z5.u.b(Unknown Source:29)
z5.j.m(Unknown Source:151)
z5.j.b(Unknown Source:0)
z5.g.run(Unknown Source:2)
z5.u$a.g(Unknown Source:2)
androidx.recyclerview.widget.RecyclerView.onDraw(Unknown Source:22)
android.view.View.draw(View.java:24395)
androidx.recyclerview.widget.RecyclerView.draw(Unknown Source:0)
android.view.View.updateDisplayListIfDirty(View.java:23256)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
androidx.recyclerview.widget.RecyclerView.drawChild(Unknown Source:0)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.draw(View.java:24398)
androidx.recyclerview.widget.RecyclerView.draw(Unknown Source:0)
android.view.View.updateDisplayListIfDirty(View.java:23256)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
androidx.drawerlayout.widget.DrawerLayout.drawChild(Unknown Source:95)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.draw(View.java:24398)
android.view.View.updateDisplayListIfDirty(View.java:23256)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
android.view.View.updateDisplayListIfDirty(View.java:23242)
android.view.View.draw(View.java:24125)
android.view.ViewGroup.drawChild(ViewGroup.java:4748)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1531)
android.view.View.draw(View.java:24398)
com.android.internal.policy.DecorView.draw(DecorView.java:1504)
android.view.View.updateDisplayListIfDirty(View.java:23256)
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:753)
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:759)
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:857)
android.view.ViewRootImpl.draw(ViewRootImpl.java:5501)
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5194)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4356)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2991)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10665)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
android.view.Choreographer.doCallbacks(Choreographer.java:923)
android.view.Choreographer.doFrame(Choreographer.java:852)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
android.os.Handler.handleCallback(Handler.java:942)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loopOnce(Looper.java:226)
android.os.Looper.loop(Looper.java:313)
android.app.ActivityThread.main(ActivityThread.java:8741)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by Donnnno** [comment]
Yes, we're aware, the next version will contain a fix for it !

**Comment by Donnnno** [comment]
This was fixed with candybar 3.16.2!
