### ISSUE TITLE
Note to self: update the font svg file

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#1416]
There are weird things in there

**Comment by kaanelloed** [comment]
Yes, the 3 is weird, the 7 and the B don't have the right stroke width, the G doesn't have the same height as the other rounded letters. I was about to open a problem about this.

**Comment by Donnnno** [comment]
Cleaned up the whole document, it should be better now :)

![image](https://user-images.githubusercontent.com/31142286/210792563-60dd7eea-db33-4e11-9415-8d5dfd69dbfe.png)

**Comment by Donnnno** [comment]
Updated the font again with some tiny fixes
