### ISSUE TITLE
Rearrange the other folder

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#1421]
We probably should put the scripts in a scripts folder and new icons in a submitted icons folder, without breaking the scrips.

**Comment by Kaiserdragon2** [comment]
That should be possible some scripts might need to be rewritten to accept additional arguments like the email parser script we even could merge some scripts like raster.sh black.sh

**Comment by Donnnno** [comment]
yeah, probably gonna figure those things out next week
