### ISSUE TITLE
Cambio icon not showing correctly

### ISSUE THREAD

**Issue by zykure** [Donnnno/Arcticons#1433]
Icon for the Cambio app is not showing correctly. It has this code in `appfilter.xml`:

```
    <!-- Cambio -->
    <item component="ComponentInfo{de.cambio.app/de.cambio.app.SplashScreenActivity}" drawable="cambio" />
```

This seems to be correct according to the IconRequest app, but it still shows the original icon. I can't see what's going wrong here :(

![Screenshot_20230113-083406_IconRequest_1](https://user-images.githubusercontent.com/54305315/212823516-33c5a567-7d2b-463e-a4a6-d710d43a1613.png)
![Screenshot_20230113-083203_hyperion_1](https://user-images.githubusercontent.com/54305315/212823525-af2a128b-540a-4ffb-a7f6-f1bf8f98766b.png)

IconRequest file:
[IconRequest_17012023_070955.zip](https://github.com/Donnnno/Arcticons/files/10431900/IconRequest_17012023_070955.zip)

**Comment by aloxe** [comment]
@zykure Have you tried to change to a different icon set and putting back Articons. Sometimes that helps clearing the cache from old icons.

**Comment by Donnnno** [comment]
Sounds like an external problem, checked the code, but there isn't anything I can do about this. 
Try clearing cache or reapplying the icon-pack.

**Comment by zykure** [comment]
@aloxe That did the trick, thank you!
