### ISSUE TITLE
Several icons not displaying

### ISSUE THREAD

**Issue by Cguy7777** [Donnnno/Arcticons#1434]
Several icons are not appearing for me, even though I believe all of these are in the pack. None of them, except for HBO Max, appear in the Icon Request list in the app.

DTEK, HBO Max, and Power Center don't show their icon in any of the launchers I have tried. The icon for Calendar does not show in OpenLauncher, but works in the others.

Launchers: KISS Launcher 3.19.0, OpenLauncher 0.7.4, BlackBerry Launcher 2.1902.1.10150
Info from Turtl:
```
<!-- Calendar -->
<item component="ComponentInfo{com.blackberry.calendar/com.blackberry.calendar.AllInOneActivity}" drawable="calendar"/>
<!-- DTEK by BlackBerry -->
<item component="ComponentInfo{com.blackberry.privacydashboard/com.blackberry.privacydashboard.SafeguardActivity}" drawable="dtekbyblackberry"/>
<!-- HBO MAX -->
<item component="ComponentInfo{com.hbo.hbonow/com.hbo.hbonow.MainActivity}" drawable="hbomax"/>
<!-- Power Center -->
<item component="ComponentInfo{com.blackberry.batterycenter/com.blackberry.batterycenter.LaunchActivity}" drawable="powercenter"/>
```

Thank you for your time!

**Comment by Donnnno** [comment]
Just checked, I couldn't find DTEK or Power Center in the icon-pack. 

I've updated the entry for HBO Max. 

The calendar app should work right on KISS, Open Launcher has some known problems: https://github.com/Donnnno/Arcticons/issues/100
