### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Sord1d** [Donnnno/Arcticons#144]
[20210508_101713.zip](https://github.com/Donnnno/Arcticons/files/6446494/20210508_101713.zip)

Hey, first I want to thank you for your great work. I really love this icon pack.
Sadly there are no Icons for four apps installed on my device (Ing Banking DE, iNaturalist, Chatcraft and MeinBlau).
I have attached the turtl zip to this issue, maybe these Icons could be created / added.

Thank you

**Comment by Donnnno** [comment]
Thank you for the compliments! Great to hear you like it.
I've created the icons & they will appear in the next update :)

Here's a preview: 

![image](https://user-images.githubusercontent.com/31142286/117553921-97799080-b054-11eb-960c-3daa5ef4151d.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
