### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by jcperil** [Donnnno/Arcticons#1440]
1. [Quillpad](https://github.com/quillpad/quillpad)
2. [Linux Command Library](https://github.com/SimonSchubert/LinuxCommandLibrary)
3. [TTS-Util](https://github.com/Danesprite/tts-util-app)
4. [PDF Scanner](https://play.google.com/store/apps/details?id=com.camscanner.documentscanner.pdfscanner.textscanner.photos.scanner)
5. Sound Recorder (com.android.soundrecorder)
6. Camera (com.android.camera) - Due to multiple camera apps, it is hard to detect which one is which.

---
Screenshot of sound recorder icon

<img src="https://user-images.githubusercontent.com/89805719/215081812-f8374d6b-271b-4f90-9e60-72d91aeb7ed2.jpg" height="300px"/>

Screenshot of camera icon

<img src="https://user-images.githubusercontent.com/89805719/215074946-64505afb-fdd5-47f6-a27b-b354777b0ee4.jpg" height="300px"/>

**Comment by Donnnno** [comment]
Hi, we don't do icon requests with GitHub anymore, the only way now is in the app! 

But you can send the code from the stock recorder and camera app with icon request here:
https://github.com/Kaiserdragon2/IconRequest/releases

**Comment by jcperil** [comment]
I am a little confused. Do you mean I should request 1-4 from Arcticons Icon Request (via email) and 5-6 in [Kaiserdragon2/IconRequest](https://github.com/Kaiserdragon2/IconRequest/issues/new)? Can you please clarify?

**Comment by jcperil** [comment]
Is this the correct format of submitting requests?

Icon Request: [icon_request.zip](https://github.com/Donnnno/Arcticons/files/10529358/icon_request.zip)

Icon Request was unable to recognize [Linux Command Library](https://github.com/SimonSchubert/LinuxCommandLibrary) as one of the missing icons.

**Comment by dgcampbe** [comment]
I just checked and here is the app filter:
```
	<!-- Linux Command Library -->
	<item component="ComponentInfo{com.inspiredandroid.linuxcommandbibliotheca/com.inspiredandroid.linuxcommandbibliotheca.MainActivity}" drawable="linux_command_library"/>
```

**Comment by Donnnno** [comment]
I meant that you should follow these instructions: https://github.com/Donnnno/Arcticons#icon-requests :)

**Comment by jcperil** [comment]
By email, understood. There is one minor issue. Icon Request recognized 5 out of the 6 missing icons. I can submit those 5 via email.

How can I submit the last one? Component info of Linux Command Library is mentioned above by @dgcampbe.

**Comment by Donnnno** [comment]
Wait till the next update ;) We're getting loads of requests from hundreds of users so we gotta limit the requests.

**Comment by dgcampbe** [comment]
Oddly, Linux Command Library doesn't show up for me as an option to request in Articons, either. Perhaps this is a symptom of a bug in Articons?

**Comment by Donnnno** [comment]
> Oddly, Linux Command Library doesn't show up for me as an option to request in Articons, either. Perhaps this is a symptom of a bug in Articons?

Probably a candybar thing then

**Comment by Donnnno** [comment]
Just noticed that Linux Command Library will be added next update :) #1430
