### ISSUE TITLE
Add support for Discreet Launcher

### ISSUE THREAD

**Issue by jcperil** [Donnnno/Arcticons#1441]
Please add support for [Discreet Launcher](https://github.com/falzonv/discreet-launcher)
___
It failed to apply Anonaddy icon.

![discreetlauncher](https://user-images.githubusercontent.com/89805719/215081312-4697bd0c-bcb8-4f3a-9fe1-514bc02fb5ba.jpg)

**Comment by Donnnno** [comment]
Can you send the component info with icon request, so I can check if the Arcticons code is correct? 
https://github.com/Kaiserdragon2/IconRequest/releases

**Comment by jcperil** [comment]
Do you mean this?

<appfilter>

	
	<item component="ComponentInfo{host.stjin.anonaddy/host.stjin.anonaddy.GradientIcon}" drawable="anonaddy"/>

</appfilter>

**Comment by Donnnno** [comment]
Fixed this one, should work again in the next release!
