### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by nomadpublic** [Donnnno/Arcticons#145]
[20210508_105933.zip](https://github.com/Donnnno/Arcticons/files/6446580/20210508_105933.zip)

**Comment by Donnnno** [comment]
Hi, I've created the icon, I'll add it in the next update:

![image](https://user-images.githubusercontent.com/31142286/117554227-98132680-b056-11eb-84a2-4119ce5a21ac.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
