### ISSUE TITLE
Failed to apply Quillpad icon because of wrong icon name

### ISSUE THREAD

**Issue by jcperil** [Donnnno/Arcticons#1450]
The name of the app is [Quillpad](https://github.com/quillpad/quillpad) while the icon name in Arcticons Dark is written Quilpad. Perhaps that is why the icon failed to apply?!

<img src="https://user-images.githubusercontent.com/89805719/218772252-29a3087f-8be7-42c1-8dce-bc8dfad41bfc.jpg" height="300px"/>

**Comment by Donnnno** [comment]
oops, that's a typo! Will fix it in the next version
