### ISSUE TITLE
Failed to apply Arity and Bybit

### ISSUE THREAD

**Issue by jcperil** [Donnnno/Arcticons#1455]
Launcher: Discreet Launcher

Despite having icons, [Arity](https://github.com/woheller69/Arity) and [Bybit](https://play.google.com/store/apps/details?id=com.bybit.app) failed to apply with Arcticons Dark v5.2.6.

<img src="https://user-images.githubusercontent.com/89805719/220128675-82473638-02b8-48f3-a76b-1b7d861c7db6.jpg" height="200px"/>

*Remarks:*
*1. As far as I recall, Bybit applied correctly with v5.1.0. Don't know what happened with v5.2.6.*
*2. The situation with Arity is confusing. F-Droid names it ArityCalc but all my launchers name it Arity in the app drawer*.

**Comment by jcperil** [comment]
<appfilter>

	
	<item component="ComponentInfo{org.woheller69.arity/arity.calculator.Calculator}" drawable="arity"/>

	
	<item component="ComponentInfo{com.bybit.app/com.bybit.pro.MainActivity}" drawable="bybit"/>

</appfilter>

**Comment by Donnnno** [comment]
Should be fixed in the next release!
