### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by karnotcycle** [Donnnno/Arcticons#146]
I tried the turtl app but I am unable to find the default storage of turtl in android 11 to find the zip. But when I chose to email the contents generated from the share screen, this is the message that was output.

some FLOSS app icons are missing on my device. This email was generated by turtl.
AnLinux
Fabularium
Finder
Libero Vocab
Radio
Stocks Widget

<item component="ComponentInfo{exa.lnx.a/exa.lnx.a.MainUI}" drawable="anlinux"/>

<item component="ComponentInfo{io.davidar.fabularium/com.luxlunae.fabularium.MainActivity}" drawable="fabularium"/>

<item component="ComponentInfo{ru.seva.finder/ru.seva.finder.MainActivity}" drawable="finder"/>

<item component="ComponentInfo{org.inventati.massimol.liberovocab/org.inventati.massimol.liberovocab.activities.MainMenuActivity}" drawable="liberovocab"/>

<item component="ComponentInfo{com.sec.android.app.fm/com.sec.android.app.fm.MainActivity}" drawable="radio"/>

<item component="ComponentInfo{com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.home.SplashActivity}" drawable="stockswidget"/>

Thank you, in advance. I'll try to make a pull request for one or two of the icons if possible.

**Comment by karnotcycle** [comment]
<item component="ComponentInfo{exa.lnx.a/exa.lnx.a.MainUI}" drawable="anlinux"/>

<item component="ComponentInfo{io.davidar.fabularium/com.luxlunae.fabularium.MainActivity}" drawable="fabularium"/>

<item component="ComponentInfo{ru.seva.finder/ru.seva.finder.MainActivity}" drawable="finder"/>

<item component="ComponentInfo{org.inventati.massimol.liberovocab/org.inventati.massimol.liberovocab.activities.MainMenuActivity}" drawable="liberovocab"/>

<item component="ComponentInfo{com.sec.android.app.fm/com.sec.android.app.fm.MainActivity}" drawable="radio"/>

<item component="ComponentInfo{com.github.premnirmal.tickerwidget/com.github.premnirmal.ticker.home.SplashActivity}" drawable="stockswidget"/>

**Comment by karnotcycle** [comment]
[icons.txt](https://github.com/Donnnno/Arcticons/files/6446864/icons.txt)

**Comment by Donnnno** [comment]
Hi, turtl can be a bit annoying to use sometimes. I'm using android 11 too and you have to give it storage permission manually. When you've done that and select some icons it will create a zip file.

**Comment by karnotcycle** [comment]
[20210509_033920.zip](https://github.com/Donnnno/Arcticons/files/6447321/20210509_033920.zip)


Here, got it!. Will this help ?

**Comment by Donnnno** [comment]
Yes! I'll take a look when I have some time :)

**Comment by Donnnno** [comment]
I've created the icons & they will appear in the next update :)

Here's a preview:

![image](https://user-images.githubusercontent.com/31142286/117572468-5a081800-b0d3-11eb-8687-8d39d852833b.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)

**Comment by Donnnno** [comment]
radio has already an icon so I updated that one

**Comment by karnotcycle** [comment]
Thanks a ton. I'll surely star it. I will try to put some buck as well but that might be hard given my current position. But this is one of the projects that I follow closely. So if not now I'll surely help out as and when I can in the future. Thank you.

-------- Original Message --------

**Comment by Donnnno** [comment]
that's no problem ofcourse :) Nothing is mandatory here. Glad you like the icon pack!
