### ISSUE TITLE
can't distinguish threema and threema work icon

### ISSUE THREAD

**Issue by Sertonix** [Donnnno/Arcticons#1468]
Threema and Threema Work have the same arcticon icons.
Since my home launcher doesn't show the app name (and I want it like that) I don't know which application is which.
The original icons only have a difference in the color.

I don't know what would look nice. Maybe a "W" in the icon for work?

**Comment by Donnnno** [comment]
good one!

**Comment by Donnnno** [comment]
Voilà~ 

![image](https://user-images.githubusercontent.com/31142286/226108295-3454f5bf-e4f3-4fc2-a7e3-d0743f49859d.png)
