### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by aaronhatesregex** [Donnnno/Arcticons#147]
[IconRequest.zip](https://github.com/Donnnno/Arcticons/files/6451870/IconRequest.zip)

- [ ] AppOpsX
- [ ] DingTalk
- [ ] HUAWEI HiLink
- [ ] Metro大都会
- [ ] Really Bad Chess

*Maybe* I can find some time and play around with Inkscape. Anyway I just put the archive here in case the schedule is fully occupied.

**Comment by Donnnno** [comment]
Had some time today to create these icons :) 

![image](https://user-images.githubusercontent.com/31142286/117664692-5db6a000-b1a2-11eb-9af9-42f0b5e014bc.png)
