### ISSUE TITLE
MLB App Icon Replaced with New York Yankees Logo Icon

### ISSUE THREAD

**Issue by dreamfall88** [Donnnno/Arcticons#1474]
The icon for the Official MLB app has been replaced with an icon of the logo for the New York Yankees. Icon for MLB app is completely gone from from the library.

NHL app seems to default to icon of the Rangers logo, but the NHL icon is still present in library.

**Comment by Donnnno** [comment]
@akp37 , you did this one right?

**Comment by Donnnno** [comment]
Reverted the appfilter changes, the apps should appear normal again :-)
