### ISSUE TITLE
Icon request feed back 

### ISSUE THREAD

**Issue by rimwulf** [Donnnno/Arcticons#1477]
Instructions don't seem to be up to date on how to submit an icon; it's either that or I need my hand held. 

![Arc Launcher](https://user-images.githubusercontent.com/89753591/225880850-0ffd1590-2f93-4bce-a25e-1e1dc2464bb3.svg)

![ARK Pro](https://user-images.githubusercontent.com/89753591/225880761-b52f7cd8-1dbe-407d-a7a6-1d20e44bf39e.svg)
*Info

https://play.google.com/store/apps/details?id=apptech.arc

https://play.google.com/store/apps/details?id=apptech.arc.pro

Arcticons look pretty good on this launcher BTW

---
*Zip file here*

**Comment by wwwwwwari** [comment]
Since they've been inactive a while, should I take and re-submit these icons the correct way for them?

**Comment by Donnnno** [comment]
That would be great! Thanks
