### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by yetanotherfossman** [Donnnno/Arcticons#148]
Thank you so much for this wonderful icon pack! Just there are some FOSS apps that doesn't have its icon yet. Could you make them?

* 1010! Klooni
* Arity
* OI Notepad
* TimeTable
* Hypatia
* Lesser Pad
* Todo List (Privacy Friendly)
* Note Crypt Pro
* PermissionsManager
* PReVo
* Rule of Three
* Screen Recorder
* Simple Text Crypt
* TowerJumper
* Ungoogled Chromium
* Units

Sorry, it's a lot. I can wait, no problem :)

[20210509_121319.zip](https://github.com/Donnnno/Arcticons/files/6452473/20210509_121319.zip)

**Comment by Donnnno** [comment]
Thanks for the compliments! I'll take a look when I have some time :)

**Comment by Donnnno** [comment]
I've created the icons & they will appear in the next update :)
Some icons already existed so I updated those ones.

Here's a preview:

![image](https://user-images.githubusercontent.com/31142286/117735220-540a5800-b1f5-11eb-99d8-90c7c6a42c96.png)
![image](https://user-images.githubusercontent.com/31142286/117735222-566cb200-b1f5-11eb-8d73-a8e7f00a337a.png)
![image](https://user-images.githubusercontent.com/31142286/117735217-52409480-b1f5-11eb-8283-4aeedc8fa037.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
