### ISSUE TITLE
Dark Arcticons background 

### ISSUE THREAD

**Issue by fabykr** [Donnnno/Arcticons#1497]
Hi there, thanks a lot for your work. Looks really great! I would have a suggestion for the black version of your icons. Maybe there is a design reason that the background is not real black. But that would look really good on all those oled screens with a black background. Without a black background the contrast will look a bit hard I have to admit.

**Comment by Donnnno** [comment]
Hi! What background are you talking about? All icons are fully transparent, so the line color for Arcticons Dark is white (#ffffff) and for Arcticons Light black (#000000).

It might be a launcher setting you didn't turn off that gives icons a shape.

**Comment by fabykr** [comment]
Oh no, sorry. You are right. Nova launcher did this in order to standardize the look of the icons. You can turn it off and it's gone. Thanks for your time !
