### ISSUE TITLE
Add support for com.android.launcher3 known as Trebuchet

### ISSUE THREAD

**Issue by Mannshoch** [Donnnno/Arcticons#1499]
Please add support for com.android.launcher3 known as Trebuchet

**Comment by Donnnno** [comment]
Hi! The lineageOS team has to do this for trebuchet. We can't do anything about it right now. :(

**Comment by Donnnno** [comment]
Hi! Sorry, closed it a bit too quickly. Do you mean an option to apply from the Arcticons app, or a way to select it in the Trebuchet app?

**Comment by skedastically** [comment]
You should first check whether Trebuchet supports custom icon packs. If not, you may wanna install a different launcher to apply these icons

**Comment by Mannshoch** [comment]
I would prefer if https://github.com/LineageOS/android_packages_apps_Trebuchet would add such a feature. I tested some Launcher available in fdroid and see that trebuchet seems currently the best solution.

**Comment by Donnnno** [comment]
Trebuchet had support in the past, but removed it with newer versions. So we can't help you with this.

The only thing that you can do probably is opening an issue on their gitlab, or switch to a launcher like nova, neo or lawnchair
