### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by tuch96** [Donnnno/Arcticons#152]
[20210512_102515.zip](https://github.com/Donnnno/Arcticons/files/6468927/20210512_102515.zip)

Hej! Please find enclosed a new icon request. Thanks a lot for your support and this perfect icon pack!!

**Comment by Donnnno** [comment]
I'll take a look when I have some time :)

**Comment by Donnnno** [comment]
Used this existing icon for your request:

![image](https://user-images.githubusercontent.com/31142286/118359585-75b46800-b584-11eb-8b84-1e12672ff9f3.png)

**Comment by tuch96** [comment]
Perfect and thanks for your support!
