### ISSUE TITLE
Wrong icon

### ISSUE THREAD

**Issue by KevinBlue28** [Donnnno/Arcticons#1523]
*Info*
_App Manager_ selecting _Settings_ icon by default.

---
*Image proof*
![image](https://user-images.githubusercontent.com/99153437/236655789-9cfd368e-d8e0-41df-9405-ea0731edea8c.png)

**Comment by Donnnno** [comment]
Image not found!

Also how _should_ it look?

**Comment by KevinBlue28** [comment]
> Image not found!
> 
> Also how _should_ it look?

Sorry it took me long to fix link. I got busy after posting.

**Comment by Donnnno** [comment]
So, it should look like a settings icon within a box?

**Comment by Donnnno** [comment]
ah solved the issue, should be visible in the next release!
