### ISSUE TITLE
2 app in my app list not auto recognizing with any launcher.

### ISSUE THREAD

**Issue by dheeraj025** [Donnnno/Arcticons#1533]
Hi
Below are details of those 2 app.
Arcticons have icons for them but they dont get applied automatically.
With most launcher i can select manually.
But i prefer discreet launchr and they dont have option to set app icons manually.

Manufacturer : OnePlus
Model : DN2101
Product : DN2101IND
Screen Resolution : 1080 x 2181 pixels

Bajaj Finserv
org.altruist.BajajExperia/com.bfl.superapp.onboarding.SplashActivity
https://play.google.com/store/apps/details?id=org.altruist.BajajExperia

Freecharge
com.freecharge.android/com.freecharge.activities.main.MainActivity
https://play.google.com/store/apps/details?id=com.freecharge.android

**Comment by Donnnno** [comment]
Thanks for letting me know, fixed it for the next release!
