### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by ungeskriptet** [Donnnno/Arcticons#154]
[20210515_094539.zip](https://github.com/Donnnno/Arcticons/files/6483883/20210515_094539.zip)

- [Freezer](https://files.freezer.life/0:/)
- [irplus](https://irplus-remote.github.io/)
- [MoeList](https://github.com/axiel7/MoeList)
- [osu!](https://github.com/ppy/osu/)
- [osu!droid](http://ops.dgsrz.com/)
- [Ultrasonic](https://ultrasonic.github.io/)
- [Ungoogled Chromium](https://uc.droidware.info/)

**Comment by ungeskriptet** [comment]
One more app: [20210514_063244.zip](https://github.com/Donnnno/Arcticons/files/6480037/20210514_063244.zip)
- [MoeList](https://github.com/axiel7/MoeList)

**Comment by Donnnno** [comment]
Created 5 new icons & updated two existing icons:

![image](https://user-images.githubusercontent.com/31142286/118359432-af38a380-b583-11eb-8d02-367a2268cf51.png)

Enjoy.
