### ISSUE TITLE
Dix app icon not apply

### ISSUE THREAD

**Issue by dheeraj025** [Donnnno/Arcticons#1552]
Hi 

https://play.google.com/store/apps/details?id=com.hdfcbank.payzapp

Problem- dev of the app discontinued old app and launches new with same name.
Arcticons has an icon for this app , just not auto applying on new version of app.
and i use discreet launcher ,it has no option to manually apply.

Pls fix this.

**Comment by Donnnno** [comment]
Hey, can you provide me the appfilter code? 
You can get it with [icon request](https://github.com/Kaiserdragon2/IconRequest/releases/tag/v2.0.5) or [iconpusher](https://play.google.com/store/apps/details?id=dev.southpaw.iconpusher). 

Thanks

**Comment by dheeraj025** [comment]
PayZapp
com.hdfcbank.payzapp/com.apollorncontainer.activities.SplashActivity
https://play.google.com/store/apps/details?id=com.hdfcbank.payzapp

**Comment by Donnnno** [comment]
Good, I'll update it soon
