### ISSUE TITLE
[Icon update request] Obsidian has a new icon

### ISSUE THREAD

**Issue by NicoWeio** [Donnnno/Arcticons#1568]
See https://obsidian.md/blog/new-obsidian-icon/

**Comment by Donnnno** [comment]
Nice, they have an svg available. Will probably do it tomorrow

**Comment by Donnnno** [comment]
Done!

![image](https://github.com/Donnnno/Arcticons/assets/31142286/72f11013-ce20-4a54-a666-b9453ce92ab3)

**Comment by NicoWeio** [comment]
Thanks!
For future reference: 6110b187fe8f11d86e6d064bbe717be8deaced20
