### ISSUE TITLE
[Feature] Variable Line-Thickness

### ISSUE THREAD

**Issue by Jak2k** [Donnnno/Arcticons#1569]
A method for configuring the line thickness  would be great. You icons are available for the use in web on [iconify](https://icon-sets.iconify.design/arcticons/). I tried to use them, but they were to thin to be clearly visible.

**Comment by Donnnno** [comment]
Reminds me of an April fool's joke I made one time 🙃

But right now that isn't possible, the icons are rendered as static pngs. We're looking at changing them to vectors tho, but have to test compatibility and stuff.

Something like that would maybe be possible then.

For now I'd recommend installing icon pack studio, you can add some line-thickness with that

**Comment by Jak2k** [comment]
> Reminds me of an April fool's joke I made one time 🙃

I know. 😆

> For now I'd recommend installing icon pack studio, you can add some line-thickness with that

Unfortunately, this is not available for the web.

**Comment by Donnnno** [comment]
Oh wait web.

Open it in a vector edit program and change the line width.

**Comment by Donnnno** [comment]
In inkscape you can do it here:

![image](https://github.com/Donnnno/Arcticons/assets/31142286/d5cba469-bb13-4ef0-8779-7bf623a7a0ca)

**Comment by Jak2k** [comment]
Can this be automated or be made client side?

**Comment by Donnnno** [comment]
Definitely, but not by me 😆

**Comment by Donnnno** [comment]
I think something like this is not our focus, because we're making an icon pack. Projects like iconify, icon duck etc. are more likely to do something with these suggestions.
