### ISSUE TITLE
Allow requesting work profile apps

### ISSUE THREAD

**Issue by canac** [Donnnno/Arcticons#1577]
On the icon request page, apps missing icons from my work profile aren't displayed and can't be requested. Would it be possible to change that? Love this project; thanks for all the hard work!

**Comment by Donnnno** [comment]
Hmmm idk if that's possible, have you tried installing Arcticons on your work profile and using the requests?

**Comment by canac** [comment]
Good idea, it does work from within the work profile. The only problem is that I don't want to use my work email to make the request. I'm not an Android developer, but maybe you could use a similar approach to Iconeration when it added support for apps in the work profile: https://codeberg.org/kaanelloed/Iconeration/commit/3cd6de9081212256f52c64bad9b14d2b2da0583f

**Comment by Donnnno** [comment]
Things like that are unfortunately beyond my scope. I focus on design and general direction, but can't code, haha. 

This would also be something for our main dashboard, Candybar: https://github.com/zixpo/candybar/issues

**Comment by canac** [comment]
@Donnnno I didn't realize that the dashboard functionality is provided by candybar. I just opened an issue over there.

**Comment by Donnnno** [comment]
Thanks, feel free to reference this issue tho!
