### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by dragonhunter056** [Donnnno/Arcticons#158]
[20210515_060042.zip](https://github.com/Donnnno/Arcticons/files/6488494/20210515_060042.zip)

**Comment by Donnnno** [comment]
Hi again,
I've created the icons & they will appear in the next update :)
Some icons already existed so I updated those ones.

Here's a preview of the new ones:

![image](https://user-images.githubusercontent.com/31142286/118400004-23e11000-b660-11eb-99e3-9a2bd4f0ac6d.png)
![image](https://user-images.githubusercontent.com/31142286/118400066-57bc3580-b660-11eb-9535-3b88f7d22a07.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
