### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by MonsterSwagger** [Donnnno/Arcticons#159]
[20210516_080056.zip](https://github.com/Donnnno/Arcticons/files/6488980/20210516_080056.zip)

**Comment by Donnnno** [comment]
I've created the icons & they will appear in the next update :)

Here's a preview:

![image](https://user-images.githubusercontent.com/31142286/118397756-e4adc180-b655-11eb-9f8a-436247c252aa.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks :^)
