### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by starbuckbok** [Donnnno/Arcticons#160]
The following four, please!

[20210517_081409.zip](https://github.com/Donnnno/Arcticons/files/6492624/20210517_081409.zip)

**Comment by starbuckbok** [comment]
Let me add one more, if possible: radio paradise - easy enough, and truly beautiful music. Many thanks!
[20210519_044818.zip](https://github.com/Donnnno/Arcticons/files/6510140/20210519_044818.zip)

**Comment by Donnnno** [comment]
Hi, I won't be doing your icons anytime soon. 

This is your third icon request, and that's okay, but I'm not getting anything back from you (not even a reaction) after making the first two, I think that's fairly impolite.

Making icons costs time, some are simple and some are more work. Fun fact, if I charged my hourly wage for this each icon would cost at least five euro (I'm not asking that, but it's something that you should be aware of).

Maybe another contributor will take some time to do it for you, or you can even install Inkscape and do it yourself :^)
