### ISSUE TITLE
Icon for Seven Time not showing

### ISSUE THREAD

**Issue by Cguy7777** [Donnnno/Arcticons#1602]
The icon for Seven Time no longer shows for me. I think it uses a generic number-in-a-square icon, maybe something just needs to be changed in appfilter.xml?

`<!-- Seven Time -->`
`<item component="ComponentInfo{com.codescape.seventime/com.codescape.seventime.MainActivity}" drawable="number_square_7"/>`

Using Nova Launcher 7.0.57 with Arcticons Dark 6.4.4.
Thank you for your work on this gorgeous icon pack!

**Comment by Donnnno** [comment]
Can you use Icon request to send the right appfilter entry here? 

https://github.com/Kaiserdragon2/IconRequest/releases/

**Comment by Cguy7777** [comment]
Sure thing, here's the output:
<appfilter>

	
	<item component="ComponentInfo{com.codescape.seventime/com.codescape.seventime.MainActivity}" drawable="seven_time"/>

</appfilter>

**Comment by wwwwwwari** [comment]
It probably just needs to be renamed `number_7` because it's pointing at `number_square_7` that doesn't exist anymore (got renamed).

@Donnnno if you haven't worked on it already, I can include the fix in my PR.
