### ISSUE TITLE
Assign an existing icon to an application

### ISSUE THREAD

**Issue by jcperil** [Donnnno/Arcticons#1629]
The existing icon is document scanner as shown below.

<p align="center">
<img src="https://github.com/Donnnno/Arcticons/assets/89805719/a2ba3a08-f4d4-47d0-8f49-07ea163bb42a" height="150px">
</p>

Arcticons has only one icon missing from my app drawer and that is PDF Scanner. I had requested an icon some time back. I also tried the Iconeration app but it didn't apply the icon due to some XML file missing.

I really don't mind if it is a different icon. And fortunately, you already have an existing icon similar to PDF scanner. Can you please assign the above icon to PDF scanner as well?

The details for [PDF scanner](https://play.google.com/store/apps/details?id=com.camscanner.documentscanner.pdfscanner.textscanner.photos.scanner) are as follows:

com.camscanner.documentscanner.pdfscanner.textscanner.photos.scanner/com.hazel.cam.scanner.free.activity.splash.SplashActivity

**Comment by Donnnno** [comment]
Sure, no problem!

**Comment by paritosh9199** [comment]
Hey @Donnnno please rename the icon DSB.svg to DBS.svg, same for dsb_digibank to dbs_digibank.svg

Seems like the name is a typo in the latest 7.0.0 release

**Comment by Donnnno** [comment]
Oops!

**Comment by jcperil** [comment]
Thank you Donnnno! An icon has been assigned to PDF Scanner in the latest release. So, this issue has been resolved. Please close this as you see fit.

**Comment by Kaiserdragon2** [comment]
> Hey @Donnnno please rename the icon DSB.svg to DBS.svg, same for dsb_digibank to dbs_digibank.svg
> 
> Seems like the name is a typo in the latest 7.0.0 release 

Fixed in #1663

**Comment by jcperil** [comment]
Hi, can you please assign the existing Obtainium icon to Obtainium (F-Droid build)?


	<item component="ComponentInfo{dev.imranr.obtainium.fdroid/dev.imranr.obtainium.MainActivity}" drawable="obtainium" />

Thank you.
