### ISSUE TITLE
1x1 clock widget

### ISSUE THREAD

**Issue by ojppe** [Donnnno/Arcticons#1644]
Is it possible to make the clock widgets 1x1 size?

**Comment by Donnnno** [comment]
It's probably possible when changing these values here (but for every clock):

https://github.com/Donnnno/Arcticons/blob/main/app/src/main/res/xml-v31/analog_clock_1.xml
https://github.com/Donnnno/Arcticons/blob/main/app/src/main/res/xml/analog_clock_1.xml

Need to test it tho

**Comment by Donnnno** [comment]
added in #1778 by @Kaiserdragon2 !
