### ISSUE TITLE
Appfilter styling issues

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#1649]
What could have happened here?

The styling is really weird now

![image](https://github.com/Donnnno/Arcticons/assets/31142286/576aa0ca-cb08-46df-bd35-61ed62e2e2e7)

maybe it has something to do with the latest modification? https://github.com/Donnnno/Arcticons/pull/1628/files

**Comment by petlyh** [comment]
Looks like the stray character here is messing up the formatting: https://github.com/Donnnno/Arcticons/blob/856e50853dc12d591bfc6ee459577f0186f820e8/other/appfilter.xml#L23

`preparerelease.py` formatted the appfilter like it's supposed to after I removed it.

**Comment by Donnnno** [comment]
ohhhhh oops, thank you !

**Comment by Donnnno** [comment]
ohhhhh oops, thank you !
