### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by coxackie** [Donnnno/Arcticons#166]
Sorry about the two different zips, but they are just two apps: Wavelet and Log Card Reader. Many thanks!

[20210521_085856.zip](https://github.com/Donnnno/Arcticons/files/6521037/20210521_085856.zip)
[20210521_080047.zip](https://github.com/Donnnno/Arcticons/files/6521038/20210521_080047.zip)

**Comment by Donnnno** [comment]
Hi, I won't be doing your icons anytime soon. 

This isn't your first time asking for icons, and that's fine, but without getting anything back from you, it's very unsustainable for me to do.

Making icons costs time, some are simple and some are more work. Fun fact, if I charged my hourly wage for this each icon would cost at least five euro (I'm not asking that, but it's something that you should be aware of).

Maybe another contributor will take some time to do it for you, or you can even install Inkscape and do it yourself :^)

**Comment by coxackie** [comment]
totally understandable - and many thanks for your work up to now. I will try at some point to check inkscape and, more importantly, my skills...

**Comment by Donnnno** [comment]
Thank you! 
Designing icons may be hard first, but it also can be really fun to do ;)

**Comment by Donnnno** [comment]
Because it was a small request, I took a couple of minutes to do it. 

Cheers ;) 

![image](https://user-images.githubusercontent.com/31142286/122573337-f87e8600-d04e-11eb-827c-72140d39c05d.png)
