### ISSUE TITLE
Website has out-of-date information

### ISSUE THREAD

**Issue by ThatOneCalculator** [Donnnno/Arcticons#1664]
It should say "wide range (over 7000!)" instead of "wide range (over 5000!)", and there should be a section for Arcticons You instead of just Dark and Light.

![image](https://github.com/Donnnno/Arcticons/assets/44733677/77ec9057-7752-477e-8581-8edacc8f896b)

**Comment by dgcampbe** [comment]
The readme has also just became outdated (though there are still technically 6k+ icons :P).

**Comment by Donnnno** [comment]
hahah the website also doesn't feature Arcticons You, should update it soon :)

**Comment by Donnnno** [comment]
updated it!
