### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by saromba** [Donnnno/Arcticons#167]
For dict leo and hide.me.
Thx.

[20210521_075901.zip](https://github.com/Donnnno/Arcticons/files/6524371/20210521_075901.zip)

Regards,
saromba

**Comment by Donnnno** [comment]
Hi! Thanks for your request and your donation, 

I created these icons. The Leo was good to do but hide.me is a tricky one, so I went for a stickfigure character.

Let me know what you think ;)

![image](https://user-images.githubusercontent.com/31142286/119185355-fa1c5480-ba76-11eb-82bc-c762102cc2ce.png)

**Comment by saromba** [comment]
Hi,

looks great. Better than the original... :-)


Kind regards,
Sascha

21.05.2021 20:56:37 Donno ***@***.***>:

**Comment by Donnnno** [comment]
Good to know :^)  
I'll add them to the next update!
