### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#168]
Not really an issue but more a place to talk or ask questions :)

**Comment by joelchrono12** [comment]
I think 32 icons in 3 days is pretty decent :D

**Comment by Donnnno** [comment]
@joelchrono12 It sure is! You're doing some great work :^)

**Comment by ObsidianChickenz** [comment]
I've been working on a few icons for the pack but I have a question regarding one in particular for an app called Guilded. On Guilded's website, the icon in SVG format is available to download. It's a simple shape, just a blocky G in the shape of a shield. If I can resize it and convert it to a path in Inkscape, would it work for the pack?

**Comment by Donnnno** [comment]
@ObsidianChickenz that probably should be fine :)

**Comment by ObsidianChickenz** [comment]
Thanks! I'm gonna try to get one or two more icons in, since I only have 5 at the moment, but hopefully I can open a pull request soon.

**Comment by Donnnno** [comment]
@ObsidianChickenz Cool! Let me know if you'll need some feedback, or have any other questions.

**Comment by joelchrono12** [comment]
> Thanks! I'm gonna try to get one or two more icons in, since I only have 5 at the moment, but hopefully I can open a pull request soon.

Lol I opened my pr's with like 2 icons and by the end of the day I had another 5, so its probably fine

**Comment by Donnnno** [comment]
Even PR's with only one icon are fine ofcourse.

**Comment by onyxdhakal** [comment]
I want to learn inkscape. Do you have any free resources that could help me?

**Comment by Donnnno** [comment]
@onyxdhakal I think maybe @joelchrono12 has a good tutorial. I personally use Illustrator for my icons but I recommend using Inkscape indeed.

**Comment by joelchrono12** [comment]
> I want to learn inkscape. Do you have any free resources that could help me?

@onyxdhakal [Logos by Nick](https://www.youtube.com/c/LogosByNick) is a good channel to checkout, I personally got started with almost no help, I was discovering new things as I learned during the whole last week, I got pretty busy since uni is ending, so I wont be able to make more icons until july

Also the [Inkscape for Teachers](https://www.youtube.com/playlist?list=PLHVWhWfdGp61uhDUMPMKewxuxmaaEQIdu) playlist is quite interesting since it has geometric shapes and I learned a thing or two there. 

I like to mess around by myself a lot more, so there might be more resources out there, but this is good to get started with this icon pack simple requirements

**Comment by ObsidianChickenz** [comment]
I opened the pull request I was talking about a few days ago, but I'd like to remove an icon and add a few new ones. Is there any way to do that without deleting the request and opening a new one?

**Comment by joelchrono12** [comment]
> I opened the pull request I was talking about a few days ago, but I'd like to remove an icon and add a few new ones. Is there any way to do that without deleting the request and opening a new one?

Justo keep commiting changes, they will show up automatically un tour pull request

**Comment by ObsidianChickenz** [comment]
Got it, thanks.

**Comment by MonsterSwagger** [comment]
@joelchrono12 Thank you. I will check them out.

**Comment by ObsidianChickenz** [comment]
When contributing, should I edit the appfilter in `app/src/main/res/xml/`, in `app/src/main/assets/`, or both?

**Comment by Donnnno** [comment]
The assets folder is fine.

**Comment by Invisible3ck** [comment]
Hi. How may I compile an apk after making some icons?

**Comment by Donnnno** [comment]
Hi @Invisible3ck, if you want to do it yourself, I suggest using android studio to open the project and exporting it with that.

**Comment by Invisible3ck** [comment]
How may I add the new icons after opening the project and is there anything additional that might need to be since? I'm still very new to all of this, so I apolgize.

**Comment by Donnnno** [comment]
There are a few steps that you'll need to do to make the icons visible in the app.

First you'll need to raster the icons in the /other folder, you can do that with one of the raster.sh files (rasterwhite.sh).
After that, you'll need to update the xml's with xml.sh

And then you can run it in android studio (I use debug mode all the time to push it quickly to my phone).

**Comment by Invisible3ck** [comment]
Do I open both rasterwhite.sh and xml.sh files in a text editor?

How do I run those two files in Android Studio?

**Comment by joelchrono12** [comment]
Those files are bash scripts, you run them on a terminal, but if you use Windows I am not sure of the procedure to do so

**Comment by Donnnno** [comment]
> 
> 
> Do I open both rasterwhite.sh and xml.sh files in a text editor?
> 
> How do I run those two files in Android Studio?

I use git bash to run them on Windows.
One more thing for the raster scripts, you'll need the inkscape commandline stuff installed.

**Comment by dgcampbe** [comment]
I don't know very much about android development, but I was wondering if there is any interest in migrating the app to Kotlin? As far as I know, Java is no longer the preferred language for Android development anymore. At least I hope so, since the only thing I really know about Java is that I despise it and everything it stands for. 😛
I don't know the current state of the Java code, but if it is a rats' nest of spaghetti code in dire need of refactoring, I could start learning Kotlin to help translate the project piece by piece.

**Comment by Donnnno** [comment]
@dgcampbe I don't know very much either, I tried to understand Kotlin & java a few months ago but didn't come very far with it. I know Kotlin is better, but have absolutely no idea how to convert everything properly. Java is fine as it is for an app like this, Kotlin code would be a nice to have. But if you're willing to give it a try, be my guest. :^)

**Comment by dgcampbe** [comment]
Have improvements made to the Frost codebase been merged to this one? I might create a new branch on my personal fork for playing around with Kotlin.

**Comment by Donnnno** [comment]
Frost is actually more out of date at the moment, there are many improvements in Arcticons that aren't in Frost.

**Comment by Aman9das** [comment]
https://github.com/jahirfiquitiva/Blueprint/wiki/Get-Started

Is the solution to all the problems.. lets focus on the designs, they built coded the Blueprint, so that we dont have to :)

@Donnnno What stops you from by following the guide and porting Arcticons.. I couldnt create a new package for some reason

**Comment by Donnnno** [comment]
> @Donnnno What stops you from by following the guide and porting Arcticons.. I couldnt create a new package for some reason

Time. For me it costs too much time to port everything over to blueprint. The frost base is a bit rusty but it works for a simple icon pack. And besides that, I've never seen another blueprint icon pack on F-Droid.

**Comment by dgcampbe** [comment]
I might be interested in putting in the time. Worst case scenario is that it never goes anywhere and I learn a lot about Android development. First step would be to make sure that blueprint would be allowed on f-droid, I suppose. Then the next step might be to figure out it works. I will create a branch on my fork for toying with it.

**Comment by dgcampbe** [comment]
It would appear that Blueprint is licensed under CreativeCommons Attribution-ShareAlike. According to the [f-droid inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/), "All applications in the repository must be Free, Libre and Open Source software". It also links to this [reference](https://www.gnu.org/licenses/license-list.html). CreativeCommons Attribution-ShareAlike, is listed as "should not be used on software" and is "one-way compatible with the GNU GPL version 3: this means you may license your modified versions of CC BY-SA 4.0 materials under GNU GPL version 3, but you may not relicense GPL 3 licensed works under CC BY-SA 4.0." As it would happen, this project is using the GNU GPL version 3. I am no lawyer, but it seems to me that we are allowed to use Blueprint code just fine (though Blueprint probably should become dual-licensed).

**Comment by Donnnno** [comment]
@dgcampbe We have another issue open about Blueprint here: #249 maybe move that conversation to there :^). There's also a comment in there how it should be compatible on F-Droid, still have to test that with something like [F-Droid Build](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/).

If you're willing to put the time in it, that would be really appreciated :) 

Oh, and the multi-licencing thing should be fine, every icon in Arcticons is already CC 4.0

**Comment by Donnnno** [comment]
Closing this one in favor of GitHub Discussions:
https://github.com/Donnnno/Arcticons/discussions
