### ISSUE TITLE
Discord and Vendetta don't get their icons applied

### ISSUE THREAD

**Issue by lou-stro** [Donnnno/Arcticons#1681]
When I updated Vendetta (Stable), the Arcticons icons don't get applied. I then installed Discord and it also happens to it. 
![Screenshot_20230901_182149_Nova7](https://github.com/Donnnno/Arcticons/assets/96671708/379429aa-a464-4b1a-86fe-c1d3f266fb99)

**Comment by Donnnno** [comment]
Discord (& vendetta) updated their app activities, it should be fixed in the upcoming release!

**Comment by lou-stro** [comment]
Ahh I see. Thanks for the info :)
