### ISSUE TITLE
CONTRIBUTING.md out of date

### ISSUE THREAD

**Issue by He-Ro** [Donnnno/Arcticons#1689]
A small correction is needed in the image of the contribution guide. There it is depicted that new icons go into `Arcticons/other/yourname/`:
![CONTRIBITING.md](https://github.com/Donnnno/Arcticons/assets/3579374/98c8371d-d15c-4c27-94e9-e8d45d9316f5)

 But that does not seem to be the correct place anymore. I could not find the SVG file for this image within this repo, so I did not create a Pull Request myself.

**Comment by Donnnno** [comment]
It's not necessary but it makes it easier for me to check the new icons ;)

**Comment by He-Ro** [comment]
Ah, okay. I thought it was a hassle for you, since you had to move the files. Then I'll close this ;)
