### ISSUE TITLE
Headspace icon was removed without replacement of clean version

### ISSUE THREAD

**Issue by vanbeveren** [Donnnno/Arcticons#169]
The headspace icon was removed with a cleanup commit (`7193223db576ad08f4ab41aef5f6cbf7bec248c3`), but not replaced with a clean version.

I hope this is the best place to note this. :)

**Comment by Donnnno** [comment]
Oh oops, it was a circle right?

**Comment by Donnnno** [comment]
Forgot to change that one, but it should be fixed in the next release 1.6.4.
