### ISSUE TITLE
Action Launcher icon not working

### ISSUE THREAD

**Issue by fartboygh** [Donnnno/Arcticons#1696]
It has no icon in the pack, yet it doesn't show up in the "icon request" section of the app. I'm using the dark version, if that matters.

This app: https://play.google.com/store/apps/details?id=com.actionlauncher.playstore

**Comment by wwwwwwari** [comment]
Do you mean the "Action Settings" icon within the launcher not getting applied? If so, I think it's probably a launcher-specific shortcut, not an actual app, so it doesn't show up in the icon request.

**Comment by fartboygh** [comment]
Yes.

**Comment by Donnnno** [comment]
I've contacted the Action Launcher dev a while ago about this, but haven't gotten a response yet.
