### ISSUE TITLE
[You] backgrounds are saturated

### ISSUE THREAD

**Issue by Suburbanno** [Donnnno/Arcticons#1705]
The icon backgrounds are saturated compared to other icon packs or application interfaces that also have the you material

![Screenshot_20230918-195208](https://github.com/Donnnno/Arcticons/assets/13632826/3a6acf05-d489-419a-8dbc-d45063a33607)
![Screenshot_20230918-195236](https://github.com/Donnnno/Arcticons/assets/13632826/ad18e22d-9493-4ec6-8dd8-f946ca05550c)

**Comment by Donnnno** [comment]
Extremely is a bit exaggerated, but I get the point. What do others think of this? We could tune it a bit down.

**Comment by Suburbanno** [comment]
> Extremely is a bit exaggerated, but I get the point. What do others think of this? We could tune it a bit down.

You're right, sorry. Let's wait for other responses.

**Comment by Donnnno** [comment]
Do you have some examples of different icon packs?

**Comment by Suburbanno** [comment]
> Do you have some examples of different icon packs?

![photo_2023-09-19_21-05-59](https://github.com/Donnnno/Arcticons/assets/13632826/99dfc760-dd80-49e4-a68f-425c48818382)
Default tematic icons and lawnicons appear in this style

**Comment by Sounak008** [comment]
I guess since the icon lines are thin and more translucent, the bg matches the icons pretty well keeping the aesthetics intact.

**Comment by ShadowAya** [comment]
Would tune it down imo. My guess is that this is an accent channel as opposed to a neutral one. Most icon packs I've seen are more muted and I prefer it that way.

**Comment by Suburbanno** [comment]
@Donnnno Do you have something in mind for this?

**Comment by Donnnno** [comment]
Haven't made my decision about it yet, it has been a fairly busy month so far.

**Comment by Donnnno** [comment]
I totally forgot that testing this out is just a matter of changing two strings, so I will test it out soon!

**Comment by Donnnno** [comment]
Here's a debug apk to test (you have to unpack it)! 
[Arcticons-v7.3.7-you-debug.zip](https://github.com/Donnnno/Arcticons/files/12860672/Arcticons-v7.3.7-you-debug.zip)

Let me know what you think

![image](https://github.com/Donnnno/Arcticons/assets/31142286/20273dc7-fecf-4fb1-aed0-fafa3ffdc5a0)

**Comment by Suburbanno** [comment]
> Here's a debug apk to test (you have to unpack it)! [Arcticons-v7.3.7-you-debug.zip](https://github.com/Donnnno/Arcticons/files/12860672/Arcticons-v7.3.7-you-debug.zip)
> 
> Let me know what you think
> 

The background color has been changed, but so are the icons, the icon should stay green, no?

**Comment by Donnnno** [comment]
Ohh, like keep the line colors primary?

**Comment by Suburbanno** [comment]
> Ohh, like keep the line colors primary?

yep, just like the icon packs I showed you above

**Comment by Donnnno** [comment]
I'm too colorblind for these small changes

**Comment by TK-NC** [comment]
![Screenshot_20231010_215216_Themed Icons](https://github.com/Donnnno/Arcticons/assets/70816294/477d7154-a45c-41fb-af8c-fe9494e0de63)

Icons should be kind of like this, no? (Themed Icons by Rushikesh Kamewar) atleast on dark theme.

![Screenshot_20231010_215459_Kvaesitso](https://github.com/Donnnno/Arcticons/assets/70816294/206b7419-49da-48b6-9d2d-8d0f1c53a995)

Also here's a screenshot of Kvaesitso with themed icons disabled (it's not an issue with it toggled on).

Thank you for all the work btw :)

**Comment by Donnnno** [comment]
Updated it, should be the same as lawnicons now :-)
