### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by yetanotherfossman** [Donnnno/Arcticons#171]
Me again! Thanks for your great job! This is the second round :)

[20210527_043655.zip](https://github.com/Donnnno/Arcticons/files/6556429/20210527_043655.zip)

**Comment by Donnnno** [comment]
Hi, I won't be doing your icons anytime soon. 

This isn't your first time asking for icons, and that's fine, but without getting anything back from you, it's very unsustainable for me to do.

Making icons costs time, some are simple and some are more work. Fun fact, if I charged my hourly wage for this each icon would cost at least five euro (I'm not asking that, but it's something that you should be aware of).

Maybe another contributor will take some time to do it for you, or you can even install Inkscape and do it yourself :^)

**Comment by yetanotherfossman** [comment]
Oh, yeah I understand that. It's a volunteer job and I shouldn't have abused, sorry. I think I'll wait for now, but I'll start learning about Inkscape too ;)

Thanks for your time and your awesome app!

**Comment by yetanotherfossman** [comment]
Oh, yeah I understand that. It's a volunteer job and I shouldn't have abused, sorry. I think I'll wait for now, but I'll start learning about Inkscape too ;)

Thanks for your time and your awesome app!

**Comment by Donnnno** [comment]
Thanks! It's totally fine ;) 
And I'm super happy that people like you like and use the icon pack!

**Comment by Donnnno** [comment]
The last two missing icons from this request:

![image](https://user-images.githubusercontent.com/31142286/131227595-2c85db7f-661d-4079-8236-507cb5342f61.png)
