### ISSUE TITLE
A utility that allows changing an icon color.

### ISSUE THREAD

**Issue by SpomJ** [Donnnno/Arcticons#1710]
Since an icon is basically single-tone it would be nice if a user could change that tone an an icon (or on all icons). Atleast at the buildtime, please.

**Comment by Donnnno** [comment]
It would be great indeed, but that's something that has to be done on the Launchers side for now. So we can't make that right now. 

I do recommend Icon Pack Studio if you want to modify your icons: https://www.iconpackstudio.com/

https://github.com/Donnnno/Arcticons/issues/403 https://github.com/Donnnno/Arcticons/issues/37

**Comment by SpomJ** [comment]
Well as I understand the only thing you need to do is to substitute every `stroke:#000` to whatever color a user chooses. If this could be done dynamically that would be awesome.

**Comment by Donnnno** [comment]
The thing is, an icon pack can't do that. It's up to the launcher what it does with the icons. 

TinyBit Launcher has the ability to override the colors, from what I know.
