### ISSUE TITLE
Phantom Dot? 

### ISSUE THREAD

**Issue by dgcampbe** [Donnnno/Arcticons#1717]
It seems that somehow the lidraughts icon has a random dot in it that isn't in the svg.
![Screenshot_20231002-154208.png](https://github.com/Donnnno/Arcticons/assets/8411451/6af10b8a-1106-4ada-bd34-c6ab03f8f0e8)

**Comment by Donnnno** [comment]
O:

**Comment by TK-NC** [comment]
.

**Comment by Donnnno** [comment]
thanks @petlyh !
