### ISSUE TITLE
Icon request: Doku

### ISSUE THREAD

**Issue by 3xploiton3** [Donnnno/Arcticons#1740]
*Info*
https://play.google.com/store/apps/details?id=com.dokuwallet.android

---
*Zip file here*
https://play-lh.googleusercontent.com/yHAWkzRY9fsbTWyMqJzojIqz1LHGD7FKvbInWus1E36oujcieWEQCrd8tlp9iO3t647_=w240-h480-rw

**Comment by Donnnno** [comment]
Hi! Icon requests go only through the in app feature nowadays.

**Comment by 3xploiton3** [comment]
> Hi! Icon requests go only through the in app feature nowadays.

ok, maybe should pin message about this
