### ISSUE TITLE
Updated icon: Revolut

### ISSUE THREAD

**Issue by NicoWeio** [Donnnno/Arcticons#1744]
Because I'm not sure how to correctly apply the “badges” for the junior and business versions, I'll take the liberty and just ask if somebody else could update the icons.

Here's the updated logo for reference:
![Revolut_Black](https://github.com/Donnnno/Arcticons/assets/12870528/4700716f-f8d3-4222-8d55-434d97a22e3d)

**Comment by Donnnno** [comment]
already did that in my latest pr!

**Comment by NicoWeio** [comment]
Thank you! I couldn't find it using GitHub's search nor in the PR's title.
