### ISSUE TITLE
Implement an icon request feature like the Turtl app

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#175]
I often get the question if it's possible to build an icon request tool in Arcticons. It should be possible, but not with my knowledge.

Some references:
https://gitlab.com/xphnx/icon-request-tool
https://github.com/jahirfiquitiva/Blueprint

**Comment by Aman9das** [comment]
Implemented thanks to Candycon and @fire-bot!

**Comment by Donnnno** [comment]
Yush!
