### ISSUE TITLE
Shell icon

### ISSUE THREAD

**Issue by onuronsekiz** [Donnnno/Arcticons#1755]
You have renamed my shell_mobile.svg as shell.svg.
It replaced ConnectBot icon with Shell Oil Company's logo.
And who knows what other app's.

appfilter.xml needs to be fixed for this.

**Comment by Donnnno** [comment]
shell more like hell am i rite?

**Comment by Donnnno** [comment]
(gonna check it out)

**Comment by Donnnno** [comment]
Fixed it, thanks for the headsup!
