### ISSUE TITLE
Icon request Macu

### ISSUE THREAD

**Issue by bradman1171** [Donnnno/Arcticons#1757]
*Info*
Hey I was wondering if you could make a "Mountain America Credit Union" themed icon! I understand if you're too busy, but figured id ask. Love your icons!
Thanks!
Brad

https://play.google.com/store/apps/details?id=com.softek.ofxclmobile.macu

---
*Zip file here*

**Comment by Donnnno** [comment]
Hi! We have an icon request function inside the app for this. We're not accepting requests on GitHub anymore!

**Comment by bradman1171** [comment]
My apologies, will do. Thank you!
