### ISSUE TITLE
Arcticons website oddities

### ISSUE THREAD

**Issue by dgcampbe** [Donnnno/Arcticons#1769]
Clicking on the buttons for PayPal, Ko-fi, and Liberapay near the bottom of the main page all open up the GitHub releases instead of their respective sites. Sorry to nitpick, just seemed like unexpected behavior. Also Arcticons You hasn't been updated to display have a Google Play link again. Might be more of a stylistic opinion, but I think the search bar should at least be above the Privacy Policy and License.

**Comment by Donnnno** [comment]
Good points, I mostly overlooked these things, will fix it soon!

**Comment by Donnnno** [comment]
Fixed those points!
