### ISSUE TITLE
Falsely replaced icon / mixup of two unrelated inventory apps

### ISSUE THREAD

**Issue by klaviartur** [Donnnno/Arcticons#1783]
With the latest release the icon (box with smiley face on it) I once contributed for the app "Magic Home Inventory" (net.twisterrob.inventory) was replaced by the icon (part of a microcontroller) for a totally unrelated app "Inventory" (com.codelv.inventory)

Please separate both apps and bring back my icon.

Thx

**Comment by Donnnno** [comment]
That's unfortunate, these things tend to happen when apps have the same name. But don't worry, we'll fix it in the next release. :)

**Comment by klaviartur** [comment]
Thx a lot!

**Comment by Donnnno** [comment]
@TotallyAvailable fixed it, so next release everything should work again!
