### ISSUE TITLE
icons print, dropbox and signal are faulty

### ISSUE THREAD

**Issue by quantenzitrone** [Donnnno/Arcticons#1794]
print.svg has this weird edge
![image](https://github.com/Donnnno/Arcticons/assets/74491719/14e6425f-8328-4320-95b0-911fe35c53ca)

signal.svg has sharp edges except for one
![image](https://github.com/Donnnno/Arcticons/assets/74491719/c03a9d61-51e8-4e6d-87e4-4bfb26dac574)

dropbox.svg has `stroke-linecap:round;stroke-linejoin:round` missing resulting in sharp edges

**Comment by Donnnno** [comment]
The signal icon was probably the only icon that I've allowed to have a sharp edge. The one rounded edge feels like a rendering error, tho.

**Comment by quantenzitrone** [comment]
the thingy the rounded edge is on is a loop
(`stroke-linejoin:round` makes it round)
the loop also results in the stroke being a bit thicker in the middle
