### ISSUE TITLE
Icon-request

### ISSUE THREAD

**Issue by the-loan-wolf** [Donnnno/Arcticons#180]
<item component="ComponentInfo{io.github.domi04151309.batterytool/io.github.domi04151309.batterytool.activities.SplashActivity}" drawable="batterytool"/>

<item component="ComponentInfo{byrne.utilities.converter/byrne.utilities.converter.ConverterActivity}" drawable="bodhaconverter"/>

<item component="ComponentInfo{org.bandev.buddhaquotes/org.bandev.buddhaquotes.Splash}" drawable="buddhaquotes"/>

<item component="ComponentInfo{in.workarounds.define/in.workarounds.define.ui.activity.SplashActivity}" drawable="define"/>

<item component="ComponentInfo{com.degoo.android.lite/com.google.androidbrowserhelper.trusted.LauncherActivity}" drawable="degoolite"/>

<item component="ComponentInfo{hackerlivewallpaper.appseries.com.skynetlabz/hackerlivewallpaper.appseries.com.skynetlabz.SettingsActivity}" drawable="hackermatrixlivewallpaper"/>

<item component="ComponentInfo{com.jzap.memorymap/com.joanzapata.android.memorymap.MemoryMapActivity_}" drawable="memorymap"/>

<item component="ComponentInfo{free.reddit.news/reddit.news.RedditNavigation}" drawable="relay"/>

<item component="ComponentInfo{com.jarsilio.android.waveup/com.jarsilio.android.waveup.MainActivity}" drawable="waveup"/>

**Comment by the-loan-wolf** [comment]
currently my laptop is broken! When it get fixed i will contribute icons for missing apps which i use.

**Comment by Donnnno** [comment]
Hey, right now the request is empty.

**Comment by the-loan-wolf** [comment]
<item component="ComponentInfo{io.github.domi04151309.batterytool/io.github.domi04151309.batterytool.activities.SplashActivity}" drawable="batterytool"/>

<item component="ComponentInfo{byrne.utilities.converter/byrne.utilities.converter.ConverterActivity}" drawable="bodhaconverter"/>

<item component="ComponentInfo{org.bandev.buddhaquotes/org.bandev.buddhaquotes.Splash}" drawable="buddhaquotes"/>

<item component="ComponentInfo{in.workarounds.define/in.workarounds.define.ui.activity.SplashActivity}" drawable="define"/>

<item component="ComponentInfo{com.degoo.android.lite/com.google.androidbrowserhelper.trusted.LauncherActivity}" drawable="degoolite"/>

<item component="ComponentInfo{hackerlivewallpaper.appseries.com.skynetlabz/hackerlivewallpaper.appseries.com.skynetlabz.SettingsActivity}" drawable="hackermatrixlivewallpaper"/>

<item component="ComponentInfo{com.jzap.memorymap/com.joanzapata.android.memorymap.MemoryMapActivity_}" drawable="memorymap"/>

<item component="ComponentInfo{com.emanuelef.remote_capture/com.emanuelef.remote_capture.activities.MainActivity}" drawable="pcapdroid"/>

<item component="ComponentInfo{free.reddit.news/reddit.news.RedditNavigation}" drawable="relay"/>

<item component="ComponentInfo{com.jarsilio.android.waveup/com.jarsilio.android.waveup.MainActivity}" drawable="waveup"/>

**Comment by the-loan-wolf** [comment]
`
<item component="ComponentInfo{io.github.domi04151309.batterytool/io.github.domi04151309.batterytool.activities.SplashActivity}" drawable="batterytool"/>

<item component="ComponentInfo{byrne.utilities.converter/byrne.utilities.converter.ConverterActivity}" drawable="bodhaconverter"/>

<item component="ComponentInfo{org.bandev.buddhaquotes/org.bandev.buddhaquotes.Splash}" drawable="buddhaquotes"/>

<item component="ComponentInfo{in.workarounds.define/in.workarounds.define.ui.activity.SplashActivity}" drawable="define"/>

<item component="ComponentInfo{com.degoo.android.lite/com.google.androidbrowserhelper.trusted.LauncherActivity}" drawable="degoolite"/>

<item component="ComponentInfo{hackerlivewallpaper.appseries.com.skynetlabz/hackerlivewallpaper.appseries.com.skynetlabz.SettingsActivity}" drawable="hackermatrixlivewallpaper"/>

<item component="ComponentInfo{com.jzap.memorymap/com.joanzapata.android.memorymap.MemoryMapActivity_}" drawable="memorymap"/>

<item component="ComponentInfo{com.emanuelef.remote_capture/com.emanuelef.remote_capture.activities.MainActivity}" drawable="pcapdroid"/>

<item component="ComponentInfo{free.reddit.news/reddit.news.RedditNavigation}" drawable="relay"/>

<item component="ComponentInfo{com.jarsilio.android.waveup/com.jarsilio.android.waveup.MainActivity}" drawable="waveup"/>
`

**Comment by the-loan-wolf** [comment]
<item component="ComponentInfo{io.github.domi04151309.batterytool/io.github.domi04151309.batterytool.activities.SplashActivity}" drawable="batterytool"/>

<item component="ComponentInfo{byrne.utilities.converter/byrne.utilities.converter.ConverterActivity}" drawable="bodhaconverter"/>

<item component="ComponentInfo{org.bandev.buddhaquotes/org.bandev.buddhaquotes.Splash}" drawable="buddhaquotes"/>

<item component="ComponentInfo{in.workarounds.define/in.workarounds.define.ui.activity.SplashActivity}" drawable="define"/>

<item component="ComponentInfo{com.degoo.android.lite/com.google.androidbrowserhelper.trusted.LauncherActivity}" drawable="degoolite"/>

<item component="ComponentInfo{hackerlivewallpaper.appseries.com.skynetlabz/hackerlivewallpaper.appseries.com.skynetlabz.SettingsActivity}" drawable="hackermatrixlivewallpaper"/>

<item component="ComponentInfo{com.jzap.memorymap/com.joanzapata.android.memorymap.MemoryMapActivity_}" drawable="memorymap"/>

<item component="ComponentInfo{com.emanuelef.remote_capture/com.emanuelef.remote_capture.activities.MainActivity}" drawable="pcapdroid"/>

<item component="ComponentInfo{free.reddit.news/reddit.news.RedditNavigation}" drawable="relay"/>

<item component="ComponentInfo{com.jarsilio.android.waveup/com.jarsilio.android.waveup.MainActivity}" drawable="waveup"/>

**Comment by the-loan-wolf** [comment]
I am pasting here turtl output, but github is not showing text after commenting!
So here i am pasting app package names:
com.jarsilio.android.waveup
free.reddit.news
com.emanuelef.remote_capture
vom.jzap.memorymap
Hackerlivewallpaper.appseries.com.skynetlabz
in.workarounds.app
com.degoo.android
org.bandev.buddhaquotes
byrne.utilities.converter
io.github.domi0151309.batterytool

**Comment by Donnnno** [comment]
reminder ^

**Comment by the-loan-wolf** [comment]
My laptop is dead, so i can't make icon right now

**Comment by Donnnno** [comment]
reminder
