### ISSUE TITLE
Changelog pops up on each launch

### ISSUE THREAD

**Issue by istudyatuni** [Donnnno/Arcticons#1808]
Probably related #1764

**Comment by Donnnno** [comment]
Yes, I've noticed it too.

**Comment by Donnnno** [comment]
Something to fix in candybar: https://github.com/Donnnno/candybar-foss

**Comment by Donnnno** [comment]
It's mostly the same, GitHub downloads have doubled after my social media posts, tho. Icon request amounts are mostly the same.

**Comment by Donnnno** [comment]
Oh yeah ofcourse, I've noticed haha

**Comment by Donnnno** [comment]
https://github.com/Donnnno/candybar-foss/commit/867ce5e9f0f4ae276095beaa84a32ef914be6436 should be fixed now :)
