### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by onuronsekiz** [Donnnno/Arcticons#1812]
I believe there are some misalignment issues with some characters.
Here is the ones I found issues;
![2023-11-18_06-18](https://github.com/Donnnno/Arcticons/assets/76511536/d93f2bce-338d-4b47-ab40-45652d575714)

Here is an example;
![2023-11-18_06-15](https://github.com/Donnnno/Arcticons/assets/76511536/44821b31-d6af-4d40-b29e-f19cea33363e)

**Comment by Donnnno** [comment]
I think there was a weird rounding error happening with the SVG file.

I've updated the file, can you test it?

**Comment by Donnnno** [comment]
@TotallyAvailable who's gonna read SVGs like that anyways?

**Comment by onuronsekiz** [comment]
It seems the misaligned characters are fixed, kudos.

**Comment by Donnnno** [comment]
great to hear that, probably used a wrong export setting, my bad!
