### ISSUE TITLE
'One app: 3 variants' instead of 3 apps

### ISSUE THREAD

**Issue by Vee-Jay** [Donnnno/Arcticons#1814]
I have all 3 versions of Arcticons installed on my device and need to update all 3. I use Obtainium (an open source apps manager) sourced to this github for the purpose.  Unfortunately the obtainium app does not recognise the 3 version (d/l/y) as 3 but variants. A variant is usually for different cpu architectures like v7a or v8a.. Arcticons as reported by github apks is a SINGLE app having 3 variants namely  d,l,y.. 

I suspect its due to the usage of same signature on all 3 apps.

**Comment by Donnnno** [comment]
Opening an issue in the Obtainium repo would be more effective. We're not responsible here for unofficial sources.
