### ISSUE TITLE
Icon attempt: Calendar Widget by Home Agenda

### ISSUE THREAD

**Issue by coxackie** [Donnnno/Arcticons#183]
Disclaimer: there is no artistic bone in my body. That being said I *attempted* (strong emphasis) to create an svg for Calendar Widget by Home Agenda. You can find it in the zip file, together with the original (info from turtl). Feel free to use it, or to alter it in any way you think it may be better. I am not creating a pull request, as it may be totally lame...

 Many thanks!

[agenda.zip](https://github.com/Donnnno/Arcticons/files/6615569/agenda.zip)

**Comment by joelchrono12** [comment]
I just added it with on my PR (#182), I changed the icon a bit, I dont think we should mess with opacity... and u also had some filled up stuff

**Comment by coxackie** [comment]
@joelchrono12 thanks for this. For my own future reference: (a) is setting opacity bad? I thought it would give the actual feeling of the app, in fact; (2) what is the problem will "filled up" stuff? What is the alternative if you want a white fill?

**Comment by joelchrono12** [comment]
> @joelchrono12 thanks for this. For my own future reference: (a) is setting opacity bad? I thought it would give the actual feeling of the app, in fact; (2) what is the problem will "filled up" stuff? What is the alternative if you want a white fill?

If you want an  icon pack that allows filling and stuff like that, try Frost, its open source too, in fact, this project is a Frost fork, I am not sure about the opacity, up to the dev

**Comment by Donnnno** [comment]
Hi!, try to follow the basic [contribution guide,](https://github.com/Donnnno/Arcticons/blob/main/CONTRIBUTING.md) it’s pretty detailed. Things like fill and opacity changes are a no-go in this icon pack. Only lines and dots (1,5x1,5 px circles) are allowed.

@joelchrono12 Thanks for fixing it :)

**Comment by coxackie** [comment]
@Donnnno  got it - will be more careful in the future.

**Comment by Donnnno** [comment]
No problem, good to see you try :)
