### ISSUE TITLE
App About Page

### ISSUE THREAD

**Issue by xprateek** [Donnnno/Arcticons#1833]
### Need to update [Matrix] Icon! in about page. (Duplicate twitter icon instead of matrix)
![image](https://github.com/Donnnno/Arcticons/assets/47496067/4e650a32-4c32-4382-a93c-8b6a1d2f9de9)

**Comment by Donnnno** [comment]
I noticed it too! Gonna fix soon :)

**Comment by Donnnno** [comment]
Fun fact: it searches for something ending with x. in the domain, didn't think it though while adding it to candybar haha

**Comment by xprateek** [comment]
Here, added matrix Vector Drawable 
https://github.com/Donnnno/candybar/pull/1

---
![image](https://github.com/Donnnno/Arcticons/assets/47496067/4f1e2f88-42b4-4100-a8c2-9f2b2ac6f7f3)

**Comment by Donnnno** [comment]
https://github.com/Donnnno/candybar-foss/commit/5cad8daaa8383d9d5c2d22708651880906c48148 fixed it here.

We have a matrix icon already, but thanks :) 
![image](https://github.com/Donnnno/Arcticons/assets/31142286/3d54924b-e801-493d-87d2-b81f2530c2f3)

**Comment by xprateek** [comment]
great!
