### ISSUE TITLE
Contributing guide out of date

### ISSUE THREAD

**Issue by digitaldirk** [Donnnno/Arcticons#1840]
Hi,

I am trying to make a fix for an icon already in this project, but with the recent changes to the project structure the contributing guide is out of date. I just want to make sure everything is going in the right place without guessing.

For example svgs are no longer in the /other directory.

I asked some questions in the discussions regarding updating an icon: https://github.com/Donnnno/Arcticons/discussions/1839#discussion-5889770

Thank you

**Comment by Donnnno** [comment]
I've just updated the pack. Each time it updates, it clears the icons from /other and exports it to the right places.

So new icons still go into /other, so I can check them easily :)

**Comment by digitaldirk** [comment]
Thanks for the clarification 🙂 @Donnnno
