### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by Gottarocket** [Donnnno/Arcticons#191]

**Comment by Donnnno** [comment]
Quite a huge request: 

- [x] amongus
- [ ] aria2app
- [ ] bisq
- [ ] blockchain
- [ ] canarabankapp
- [ ] crowdcity
- [ ] dharma
- [ ] documents
- [ ] droidfs
- [ ] etchdroid
- [ ] exodus
- [ ] freedcam
- [ ] freedcamvierwer
- [ ] gameturbo
- [ ] incognitowallet
- [ ] metamask
- [ ] music
- [ ] photoprism
- [ ] portscanner
- [ ] safehancerlite
- [ ] samourai
- [ ] tsacdop
- [ ] vigilante

**Comment by Donnnno** [comment]
Some icons already existed, so I updated those.
Here are the new icons, enjoy:

![image](https://user-images.githubusercontent.com/31142286/122388317-0f9a7680-cf70-11eb-9068-86f1078c8ae0.png)
![image](https://user-images.githubusercontent.com/31142286/122388331-145f2a80-cf70-11eb-9b09-5c6e5bd8c7ef.png)
![image](https://user-images.githubusercontent.com/31142286/122388339-16c18480-cf70-11eb-9ee3-b5aad90f9525.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, especially huge requests like this one. Thanks :^)
