### ISSUE TITLE
black outline

### ISSUE THREAD

**Issue by Gottarocket** [Donnnno/Arcticons#192]
Briar has black whiteline which makes it hard to see behind dark background

**Comment by Donnnno** [comment]
I'll check it when I have some time. Everything should be white.

**Comment by Donnnno** [comment]
Can you make a screenshot of your problem? I don't see a problem with the icon.

**Comment by Gottarocket** [comment]
https://0bin.net/paste/9Pof6Mtf#WVc-cY2n8+WHLtxgTqTGHFsOlqATIE8Q06SYSmowGxh

**Comment by Donnnno** [comment]
Are you using MIUI?

**Comment by Gottarocket** [comment]
Yes may be due to forced dark mode but as you see other icons are fine and launcher is shade launcher

**Comment by Donnnno** [comment]
I have the same issue but with icons like binance. MIUI's dark mode is really agressive. I dunno what to do about that. Maybe you can disable it per app

**Comment by Gottarocket** [comment]
Yeah that worked disabled for launcher 
Thanks

**Comment by Donnnno** [comment]
Cool! I should do that too
