### ISSUE TITLE
Vanced microG Settings icon no longer applies automatically

### ISSUE THREAD

**Issue by ObsidianChickenz** [Donnnno/Arcticons#195]
I believe they changed the activity from `org.microg.gms.ui.SettingsActivity` to `org.microg.gms.ui.SettingsActivityLauncher` after checking Turtl.

**Comment by Donnnno** [comment]
Thanks! I'll add it whrn I have some time :)

**Comment by Donnnno** [comment]
It should already work with the latest update, I checked it and that line is already in the appfilter.

**Comment by ObsidianChickenz** [comment]
If latest is 1.6.5, then it still isn't working on my phone (Galaxy J7 Star running Android 9 Pie). Also, after checking appfilter, it has the old activity name, not the new, unless I'm checking in the wrong spot. The new one ends in `SettingsActivityLauncher` while both appfilter files end in `SettingsActivity`.

**Comment by Donnnno** [comment]
can you send the full turtl data?

**Comment by Donnnno** [comment]
This is what I have in the appfilter(s):

![image](https://user-images.githubusercontent.com/31142286/122282115-572aef00-ceeb-11eb-881b-092685ab8e30.png)

**Comment by ObsidianChickenz** [comment]
Oh, I think we weren't on the same page. This is for Vanced MicroG, not normal MicroG.

**Comment by Donnnno** [comment]
Oh sorry I'm blind

**Comment by ObsidianChickenz** [comment]
It's fine, at least we cleared it up.

**Comment by Donnnno** [comment]
fixed it :)

**Comment by ObsidianChickenz** [comment]
Thanks!
