### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by marcdw1289** [Donnnno/Arcticons#196]
WebApps is included in the request. Although it's in Arcticons it uses the same icon as GApps Browser. They used to be similar but WebApps changed its icon awhile back.

[20210617_012729.zip](https://github.com/Donnnno/Arcticons/files/6668677/20210617_012729.zip)

**Comment by Donnnno** [comment]
Some icons already existed, so I updated those.
Here are the new icons, enjoy:

![image](https://user-images.githubusercontent.com/31142286/122402444-c6512380-cf7d-11eb-850c-a7979d261881.png)
![image](https://user-images.githubusercontent.com/31142286/122402664-fbf60c80-cf7d-11eb-9705-c31f77d96029.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, especially huge requests like this one. Thanks :^)
