### ISSUE TITLE
Icon reques

### ISSUE THREAD

**Issue by lisek-cytrusek** [Donnnno/Arcticons#199]
Hello!!
Can I please ask for 2 more icons to be added?? I am so sorry, turtl for some reason still does not export any zip files for me T__T
I made screenshots + copied the text file that turtl would produce. Sorry for trouble, I wish I could do it through a zip file 

HSBC UK item component="ComponentInfo{uk.co.hsbc.hsbcukmobilebanking/uk.co.hsbc.enterprise.hsbcukmobilebanking.MobileXActivity}" drawable="hsbcuk"/
Nest Bank
item component="ComponentInfo{pl.nestbank.nestbank/bank.nest.atos.pl.nestbank.activities.base.SplashScreenActivity_}" drawable="nestbank"/

![hsbc2](https://user-images.githubusercontent.com/28781321/122642621-3fc64e80-d103-11eb-84b2-d0b2fa2e692f.jpeg)

![NB1](https://user-images.githubusercontent.com/28781321/122642624-4228a880-d103-11eb-99aa-2bf74381a8d3.jpeg)

Thank you for your work, I love the aesthetic ♥◡♥

**Comment by Donnnno** [comment]
Hi, Thanks for your donation :)
Turtl doesn't work good with newer android versions, so that's a bit of a pain.

I'll take a look at your icons :)

**Comment by Donnnno** [comment]
Here are the two icons! They'll appear in the next update, which I'm planning to release today! 

![image](https://user-images.githubusercontent.com/31142286/122643097-21b21b80-d10e-11eb-992c-4a58ea4e5b09.png)

**Comment by lisek-cytrusek** [comment]
OMG THANK YOU!!!!!! This was so fast!!!! 
Awaiting the update :D

**Comment by Donnnno** [comment]
Haha, no problem ;) Glad you like them!

My goal is to publish the update tomorrow or monday.
