### ISSUE TITLE
Search for icon?

### ISSUE THREAD

**Issue by heyyzoeyy** [Donnnno/Arcticons#2]
Sometimes an icon isn't available for an app, but it is because the name isn't exactly right e.g. 'dialer' for phone app. It would be easier to change if I could search through the icons, or at least have the names of the icons in the Articons app.
Also, an app might not have an icon, but an existing icon for another app could fit perfectly, so the search feature would also be good for this.

**Comment by Donnnno** [comment]
Hi, I have like almost no knowledge how coding (java) works :s  So for now you'll have search for the icons manually for now.
But I moved some basic icons to the top in the next release: 

![image](https://user-images.githubusercontent.com/31142286/102787711-ccd15a80-43a1-11eb-931a-844b393a1903.png)

**Comment by L0stLink** [comment]
@Donnnno thanks for the icons, I will try to find some time to implement this feature over next weekend.

**Comment by Donnnno** [comment]
@L0stLink damn, something like that would be amazing to have! Thanks :)

**Comment by Donnnno** [comment]
We have a search bar now! 🎉 

![image](https://user-images.githubusercontent.com/31142286/103707207-88070f80-4fae-11eb-9d16-2be3fe1066cf.png)
