### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by jemail99** [Donnnno/Arcticons#202]
More icons I would like to see added to your great pack.

[20210624_024740.zip](https://github.com/Donnnno/Arcticons/files/6709328/20210624_024740.zip)

**Comment by Donnnno** [comment]
Quite a huge request, I'll see what I can do.

**Comment by Donnnno** [comment]
Forkyz, openboard & radiofrance should already work.

**Comment by Donnnno** [comment]
- [ ] 3ctaskmanager
- [ ] anticovid
- [ ] betterbatterystats
- [ ] calibrecompanion
- [ ] cflumen
- [ ] chronus
- [ ] chlocksync
- [ ] colordict
- [ ] defaultdarktheme
- [ ] doctolib
- [ ] exercisetimes
- [ ] franceinfo
- [ ] francetv
- [ ] idfmobilits
- [ ] keyboardswitcher
- [ ] medilog
- [ ] authenticator
- [ ] overridedns
- [ ] seeders
- [ ] simplereboot
- [ ] synccamera
- [ ] torrentssearchsettings
- [ ] youtubedownloader
- [ ] forkyz
- [ ] openboard
- [ ] radiofrance
- [ ] sdmaidpro
- [ ] weather

**Comment by Donnnno** [comment]
Hi, this was a huge request for me to do, and I hope you like these icons. 

I reused older ones for some icons that aren't in this preview.

Note that creating these icons cost a lot of time, so consider donating & starring the project here on GitHub. Thanks!

![image](https://user-images.githubusercontent.com/31142286/123513520-f1c6c300-d68d-11eb-80ae-254ef444fe97.png)
![image](https://user-images.githubusercontent.com/31142286/123513523-f4c1b380-d68d-11eb-8f2e-62d9121f1d5f.png)
![image](https://user-images.githubusercontent.com/31142286/123513504-e07db680-d68d-11eb-98d1-b4d5be0c3804.png)
![image](https://user-images.githubusercontent.com/31142286/123513507-e2e01080-d68d-11eb-99eb-65c6d993800f.png)
![image](https://user-images.githubusercontent.com/31142286/123513508-e4a9d400-d68d-11eb-8f6c-7658a944b452.png)
![image](https://user-images.githubusercontent.com/31142286/123513518-ed9aa580-d68d-11eb-854d-e740c9daaada.png)

Enjoy!

**Comment by jemail99** [comment]
Thank you for your great work.
I notice that the Forkyz icon is not selected automatically for me on Android 10-11. Looking through the icon pack I don't see any icon that looks like the one I submitted. Maybe there are two apps with the same name?
The Forkyz app I use is a crossword puzzle app. I notice there is an icon that looks like a trident or fork is that the icon you mean?

Again, many thanks for your work and I will certainly donate and star.

**Comment by Donnnno** [comment]
1.6.6 will be available on fdroid in the coming days, it was part of the last update :)

**Comment by Donnnno** [comment]
![Screenshot_2021-06-26-16-09-02-717_com.donnnno.arcticons.debug.jpg](https://user-images.githubusercontent.com/31142286/123515748-09f00f80-d699-11eb-8e9c-5bebbf64d03f.jpg)

**Comment by Donnnno** [comment]
Thank you for your donation ❤️ 

Your icons will appear in the next update (not 1.6.6), probably releasing next week!

**Comment by jemail99** [comment]
I'm still having trouble with Forkyz.

It is not present in 1.6.5 downloaded from F-Droid:
![Screenshot_F-Droid](https://user-images.githubusercontent.com/10640260/123545684-906c2600-d759-11eb-86de-b81fa85fe5f2.png)

![Screenshot_Arcticons](https://user-images.githubusercontent.com/10640260/123545686-95c97080-d759-11eb-9adb-46d7ecec73a8.png)

**Comment by Donnnno** [comment]
F-Droid is one version behind because they build all the apps themselves, it can take a while longer for updates to come out. 
F-Droid's current version is 1.6.5, I released 1.6.6 a couple of days ago, that version will be present in the next repo update from F-Droid.

**Comment by jemail99** [comment]
Hi,

Am I correct in thinking that Forkyz is not present in 1.6.5 but is present in 1.6.6?

Thanks again for your help.

**Comment by Donnnno** [comment]
Yes! It should work 1.6.6

Thanks for your support ;)

**Comment by jemail99** [comment]
Hi,

I see 1.6.6 is updated on F-Droid today.
I updated to 1.6.6 but none of the icons I requested are present in the icon pack.
I see Forkyz does show up but none of the others are present eg Simple Reboot etc.

When will these new icons be present?

**Comment by Donnnno** [comment]
Yes, that's true. Good to know F-Droid has updated it.

I'll probably push a new release later this week after I finished a couple of other icons that I want in the pack.

**Comment by jemail99** [comment]
I look forward to seeing the new icons.

**Comment by Donnnno** [comment]
Just published 1.7.0 with your icons in it. You can download it here from GitHub or wait a couple of days for it to appear on F-Droid
