### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by TobiasDev** [Donnnno/Arcticons#205]
Hello! Here are some icons it looks like is the pack is missing.

- Budget My Life
- Microsoft Launcher
- Recorder (default with LineageOS)
- DHL (maybe this one is just broken because they changed some app name?)

[Articons.zip](https://github.com/Donnnno/Arcticons/files/6737821/Articons.zip)

**Comment by Donnnno** [comment]
Hi, 
Recorder & Microsoft Launcher should already work in the latest version.
I've updated the DHL icon and created one new icon for Budget my life:

![image](https://user-images.githubusercontent.com/31142286/123952452-4e83ef80-d9a6-11eb-8636-c2827c314479.png)
