### ISSUE TITLE
Icons are not used even though they exist

### ISSUE THREAD

**Issue by sasukeiscool** [Donnnno/Arcticons#209]
[20210706_085236.zip](https://github.com/Donnnno/Arcticons/files/6769790/20210706_085236.zip)
Changing the splash activity of these apps causes the icons to not be used.

**Comment by Donnnno** [comment]
Yes, the color red probably isn't in the appfilter right now, will fix this later.

**Comment by Donnnno** [comment]
fixed in my latest pr
