### ISSUE TITLE
Life360 icon is not automatically applied

### ISSUE THREAD

**Issue by ObsidianChickenz** [Donnnno/Arcticons#211]
Just a simple issue, and I think I know why. `drawable="life360"` is in the appfilter, but all of the icon files for Life360 are simply titled `life.svg` or `life.png`. My guess is that if the line in the appfilter is edited to say `drawable="life"`, it would work. However, I may be wrong, as my previous contributions have only been icons, not code.

**Comment by Donnnno** [comment]
Hmm, could have been a typo by me ;) Anyways will fix this later

**Comment by Donnnno** [comment]
fixed in my latest pr
