### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by ColaTheWagon** [Donnnno/Arcticons#213]
[20210708_080634.zip](https://github.com/Donnnno/Arcticons/files/6788001/20210708_080634.zip)

**Comment by Donnnno** [comment]
Hi! I've completed your request, some icons already existed, so I've included only the new ones in the image:

![image](https://user-images.githubusercontent.com/31142286/126822852-1a7e5852-6e6c-4a06-af64-d328159112f7.png)

Enjoy!

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)
