### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by ail1020** [Donnnno/Arcticons#218]
Blur
Electrum
Phimp.me
RHVoice
Sound Toggle
WatchCheck

[20210715_045454.zip](https://github.com/Donnnno/Arcticons/files/6826458/20210715_045454.zip)

**Comment by Donnnno** [comment]
Hi, I've managed to create 3 icons from your request. They'll appear in the next update (1.7.1)!

![image](https://user-images.githubusercontent.com/31142286/126081274-ac29a39b-1bc1-4172-8d4d-fbd8d99cc7da.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)

**Comment by Donnnno** [comment]
- [x] Blur
- [x] Electrum
- [ ] Phimp.me
- [x] RHVoice
- [ ] Sound Toggle
- [ ] WatchCheck

**Comment by ail1020** [comment]
Been patiently waiting for f-droid to build the new icons and noticed a couple issues that I could fix (I tried inkscape and  creating vector images is beyond me). I fully intend to donate to this project monetarily as well though. Keep up the good work.

Relevant pull request: https://github.com/Donnnno/Arcticons/pull/223
