### ISSUE TITLE
Icons Request / Icon Missmatch

### ISSUE THREAD

**Issue by LanaKirisame** [Donnnno/Arcticons#220]
I noticed a two missing one :
 - Tan
 - Doctolib
 
And I noticed the Webtoon app had an Line icon.

[20210719_125806.zip](https://github.com/Donnnno/Arcticons/files/6841685/20210719_125806.zip)

Thanks for making such a great icons pack !

**Comment by Donnnno** [comment]
Ah, I see where the problem is with the missmatch, I'll take a look at it when I have some time :)

**Comment by Donnnno** [comment]
Hi, I've compled your request!
Two new icons for Webtoon & Tan, Doctorlib already had an icon, apparently.

![image](https://user-images.githubusercontent.com/31142286/126677368-38bfee1d-2594-447b-b1c6-506ff8352554.png)

Enjoy!

Ps. if you like them and want to support this icon pack, consider leaving a few bucks & star it on GitHub :) It can be very time-consuming to do this, thanks :^)

**Comment by Donnnno** [comment]
Thank you for your donation! <3
