### ISSUE TITLE
Simple calendar icon not working

### ISSUE THREAD

**Issue by ThomasTraineau** [Donnnno/Arcticons#226]
The simple calendar icon is still the normal one, the icon pack isn't applied on it

**Comment by Donnnno** [comment]
What launcher do you use?

**Comment by ThomasTraineau** [comment]
I use open launcher

**Comment by Donnnno** [comment]
Ah, that's not the icon pack's fault but open launcher being old, see: #100

**Comment by ThomasTraineau** [comment]
Alright, tanks !

**Comment by Donnnno** [comment]
I'd recommend using a more updated launcher like nova, shade or omega

**Comment by ThomasTraineau** [comment]
Yea but none of them are available on f-droid (or I at least couldn't find any repo) and open launcher has more features like adding a lot of columns/rows

**Comment by Donnnno** [comment]
Shade & Omega are available from the IzzyOnDroid repo: https://apt.izzysoft.de/fdroid/
