### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by aaronhatesregex** [Donnnno/Arcticons#24]
The present icons seem to fit well so I think the following lines are enough.

    
    <item component="ComponentInfo{com.dimowner.audiorecorder/com.dimowner.audiorecorder.app.main.MainActivity}" drawable="audiorecorder"/>

    
    <item component="ComponentInfo{com.gitlab.mahc9kez.shadowsocks.foss/com.gitlab.mahc9kez.shadowsocks.foss.MainActivity}" drawable="shadowsocksfoss"/>

I'd like to make a PR but have no idea which file I should change to add icon for different variants of an app / apps that can share same icon. For example, there are [Shadowsocks Android](https://github.com/shadowsocks/shadowsocks-android) on GitHub and [Shadowsocks FOSS](https://f-droid.org/en/packages/com.gitlab.mahc9kez.shadowsocks.foss) on F-Droid, but their package names differ. I suppose I should at least add following two lines to `app/src/main/res/xml/appfilter.xml`.

**Comment by Donnnno** [comment]
Ah it's fine, I can add them later today. They can use the same icons as the existing ones.

**Comment by Donnnno** [comment]
I've added the two lines to the app, scheduled for the next release (not 1.2.0 but the one after that).
