### ISSUE TITLE
[icon request] Mapillary

### ISSUE THREAD

**Issue by Suburbanno** [Donnnno/Arcticons#244]
[mapillary.zip](https://github.com/Donnnno/Arcticons/files/6951464/mapillary.zip)

**Comment by Donnnno** [comment]
Mapillary already has an icon too

**Comment by Suburbanno** [comment]
don't appear to me
![Screenshot_20210808-204519_hyperion.png](https://user-images.githubusercontent.com/13632826/128649164-034b7e0f-58b0-411a-9a9d-783dbbdfd0ee.png)

**Comment by Donnnno** [comment]
I've fixed that, the code was outdated.

(I also should redo that libretorrent icon now that I see it)

**Comment by Donnnno** [comment]
The one for mapillary:

![image](https://user-images.githubusercontent.com/31142286/128649372-39e3fd90-d79c-43d7-9ebe-a94b41338912.png)

Already did update the lbretorrent icon but never updated it apereantly :/

![image](https://user-images.githubusercontent.com/31142286/128649376-8d7eacdc-9fb4-450a-86c4-1fb1b0999d52.png)

**Comment by Suburbanno** [comment]
thanks for the mapillary, and about LibreTorrent, I like both haha
