### ISSUE TITLE
[icon request] Organic Maps

### ISSUE THREAD

**Issue by Suburbanno** [Donnnno/Arcticons#245]
[organicmaps.zip](https://github.com/Donnnno/Arcticons/files/6951465/organicmaps.zip)

**Comment by Donnnno** [comment]
Organic maps already has an icon!

**Comment by Donnnno** [comment]
Wanted to make this one instead of the generic maps icon that already existed ;)

![image](https://user-images.githubusercontent.com/31142286/128648911-a0bb9d62-2e85-43a1-9b7e-2727c577da4d.png)

Enjoy
