### ISSUE TITLE
[Suggestion] Blueprint

### ISSUE THREAD

**Issue by Suburbanno** [Donnnno/Arcticons#249]
What do you think about using Blueprint?

https://github.com/jahirfiquitiva/Blueprint

![image](https://user-images.githubusercontent.com/13632826/128649951-9a45f3d9-412c-4719-9454-4aa0378da1a0.png)

**Comment by Donnnno** [comment]
I'm familiar with blueprint and have looked at it in the past. But I don't know if it's compatible with f-droid.

It looks good tho.

**Comment by Suburbanno** [comment]
@Donnnno see, maybe work with f-droid

Anyways, since you are basically disabling all the license checks already, you can disable it completely (it will allow all installs from anywhere) by doing this:

Replace:
```kotlin
   override fun getLicenseChecker(): PiracyChecker? {
        destroyChecker() // Important
        return if (BuildConfig.DEBUG) null
        else super.getLicenseChecker()
    }
```

With:
```kotlin
   override fun getLicenseChecker(): PiracyChecker? {
        destroyChecker() // Important
        return null
    }
```

_Originally posted by @jahirfiquitiva in https://github.com/jahirfiquitiva/Blueprint/issues/107#issuecomment-407525586_

**Comment by Donnnno** [comment]
I'll think about it, maybe when I have some extra time in the future.

Unfortunately, I'm not really a coder but more a designer, figuring out how the current app works was a lot of work for me. 
So figuring out how Blueprint works and converting everything to it may cost a lot of work for me.

**Comment by dgcampbe** [comment]
I will start toying around with learning how to do this. I will admit that I currently don't know much, but it will be a learning experience.

**Comment by Donnnno** [comment]
Many thanks! I hope you learn lots about it while figuring this out :)

**Comment by jahirfiquitiva** [comment]
Our discord is always open for questions 🙌

https://discordapp.com/invite/78h7xgj

**Comment by Suburbanno** [comment]
closing, Candybar was chosen
