### ISSUE TITLE
Icon Request: Backup, Shpock, Taiga

### ISSUE THREAD

**Issue by TobiasDev** [Donnnno/Arcticons#251]
[20210809_070254.zip](https://github.com/Donnnno/Arcticons/files/6954791/20210809_070254.zip)

**Comment by Donnnno** [comment]
Backup should already have an icon

**Comment by Donnnno** [comment]
Your icon request:

Enjoy! 

![image](https://user-images.githubusercontent.com/31142286/128888724-857a5a2e-d1b0-4d58-b927-824ecc32df28.png)
