### ISSUE TITLE
[BUG] Ingress icon does not work, both in dark and light versions

### ISSUE THREAD

**Issue by Suburbanno** [Donnnno/Arcticons#256]
![Screenshot_20210812-002304_hyperion.png](https://user-images.githubusercontent.com/13632826/129133744-9c02d414-f1e6-4204-8f84-24ed3ca8ba59.png)

**Comment by Donnnno** [comment]
I may have forgotten to add that one

**Comment by Donnnno** [comment]
Fixed it for the next update :^)
