### ISSUE TITLE
Icon requests [5]

### ISSUE THREAD

**Issue by Aman9das** [Donnnno/Arcticons#259]
[20210813_070004.zip](https://github.com/Donnnno/Arcticons/files/6982765/20210813_070004.zip)

5 apps

- [x] Vector asset creator
- [x] Acadboost
- [x] blabber.im
- [x] styx browser
- [x] Aniyomi

I've done a couple myself, pull request #258

**Comment by Aman9das** [comment]
Vector asset creator is a very crucial app, it can create icons ON ANDROID, pretty much sufficient to make arcticons icons.
I suggest you add it as an example resource to contribute using like inkscape..

**Comment by Donnnno** [comment]
> 
> 
> Vector asset creator is a very crucial app, it can create icons ON ANDROID, pretty much sufficient to make arcticons icons.
> I suggest you add it as an example resource to contribute using like inkscape..

I'll take a look at it! There are many different programs / apps that you can use for vector graphics. I'm recommending Inkscape on this page because it's open-source and pretty easy to learn, but personally, I'm using Adobe Illustrator because I'm way to attached to that program.

**Comment by Aman9das** [comment]
They are no doubt better programs, but for articons this app [Vector asset creator](https://play.google.com/store/apps/details?id=com.inglesdivino.vectorassetcreator) is quite simple at drawing line art. I'll let my pull request speak for itself.. (all made on android)

**Comment by Donnnno** [comment]
Created this one for vectorassetcreator: 

![image](https://user-images.githubusercontent.com/31142286/130440965-c8f9037f-cda7-4ee5-bee3-c480e0e539e2.png)

:)

**Comment by Donnnno** [comment]
Also updated the README with a couple more vector programs, including vac
