### ISSUE TITLE
What happened with the icon for GeoGebra Graphing Calculator?

### ISSUE THREAD

**Issue by Quantenzitrone** [Donnnno/Arcticons#260]
In the appfilter.xml files in ll. 2282ff is the following:
```
<!-- GeoGebra Graphing Calculator -->
<item component="ComponentInfo{org.geogebra.android/org.geogebra.android.privatelibrary.splashscreen.SplashScreenActivity}" drawable="geogebragraphingcalculator" />
```
The icon for GeoGebra Graphing Calculator doesn't seem to exist in `/icons`.
What happened here?

**Comment by Donnnno** [comment]
Good question! 

I have no idea 🙃 

But I'll check it out later.

**Comment by Donnnno** [comment]
It had the wrong drawable name, it's fixed now!

**Comment by Quantenzitrone** [comment]
Actually geogebra and geogebragraphingcalculator are not the same and also shouldn't have the same icon.
The developer Geogebra publishes 7 apps on the playstore. 5 different mathematical tools and two apps that combine all of them. GeoGebra Classic is the old version and hasn't received updated since 2018 and GeoGebra Calculator Suite is the new version. Geogebra classic and Calculator Suite have kinda the same icon. While all the others (Graphing Calculator, Geometry, 3D Calculator, CAS Calculator and Scientific Calculator) have unique icons.

**Comment by Donnnno** [comment]
Pffff, a lot of different calculators. I only could find the normal one in the icon database, so feel free to draw them ;)
