### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by stinglama** [Donnnno/Arcticons#264]
Hi, can you please make icons for the following apps.

- Blackhole
- Join
- Naptime
- SAI
- Truecaller

[IconRequest.zip](https://github.com/Donnnno/Arcticons/files/7008269/IconRequest.zip)

**Comment by Donnnno** [comment]
- [ ]     Blackhole
- [ ]     Join
- [x]     Naptime
- [x]     SAI
- [x]     Truecaller

**Comment by Donnnno** [comment]
Join & Blackhole!

![image](https://user-images.githubusercontent.com/31142286/130428466-2feb5450-5f6a-4292-a170-1014408e0721.png)
