### ISSUE TITLE
DigiD Icon not working anymore

### ISSUE THREAD

**Issue by Gd4pL4E** [Donnnno/Arcticons#267]
The DigiD icon exists and I can see it in the Arcticons app itself, but the icon is not applied to the app.

My best guess but would be that the activity "name" has changed:

In the current version of Arcticons:
`
<item component="ComponentInfo{nl.rijksoverheid.digid.pub/crc64c53741d03f31ca6c.MainActivity}" drawable="digid" />`

Checked today with Turtl:
`
<item component="ComponentInfo{nl.rijksoverheid.digid.pub/crc648bce9322c5bd67f6.MainActivity}" drawable="digid"/>
`

Thanks for your continuous work on this icon pack! :)

**Comment by Donnnno** [comment]
Thanks! I've fixed it :^)
