### ISSUE TITLE
Widgets?

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#273]
Another nice to have feature are widgets with the arcticons style.

**Comment by Aman9das** [comment]
I've added a digital clock to my fork, but dont merge, because i obviously dont have the font ttf

**Comment by Donnnno** [comment]
And there's this one already in the candybar version 

![Screenshot_20210913-001833_Nova7.png](https://user-images.githubusercontent.com/31142286/133041470-7832b53e-a311-4075-8f07-139eee8240a2.png)

**Comment by Donnnno** [comment]
I'm considering removing the dash from the zero, or make it an alternative glyph. That probably will look much cleaner with the digital clock.

**Comment by Aman9das** [comment]
Yes add to the svg, but rn the widget uses the font of the app..
