### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by morialo** [Donnnno/Arcticons#276]
Thanks a lot for the minimalist icons, I've been looking around for a FOSS icon pack, I found what Im looking for, there are 4 icons in the zip extracted with "App Manager", I hope that would suffice, thanks again.
[Requested-icons.zip](https://github.com/Donnnno/Arcticons/files/7065473/Requested-icons.zip)

**Comment by Donnnno** [comment]
![image](https://user-images.githubusercontent.com/31142286/132067758-3235e032-f6c4-4cea-a663-69ff9e4d3cb3.png)
 and the last one!
