### ISSUE TITLE
Icon Request for Auxio

### ISSUE THREAD

**Issue by graphonymous** [Donnnno/Arcticons#281]
I would like to have an icon for Auxio. Here the F-Droid link: https://f-droid.org/en/packages/org.oxycblt.auxio/
Thanks :)

**Comment by Donnnno** [comment]
Done! And scheduled for the next version (after 2.0.5):

![image](https://user-images.githubusercontent.com/31142286/131226867-32241d4e-41f1-42fb-8a6a-93d1329179fb.png)

Enjoy!

**Comment by graphonymous** [comment]
Thanks!
