### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by cbeauhilton** [Donnnno/Arcticons#283]
Love this pack. 

A few suggested additions:
- pulse sms
- mint finance
- mobilepass+ authenticator
- renpho
- uptodate medical reference

Will upload turtl soon.

Thanks for all the great work!

**Comment by cbeauhilton** [comment]
[20210829_075836.zip](https://github.com/Donnnno/Arcticons/files/7072530/20210829_075836.zip)

**Comment by Donnnno** [comment]
Hi, I've completed your request, it will be available in the next update :^) 

Here's a preview:

![image](https://user-images.githubusercontent.com/31142286/131555355-4004f9fd-6d58-4562-ba1e-7a5c27736336.png)

Ps. if you like the icon-pack, consider donating a few bucks. Maintaining this pack and making specific icons for people can take a lot of time. Thanks! :^)

**Comment by cbeauhilton** [comment]
These are fantastic, thank you, threw a few bucks your way

 (I'm putting this comment here to hopefully exert some positive peer pressure on anyone who may see it who hasn't donated yet!)

**Comment by Donnnno** [comment]
Haha thank you! Glad you like them :^)
