### ISSUE TITLE
What's more important: Simplicity or staying true to the original icon?

### ISSUE THREAD

**Issue by Quantenzitrone** [Donnnno/Arcticons#284]
The original icon:
![unicodepad original](https://user-images.githubusercontent.com/74491719/131264880-391b60ab-be14-4271-873f-0898b325b87f.png)

My drawn ones:
![unicodepad](https://user-images.githubusercontent.com/74491719/131264876-243157fa-9403-4ea0-905a-707b740c0300.png)
![unicodepad1](https://user-images.githubusercontent.com/74491719/131264877-5c37363b-bf61-4714-bd7e-80cd6059814a.png)
I do like the simplicity of the first one, but if you understand that the text is the waving emoji 🙋 encoded in Unicode, it makes sense to include it.

**Comment by Donnnno** [comment]
The first one!
I think characters like that are unnecessary for a minimalistic icon pack

Also, maybe connect these parts to the body instead of making it loose?
![image](https://user-images.githubusercontent.com/31142286/131265167-4a37beb9-d0a0-487d-b1f3-318808969870.png)

**Comment by Quantenzitrone** [comment]
ok thanks
