### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by murtezayesil** [Donnnno/Arcticons#286]
Turtl - FOSS alternative to Evernote
edX - online learning platform
Stitchcraft - screenshot stitching app

**Comment by murtezayesil** [comment]
[20210829_075836.zip](https://github.com/Donnnno/Arcticons/files/7083569/20210829_075836.zip)

**Comment by Donnnno** [comment]
Your zip doesn't match with the icons that  you describe

**Comment by Donnnno** [comment]
reminder

**Comment by murtezayesil** [comment]
I just used Turtle to create the zip and uploaded it. Didn't even check what was in their. Those icons are foreign to me as well. I never used such apps and have no slughtest of the idea where they came from.
You may close this issue and don't worry about this icons. If I make new request, it will be using Arcticons app.

**Comment by Donnnno** [comment]
Okey
