### ISSUE TITLE
[Documentation] Building instructions

### ISSUE THREAD

**Issue by chopin2712** [Donnnno/Arcticons#287]
Hello! 

Your contributing guide is awesome, but I would like to know if it would be possible to add information to build the project. I am a newbie in Android and gradle stuff, so I have no idea on how it works :sweat_smile:  

I would like to know the process for 2 reasons: first, I am curious and second, some already existing icons could very well suit my needs so I guess it would be easier and faster to just reuse those (for personal need, of course). 

Thanks in advance!

**Comment by Donnnno** [comment]
Hi!

Hmm, I could take a look at a building guide, I figured it out some way too without any knowledge of Android Studio before that. I'll probably write my steps down when I have some time for that.

Btw. if you want to use the icons, you can find them in the /icons folder as SVG (you don't need to use android studio for that).

**Comment by Donnnno** [comment]
Building:

To update and build the app yourself, you'll need to do the following things:

1. Place the created icons in the `/other` folder and add the new lines of code generated with the turtl app to `appfilter.xml` in `/assets`
2. Use the raster script with something like _git bash_: `sh rasterdark.sh` or `sh rasterlight.sh` depending on what color you want.
3. When the rastering is finished you can generate the XML files in git bash: `sh xml.sh`, that creates two files: `iconpack.xml` in `/res/values` & `drawable.xml ` in `/assets`
4. Copy both files from the `/assets` folder to `/res/xml`
5. Change the version code and version name in the `build.gradle` file.
6. Open Android studio, plug your phone in (allow usb debugging), choose your build flavor and click the green play button to run it on your phone.

I think those are the steps I take to build the project.

**Comment by Donnnno** [comment]
This quick documentation is already outdated because we kinda changed all the code, but it's easier now!

**Comment by Donnnno** [comment]
Building:

1. Place the created icons in the `/other` folder and add the new lines of code in the appfilter.xml, you can gather it with [icon request](https://github.com/Kaiserdragon2/IconRequest/releases/).
2. Run the `raster.sh` script and wait until it's done.
3. Change the version code and version name in the app's `build.gradle` file.
4. Open Android studio, plug your phone in (allow USB debugging), choose your build flavor and click the green play button to run it on your phone.
5. You can also generate an APK file in Android studio, more on that [here](https://developer.android.com/studio/run/)

**Comment by Donnnno** [comment]
This is my process, minus changing all the changelogs and stuff. This is the minimum you have to do to build the app!

**Comment by EdwinRodger** [comment]
Thanks!

**Comment by Donnnno** [comment]
Added the guide here https://github.com/Donnnno/Arcticons/blob/main/Building.md
