### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by chopin2712** [Donnnno/Arcticons#288]
TEC - A Belgian bus transportation app
SNCB and SNCB New - Belgian train transportation apps

[20210831_043029.zip](https://github.com/Donnnno/Arcticons/files/7084728/20210831_043029.zip)

**Comment by Donnnno** [comment]
Ah, the inferior Belgium train logo. I always see it on the intercity direct train in the Netherlands next to the superior NS logo :^)

**Comment by Donnnno** [comment]
Anyways, the icons! They will appear in the next update, enjoy!

Here's a preview:

![image](https://user-images.githubusercontent.com/31142286/131556547-b4c2277d-3a76-481d-9e7a-080f0a049f51.png)


Ps. if you like the icon-pack, consider donating a few bucks. Maintaining this pack and making specific icons for people can take a lot of time. Thanks! :^)

**Comment by chopin2712** [comment]
That's very nice!

**Comment by chopin2712** [comment]
Shall I close this issue?

**Comment by Donnnno** [comment]
Thanks!

Nah, I'll close it, still have to merge it otherwise I might forget it.
