### ISSUE TITLE
Support link in the app not working

### ISSUE THREAD

**Issue by antenore** [Donnnno/Arcticons#289]
When I click on the hearth support link, nothing happens.

It seems it tries to start an external app, like PayPal or Firefox, but it closes too fast to see it

**Comment by Donnnno** [comment]
Hmm, I noticed that too! It links to a paypal.me domain, and tries to open the paypal app, but something's not working correctly there :S

**Comment by antenore** [comment]
It's the same from the GitHub link, so it's a PayPal issue.

I'll use liberapay for the good

**Comment by Donnnno** [comment]
Strange paypal issue, on web it works fine for me.
Anyways thanks for your support!

**Comment by antenore** [comment]
You deserve it! I'm a maintainer as well and I know how much is important.

**Comment by Donnnno** [comment]
I changed some things in the support part, there's also a liberapay option now. As for paypal I have no idea what's wrong, it just tries to open a link and I guess that there's a bug within paypal or something.

**Comment by antenore** [comment]
> I changed some things in the support part, there's also a liberapay option now. As for paypal I have no idea what's wrong, it just tries to open a link and I guess that there's a bug within paypal or something.

Awesome!

I've reported the issue to PayPal

**Comment by Donnnno** [comment]
Oh thanks!
