### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by avtkal** [Donnnno/Arcticons#29]
I read that I need to send a .zip file, but Turtl does not create the file, it just lets me copy and paste the following. Let me know if I should do anything else.

Edit: OK, I think I know what I was doing wrong. Sorry for that.
```
<!-- Aplikazioak -->
<item component="ComponentInfo{foundation.e.apps/foundation.e.apps.MainActivity}" drawable="aplikazioak"/>
<!-- BetterUntis -->
<item component="ComponentInfo{com.sapuseven.untis/com.sapuseven.untis.activities.MainActivity}" drawable="betteruntis"/>
<!-- Browser -->
<item component="ComponentInfo{foundation.e.browser/com.google.android.apps.chrome.Main}" drawable="browser"/>
<!-- Laboral Kutxa -->
<item component="ComponentInfo{com.tecnocom.cajalaboral/com.tecnocom.cajalaboral.MainActivity}" drawable="laboralkutxa"/>
<!-- Mezuak -->
<item component="ComponentInfo{foundation.e.message/com.moez.QKSMS.feature.main.MainActivity}" drawable="mezuak"/>
<!-- NewPipe Legacy -->
<item component="ComponentInfo{org.schabi.newpipelegacy/org.schabi.newpipelegacy.MainActivity}" drawable="newpipelegacy"/>
<!-- Oharrak -->
<item component="ComponentInfo{foundation.e.notes/foundation.e.notes.android.activity.SplashscreenActivity}" drawable="oharrak"/>
```

**Comment by elchiquics** [comment]
Try to tap the first option in the Turtl app, you'll be able to copy the needed information from your apps, create an issue titled "Icon Request" and paste the info from the Turtl app

**Comment by Donnnno** [comment]
Oh, and be sure to give turtl storage permission.

**Comment by avtkal** [comment]
Permission to Turtl is granted. I sent what I copied from Turtl in the first comment, but it does not appear. I pasted it in this comment too, but it does not even appear in the preview of the message. Am I doing something wrong? 😅

![Screenshot_20210111-130809_1](https://user-images.githubusercontent.com/63205014/104180879-24497000-540e-11eb-807c-2ce8294bc269.png)


<item component="ComponentInfo{foundation.e.apps/foundation.e.apps.MainActivity}" drawable="aplikazioak"/>

<item component="ComponentInfo{com.sapuseven.untis/com.sapuseven.untis.activities.MainActivity}" drawable="betteruntis"/>

<item component="ComponentInfo{foundation.e.browser/com.google.android.apps.chrome.Main}" drawable="browser"/>

<item component="ComponentInfo{com.tecnocom.cajalaboral/com.tecnocom.cajalaboral.MainActivity}" drawable="laboralkutxa"/>

<item component="ComponentInfo{foundation.e.message/com.moez.QKSMS.feature.main.MainActivity}" drawable="mezuak"/>

<item component="ComponentInfo{org.schabi.newpipelegacy/org.schabi.newpipelegacy.MainActivity}" drawable="newpipelegacy"/>

<item component="ComponentInfo{foundation.e.notes/foundation.e.notes.android.activity.SplashscreenActivity}" drawable="oharrak"/>

**Comment by avtkal** [comment]
> Try to tap the first option in the Turtl app, you'll be able to copy the needed information from your apps, create an issue titled "Icon Request" and paste the info from the Turtl app

Done! I have edited the request.

**Comment by Donnnno** [comment]
Hi can you give us the icons from the apps too? (If turtl doesn't work, try screenshotting them).

**Comment by avtkal** [comment]
> Hi can you give us the icons from the apps too? (If turtl doesn't work, try screenshotting them).

Here, in order:

![aplikazioak](https://user-images.githubusercontent.com/63205014/104190777-e273f600-541c-11eb-8bcd-c14a0d9fa401.png)
![betteruntis](https://user-images.githubusercontent.com/63205014/104190782-e6a01380-541c-11eb-998b-80a47e98b2af.png)
![browser](https://user-images.githubusercontent.com/63205014/104190790-e9026d80-541c-11eb-84ed-87412dca7797.png)
![laboral kutxa](https://user-images.githubusercontent.com/63205014/104190798-ebfd5e00-541c-11eb-934e-a2e13170854b.png)
![mezuak](https://user-images.githubusercontent.com/63205014/104190806-eef84e80-541c-11eb-84e3-6a8094573213.png)
![new pipe legacy](https://user-images.githubusercontent.com/63205014/104190823-f3246c00-541c-11eb-825a-7a07761dec95.png)
![oharrak](https://user-images.githubusercontent.com/63205014/104190838-f7508980-541c-11eb-89e5-6fe58331891a.png)

**Comment by Donnnno** [comment]
Do you know the english names of the apps? Some are translated here.
(I already have an icon for e.apps)

**Comment by avtkal** [comment]
> Do you know the english names of the apps? Some are translated here.
> (I already have an icon for e.apps)

Yes!
Aplikazioak = Apps
Mezuak = Message
Oharrak = Notes

**Comment by Donnnno** [comment]
- [x] Aplikazioak 
- [x] BetterUntis 
- [x] Browser 
- [x] Laboral Kutxa
- [x] Mezuak 
- [x] NewPipe Legacy
- [x] Oharrak
