### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by James-White-93** [Donnnno/Arcticons#290]
Private Internet Access VPN
BBC News
Virgin Money
First Bus
Tesco Mobile
Light Meter

I know the Tesco Mobile one is a bit odd, so if you ever get round to doing it, you can always just use the logo, or just use the actual text instead. The others should be fairly straightforward. Thanks so much for your work, really appreciate it.
[20210901_122916.zip](https://github.com/Donnnno/Arcticons/files/7090738/20210901_122916.zip)

**Comment by Donnnno** [comment]
- [ ] Private Internet Access VPN
- [x] BBC News
- [ ] Virgin Money
- [x] First Bus
- [ ] Tesco Mobile
- [ ] Light Meter

**Comment by Donnnno** [comment]
Just completed your request, here's a preview of the icons, enjoy:

![image](https://user-images.githubusercontent.com/31142286/132098365-ddb311f8-26bd-4227-9124-8871ef1df7ec.png)
![image](https://user-images.githubusercontent.com/31142286/132098366-d269e9b7-e8ec-4101-b1c1-c89cdf3b3305.png)
![image](https://user-images.githubusercontent.com/31142286/132098369-c00b3ba5-f79d-4246-9304-b6f6e98be5cf.png)
![image](https://user-images.githubusercontent.com/31142286/132098371-da5f9bd4-c044-41ca-a34e-a0c7bff2ba0e.png)

Ps. if you like the icon-pack, consider donating a few bucks. Maintaining this pack and making specific icons for people can take a lot of time. Thanks! :^)
