### ISSUE TITLE
Icon Request: Gotify, News, and Paperless

### ISSUE THREAD

**Issue by hjr265** [Donnnno/Arcticons#291]
Icons for these three apps would be greatly appreciated.

```
<!-- Gotify -->
<item component="ComponentInfo{com.github.gotify/com.github.gotify.init.InitializationActivity}" drawable="gotify"/>
<!-- News -->
<item component="ComponentInfo{co.appreactor.news/common.AppActivity}" drawable="news"/>
<!-- Paperless -->
<item component="ComponentInfo{eu.bauerj.paperless_app/eu.bauerj.paperless_app.MainActivity}" drawable="paperless"/>
```

![image](https://user-images.githubusercontent.com/348107/131687574-6c0f81f8-d134-440a-8396-9b2a6f0a015e.png)

**Comment by hjr265** [comment]
The big dot on the top right corner of the News app icon is obviously a notification dot, not a part of the icon.

**Comment by Donnnno** [comment]
Two new icons by @Aman9das and one updated entry for news

![image](https://user-images.githubusercontent.com/31142286/132068787-12086138-cc3b-4846-bf5f-08fae5f4e08c.png)
