### ISSUE TITLE
Arcticons for linux

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#292]
Making the icon pack compatible with linux.

Need help with this one.

**Comment by Aman9das** [comment]
https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

https://www.linux.org/threads/creating-icon-themes.11826/

There is need to make an entire new repository for the project it seems, but great idea..
Just creating an empty repo would be good start for now...

**Comment by Donnnno** [comment]
@Aman9das thanks! That's a good start indeed. I'll take a look at the documentations

**Comment by Donnnno** [comment]
The first step has been made for this: https://github.com/Donnnno/Arcticons-Linux :^)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Many of the issues that are within this repository affect http://github.com/Donnnno/Arcticons-Linux and http://github.com/Donnnno/Arcticons identically. If this repository were hosted by were GitLab, or issues were tracked externally by Bugzilla, the separation would not be problematic, but those are not currently utilized.

Consequently, I suggest that the repositories be combined if possible, even if they are moved into subdirectories of this repository.

**Comment by Donnnno** [comment]
Uhhhh, which issues do you mean?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@Donnnno, http://github.com/Donnnno/Arcticons/issues/395
