### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by bubbec** [Donnnno/Arcticons#294]
Android version
Bitmask
ClipboardCleaner
Developer Widget
LibreTranslater
LiveBoot
Open SSTP Client
PCAPdroid
Pixel Wheels
Privacy Indicators
VPN Hotspot
[IconRequest.zip](https://github.com/Donnnno/Arcticons/files/7100819/IconRequest.zip)

**Comment by bubbec** [comment]
And also another application with a simple icon.

[20210903.zip](https://github.com/Donnnno/Arcticons/files/7107013/20210903.zip)

**Comment by Donnnno** [comment]
- [ ] Android version
- [ ] Bitmask
- [ ] ClipboardCleaner
- [ ] Developer Widget
- [ ] LibreTranslater
- [ ] LiveBoot
- [ ] Open SSTP Client
- [ ] PCAPdroid
- [ ] Pixel Wheels
- [ ] Privacy Indicators
- [ ] VPN Hotspot
- [ ] irremote

**Comment by Donnnno** [comment]
Just completed your request, here's a preview of the icons (some icons already existed so updated those entries), enjoy:

![image](https://user-images.githubusercontent.com/31142286/132097466-b3e2916e-4f4c-49ce-b7a2-d6380fa7bed8.png)
![image](https://user-images.githubusercontent.com/31142286/132097471-f9bb8205-7e91-4959-ab57-80bfcab9c732.png)

Ps. if you like the icon-pack, consider donating a few bucks. Maintaining this pack and making specific icons for people can take a lot of time. Thanks! :^)
