### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by dgcampbe** [Donnnno/Arcticons#295]
I picked some apps that I think are rather popular (including Google Pay and Google TV) for consideration for icons. I am interested in trying my hand at learning to create vector icons to help out, too. I can't guarantee the quality, though. 😛
[20210901_080523.zip](https://github.com/Donnnno/Arcticons/files/7101295/20210901_080523.zip)

**Comment by Donnnno** [comment]
Hi! I've created the icons (gpay already has one, I updated that one).

![image](https://user-images.githubusercontent.com/31142286/132072227-cf061dbf-e565-405e-850c-da4b5befc078.png)

(maybe the Discover icon is a bit too minimalistic)

Enjoy!

**Comment by dgcampbe** [comment]
Thanks. Awesome work on all the detail for the Terraria icon.
