### ISSUE TITLE
Icon Request: Neato, Corona and some more

### ISSUE THREAD

**Issue by TobiasDev** [Donnnno/Arcticons#3]
[20201224_064131.zip](https://github.com/Donnnno/Arcticons/files/5738294/20201224_064131.zip)

Hello, I already love the work you've done for Frost but man these lines icons looks good!

Here are some apps I would love see themed.

- [ ] Neato (Robot vacuum cleaner)
- [x] MS Launcher
- [x] Money Wallet
- [x] Corona Warn app
- [x] StadtMobil
- [x] DHL
- [x] Florisboard

Thanks for the amazing icons! 

Also, Merry Christmas!

**Comment by Donnnno** [comment]
Thanks!
Created icons for your two issues,  The only icon I didn't create is the Neato icon because it's a complicated icon.

![image](https://user-images.githubusercontent.com/31142286/103170944-88820680-4848-11eb-8767-d69eba3aee27.png)
