### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by elchiquics** [Donnnno/Arcticons#30]
Hello!
There are some apps that don't have icon all of them are open source except for popcorntime. Thanks for you atention!

```
<!-- Nova Video --> 
<item component="ComponentInfo{org.courville.nova/org.courville.nova.browser.BrowserActivityVideo}" drawable="novavideo"/>
<!-- Popcorn Time --> 
<item component="ComponentInfo{dp.ws.popcorntime/se.popcorn_time.mobile.ui.MainActivity}" drawable="popcorntime"/> 
<!-- Showly 2.0 --> 
<item component="ComponentInfo{com.michaldrabik.showly2/com.michaldrabik.showly2.ui.main.MainActivity}" drawable="showly2.0"/>
```
[icons.zip](https://github.com/Donnnno/Arcticons/files/5797064/icons.zip)

**Comment by Donnnno** [comment]
Hi can you give us the icons from the apps too? (If turtl doesn't work, try screenshotting them).
(download navi is already in there, so I updated that one)

**Comment by elchiquics** [comment]
Now I've updated the request attaching the .zip from Turtl.

**Comment by Donnnno** [comment]
Created the icons, they should appear in the next update.
