### ISSUE TITLE
Accidental new branch?

### ISSUE THREAD

**Issue by dgcampbe** [Donnnno/Arcticons#303]
Huh. For some reason when my last pull request was merged, it looks like git decided we wanted a new branch for some reason.

**Comment by Donnnno** [comment]
Yea, it gets created when I merge and  edit your pr, sometimes I forget to delete those.

It should be gone now :)

**Comment by dgcampbe** [comment]
Ok, just wanted to make git didn't decide to rise up against up us. For a second there I was wondering if I did something with my pull request to cause that. :P

**Comment by Donnnno** [comment]
Haha, no worries, :^) There's a bigger chance of that happening when their autopilot thing launches tho...
