### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Suburbanno** [Donnnno/Arcticons#306]
- [ ] Rave
- [x] Shopee
- [ ] Apk Editor
- [x] Apk Repacker
- [x] App Tester
- [x] Albatross
- [x] AR
- [x] Aurora Store
- [x] Doodle
- [ ] GPSvc
- [ ] Gravador de Voz
- [ ] Transformers - Heavy Metal
- [x] iti Itaú
- [x] C6
- [x] Inmage
- [ ] Kit do SIM
- [x] LewdFI
- [ ] Meu Alelo
- [ ] Minha Oi
- [x] MX Player
- [x] QTranslate
- [x] Clubhouse
- [x] Scrobb
- [x] Songtube
[20210905_123217.zip](https://github.com/Donnnno/Arcticons/files/7110865/20210905_123217.zip)

**Comment by Donnnno** [comment]
Another huge request :/

**Comment by Donnnno** [comment]
created some of them too:

![image](https://user-images.githubusercontent.com/31142286/132956748-e74184dd-5b42-413a-a6c6-721672d1cbdb.png)
