### ISSUE TITLE
Umm.. I successfully built the app in CandyBar!

### ISSUE THREAD

**Issue by Aman9das** [Donnnno/Arcticons#313]
Here's the apk.. https://drive.google.com/file/d/1hDGUVGAXLP66RMgWGCciHDAVYEbeNBt_/view?usp=sharing
but how do i share the code, make a repo myself?

**Comment by Suburbanno** [comment]
Ok, I just tested it and it's working perfectly, please consider @Donnnno 
thanks @Aman9das!!

**Comment by dgcampbe** [comment]
Nice, I am still floundering with trying to use blueprint. 😛

**Comment by Aman9das** [comment]
> Nice, I am still floundering with trying to use blueprint. 😛 

I couldn't succeed with blueprint either..

The build was getting strange errors.. In retrospect the blueprint wiki made us replace com.blueprint.sample at only 1 place with com.donnnno.arcticons

Candybar wiki tells the right way:

    In Android Studio go to Edit > Find > Replace in Path
    In the first text input box write com.candybar.sample and in the second input box write your app's package name
    Choose 'In Project'
    Click Replace All
    Do Gradle Sync

Do this for blueprint and i think you'll be more successful..

**Comment by dgcampbe** [comment]
I don't know if that is the issue. I really am a noob and don't know how to solve this (very basic, I presume) error that I am getting.
```
Build file 'E:\Downloads\Blueprint-sample\build.gradle' line: 13

A problem occurred evaluating root project 'Blueprint-sample'.
> Could not get unknown property 'Plugins' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
lines 12 -15 
```
    dependencies {
        classpath Plugins.android
        classpath Plugins.kotlin
    }
```

**Comment by dgcampbe** [comment]
Here is my attempt at trying to follow the guide so far, but I don't really know what I am doing when it comes to java/kotlin/gradle.
https://github.com/dgcampbe/Blueprint

**Comment by Aman9das** [comment]
Hey i cant help you because i am a noob too... and i had that same exact problem which forced me to switch plans..

**Comment by dgcampbe** [comment]
2 noobs make an expert, right? 😛 
I asked about it in the discord server for Blueprint and I might ask around on the r/AndroidDev discord server for help learning this.

**Comment by Donnnno** [comment]
Wow, this is great! @Aman9das

**Comment by Donnnno** [comment]
> but how do i share the code, make a repo myself?

Create a separate repo or a different branch is easier, probably.

> 2 noobs make an expert, right? 😛

Make that 3 I barely know what I'm doing too 😄 

But seriously, this is great work! If we can get everything right, the icon request tool in there too, that would be amazing to have!

**Comment by Aman9das** [comment]
Ok.. My father took the computer to office, so we gotta wait 4 hours... but yes it has many goodies, we can supply widgets, wallpapers etc 
And because of the open source nature we could talk with either blueprint or candybar to help us code the -change icon color setting... it could be a global variable i suppose..

The possibilities are definitely big!

**Comment by Donnnno** [comment]
Exciting!

**Comment by Aman9das** [comment]
Well I struggled to create branch and repository, no success
So here's the zip https://drive.google.com/file/d/1K6puuF5Q7l8KxRRbL-0d7C5EHxMkvxBb/view?usp=sharing :)

**Comment by Donnnno** [comment]
I'll create a branch, but I have to check some things in the build.gradle & manifest first :)

**Comment by Donnnno** [comment]
Does candybar only need two drawable sizes for the icons?

**Comment by Aman9das** [comment]
I don't think so

**Comment by Donnnno** [comment]
I think the other drawables are for compatability with older devices with lower resolutions

**Comment by Donnnno** [comment]
Just tweaked some stuff so it should work with the build flavors now and published a branch named candybar
