### ISSUE TITLE
Candybar: Polish themes to match Light & Dark

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#317]
- [x] Dark theme
- [x] Light theme
- [x] Custom icons
- [ ] Arcticons font

**Comment by Aman9das** [comment]
https://github.com/zixpo/candybar-sample/wiki/Changing-navigation-drawer-icons

We gotta use this.. should i recycle old stuff or you'll draw new icons for the navigation drawer..?

**Comment by Donnnno** [comment]
Ohh, yea I was wondering already if that's possible. I'll creat a few icons later today :)

**Comment by Donnnno** [comment]
![IMG_20210910_143054.jpg](https://user-images.githubusercontent.com/31142286/132853641-b0c32317-a235-41a0-b351-cde28641158b.jpg)

**Comment by Aman9das** [comment]
Did you make the stroke width more than 1 intentionally?

About light theme.. I was thinking it still doesn't look good, can you make the primary color #808080 and test it out...

**Comment by Donnnno** [comment]
> Did you make the stroke width more than 1 intentionally?
 
Yes, I think it's better for the menu icons.

> About light theme.. I was thinking it still doesn't look good, can you make the primary color #808080 and test it out...

I haven't touched the light to be honest, will take a look at it later :^)

**Comment by Aman9das** [comment]
Alright, so my idea rn is similar to dark theme, except #000000 replaced by #808080 or completely disregarding the light theme

I'll send prototypes to you, if you like them I'll push the changes..

**Comment by Donnnno** [comment]
Great!

**Comment by Aman9das** [comment]
![Screenshot_20210910_213157](https://user-images.githubusercontent.com/39594914/132883395-03ade1a3-6913-4348-aec1-6f471160a1f2.jpg)

The dark n light mode both are pitch black.. should i push, also i changed the violet ripple on long clicking an icon

**Comment by Donnnno** [comment]
I've updated the theme for Arcticons light. Kinda ignored the in-app dark & light modes because it doesn't make much sense to use.
