### ISSUE TITLE
Candybar: descriptions & stuff

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#320]
- [x] list of contributors
- [x] descriptions

**Comment by joelchrono12** [comment]
Is this a new icon pack gui?

**Comment by Donnnno** [comment]
Yes! Based on [Candybar](https://github.com/zixpo/candybar)

![image](https://user-images.githubusercontent.com/31142286/132722826-a59aa1d0-2cdc-4179-8b6c-8ff7a55e1844.png)
![image](https://user-images.githubusercontent.com/31142286/132722879-929f487e-129f-49bf-ab57-1b293905bc3d.png)
![image](https://user-images.githubusercontent.com/31142286/132722845-116a6458-be24-472d-a868-ebb6d7322f1d.png)

**Comment by joelchrono12** [comment]
OH my! It looks awesome! When will it be ready? :P

**Comment by Donnnno** [comment]
Soon™

**Comment by Donnnno** [comment]
Updated the phone screenshots too: 

![phonescreenshotsdark](https://user-images.githubusercontent.com/31142286/133004164-783f678b-fb99-44eb-bc30-332ea8559aff.jpg)
![phonescreenshotslight](https://user-images.githubusercontent.com/31142286/133004165-deebc43c-fddc-4661-bc40-c5c5b99b142f.jpg)

**Comment by joelchrono12** [comment]
Which launcher is that? Also, I noticed there are none of the icons I've done :'c

**Comment by Donnnno** [comment]
They are just screenshots from my phone, that's probably why. I use nova launcher 7 :^)

**Comment by joelchrono12** [comment]
> They are just screenshots from my phone, that's probably why. I use nova launcher 7 :^)

Dont worry I remembered Usage Direct was done by me, which is why I deleted that part xd
