### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by francescosoave** [Donnnno/Arcticons#321]
[20210903_100922.zip](https://github.com/Donnnno/Arcticons/files/7137350/20210903_100922.zip)

thank you!

**Comment by joelchrono12** [comment]
I did a couple of these icons, but not all of them

- [ ] Live DV
- [ ] Manager
- [ ] Metrobank
- [ ] Monefy
- [ ] MySielteId
- [ ] Okcupid
- [ ] onecalendar
- [ ] Tapemeasure
- [ ] Weather

**Comment by francescosoave** [comment]
thanks! btw I now noticed "Manager" is just magisk so please ignore that

**Comment by Donnnno** [comment]
Just did okc & onecalendar!

![image](https://user-images.githubusercontent.com/31142286/132957051-9fde1399-ffd5-4a4f-8155-315a0acd2bc4.png)

**Comment by Quantenzitrone** [comment]
For MySielteId: Should I add the text or just leave it like that?
![mysielteid1](https://user-images.githubusercontent.com/74491719/133867499-952a3c23-6451-4974-9a55-a08ca5a239bf.png)

**Comment by Aman9das** [comment]
I'd say add text, @Donnnno will remove it if he feels..

**Comment by Donnnno** [comment]
Nice solution! Less text is better indeed!
