### ISSUE TITLE
Guide to Contributing

### ISSUE THREAD

**Issue by elchiquics** [Donnnno/Arcticons#33]
Can you put a more detailed guide to contributing, explaining how add the new icons and metadata of app to the .xml files?
In this way you can help to people like me who can execute commands to build repos but don't understand any line of code. You would help a lot of people without programming experience that want to contribute to this repo in the future.

**Comment by Donnnno** [comment]
Hi! You don't need any programming experience to contribute. I'm not a programmer either, just a guy who copied some code from the Frost icon pack and started to experiment with it.

I'll have a look at rewriting the contributing page when I have more time.

**Comment by elchiquics** [comment]
Sure! Thanks for you answer, is great read that you have no programming experience even so bring us an beautiful icon pack!

**Comment by Donnnno** [comment]
Thanks!
