### ISSUE TITLE
Fire Bot reveals email address in Icon request

### ISSUE THREAD

**Issue by joelchrono12** [Donnnno/Arcticons#348]
Since Github issues are open for everyone to see, I think that the email should be not shown in each request, at least publicly.

This is a privacy concern that should be taken into account. I don't think we'll need to update the app itself to fix this, so it should be done quickly

**Comment by Aman9das** [comment]
I have 2 possible solutions in mind :

- create an email account which intercepts the requests and sends it to firebot

- edit fire bot source code such that it doesn't say the email-id

**Comment by joelchrono12** [comment]
> I have 2 possible solutions in mind :
>     * create an email account which intercepts the requests and sends it to firebot

We could use https://simplelogin.io for that!

>     * edit fire bot source code such that it doesn't say the email-id

Isn't there like a format option for this kinda thing, some flag or something?

> On an unrelated note, could you create a markdown guide as to how to get started with contributing to arcticons using inkscape.
> Assuming they have zero prior experience with inkscape and github...

Yeah I might do that. Should be simple enough

**Comment by Donnnno** [comment]
Hey, I'm aware of this issue.

Firebot has a toggle to hide the persons email. Personally I'm against that because I want to know where the request are coming from. 

Anonymizing the request would be a huge deal for me because it makes al this work even more impersonal and that's not the reason I started doing this.

So, I want to know as a dev, who I'm dealing with, how many times the person already requested something and how to contact them when needed.

But I know leaking email adresses to github isn't ideal, if others share this concern too, my solution would be to use my arcticons@onnno.nl mail and let me upload the stripped request to github.

**Comment by Aman9das** [comment]
You don't have access to the email id 
`arcticons@ fire.foundersclub.com`?

**Comment by Donnnno** [comment]
No, everything goes through the bot. Kinda like a relay mail address.

**Comment by Aman9das** [comment]
Ok then we just need to make a forwarding mail  that you have access to and which forwards to firebot, kinda clunky but does the job. (For the moment)

Then we can fork firebot and change it to intercept an email that you own.

It would have been great if firebot could intercept arcticons@onno.nl directly though.. :(

**Comment by joelchrono12** [comment]
Can you setup the forwarding by yourself or do you still want me to set it up? Idk how I would do it if I don't have access to the account xD

**Comment by Aman9das** [comment]
@joelchrono12 yeah you're right, i mean if @Donnnno wants to publish on PlayStore, he needs a gmail id anyway, then he can follow this:

https://support.google.com/mail/answer/10957?hl=en

and set things up. We can't do much ourselves..

**Comment by Aman9das** [comment]
What's the status on this @Donnnno ?

**Comment by Donnnno** [comment]
Nothing new here.

**Comment by Aman9das** [comment]
OK so the reasons why revealing the email id of customers in public is VERY-BAD:

- they didn't consent
- on top of that https://askleo.com/why_shouldnt_i_post_my_email_address_in_a_public_forum/

**Comment by Donnnno** [comment]
Sure, you're right! I'll remove the addresses, but I'm also changing the email back to arcticons@onnno.nl, so no more automation after the next release.

**Comment by joelchrono12** [comment]
Yeah maybe just forward the emails to your account and then resend them here and strip out the address and even some of the device details too. We dont need to know the model and stuff for most things here

**Comment by Aman9das** [comment]
Ayeah that's better still

**Comment by Donnnno** [comment]
> 
> 
> Yeah maybe just forward the emails to your account and then resend them here and strip out the address and even some of the device details too. We dont need to know the model and stuff for most things here

That's the idea

**Comment by Aman9das** [comment]
I'd say  save the zips and https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue 

And reupload in new issue for old requests

**Comment by Aman9das** [comment]
I'd say  save the zips and https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue 

And reupload in new issue for old requests

**Comment by Donnnno** [comment]
Updated the email for the next release

**Comment by Donnnno** [comment]
No we don't use this system anymore..
Idk why gmail is recommended
