### ISSUE TITLE
Candybar: F-Droid instead of Play Store Link

### ISSUE THREAD

**Issue by Quantenzitrone** [Donnnno/Arcticons#362]
Make Candybar add the F-Droid Link for F-Droid Apps instead of automatically adding the Play Store Link for all.

**Comment by Aman9das** [comment]
I didn't understand.. can you elaborate a bit?

What is the affected area of the app..?

**Comment by Quantenzitrone** [comment]
The App in general is not affected, but when submitting an icon request to GitHub, Candybar adds a link to the app in the Play Store, consisting of `"https://play.google.com/store/apps/details?id="` + `applicationId` (e.g. "com.drutol.malclient")
Because Arcticons mainly focuses on F-Droid Apps, it would be convenient to add links to F-Droid instead.
`"https://f-droid.org/en/packages/"` + `applicationId`
Because not every App is available on F-Droid it would maybe be possible to differentiate between Play Store and F-Droid Apps and add the right link for every app.

**Comment by Quantenzitrone** [comment]
I looks like what I described is done in this script:

https://github.com/zixpo/candybar/blob/main/library/src/main/java/candybar/lib/tasks/IconRequestBuilderTask.java in ll. 120 ff.:

`stringBuilder.append("\r\n\r\n")`
`     .append(request.getName())`
`     .append("\r\n")`
`     .append(request.getActivity())`
`     .append("\r\n")`
`     .append("https://play.google.com/store/apps/details?id=")`<--
`     .append(request.getPackageName());` <--

I have no idea if it is possible to easily find out if an app is available on F-Droid. 
Maybe through the where the app is installed from. In that case, other App-Stores could also probably be included.

**Comment by Aman9das** [comment]
I mean for us its irrelevant, the zip file does the job, we can delete the line completely safely

But thanks for pointing to the file!
I have no idea how to overwrite library files.. let me tinker around and see if it works

**Comment by Quantenzitrone** [comment]
Getting the attribute where the App was installed from should be possible trough [this](https://developer.android.com/reference/android/content/pm/PackageManager#getInstallSourceInfo(java.lang.String))

[here](https://stackoverflow.com/questions/10809438/how-to-know-an-application-is-installed-from-google-play-or-side-load) is where I got it from

I can't help further because I don't know Java

**Comment by Aman9das** [comment]
https://medium.com/@jasjot784/how-to-modify-an-android-library-in-7-steps-bf9c16aa6dfa

This sound like quite a headache

**Comment by Quantenzitrone** [comment]
Yay

**Comment by Aman9das** [comment]
Ok so after a bunch of error debugging the thing, I sincerely believe we need to ask for help from someone..

or support from candybar themselves, but im going to keep trying, we just need to implement the library by hand

**Comment by Donnnno** [comment]
I found this after a brief search:
https://forum.f-droid.org/t/build-log-for-failing-build/14676
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9546/diffs

**Comment by Aman9das** [comment]
It works now! We'll be able to tweak the candybar library now!

**Comment by Aman9das** [comment]
Added the functionality:)

**Comment by Quantenzitrone** [comment]
Have you found a way to differentiate between App from F- Droid and Google Play or have you changed the link to always being the F-Droid link

**Comment by Aman9das** [comment]
Yes play store gets play store link

And sideloaded apks/malware/official-fdroid-apps get fdroid links

Because they are installed by the same apk-installer but it is what it is :(

**Comment by Donnnno** [comment]
that's really cool tho
