### ISSUE TITLE
F-Droid build fails (2.1.8)

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#363]
Idk I have to check the logs but the build failed

**Comment by Donnnno** [comment]
![Screenshot_20210915-113059_F-Droid_Build_Status.png](https://user-images.githubusercontent.com/31142286/133408746-c31afee3-5c09-4c31-b2f3-b9c28f471a4b.png)

**Comment by Donnnno** [comment]
from the AndroidManifest.xml >

**Comment by Donnnno** [comment]
I found this after a brief search:
https://forum.f-droid.org/t/build-log-for-failing-build/14676
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9546/diffs

**Comment by Aman9das** [comment]
Can we help in some way..?
Or only the f-droid people can fix the problem

**Comment by Donnnno** [comment]
It looks like the F-Droid team fixed it already.
https://gitlab.com/fdroid/fdroiddata/-/commit/e6432f5453c64bd9245aa700d871ae3a4eb5e310

**Comment by Donnnno** [comment]
It failed again, oh no!

**Comment by Donnnno** [comment]
![Screenshot_20210919-004525_F-Droid_Build_Status.png](https://user-images.githubusercontent.com/31142286/133910372-2866acf9-e2a5-4f06-83ea-859c83cfd801.png)

**Comment by Donnnno** [comment]
We could try to release a new version with the now internal library, IDK if that would be the solution. What do you think @Aman9das ?

**Comment by Aman9das** [comment]
Is there some way to trial run this art home?

Because there will be a lot of analytics and stuff.. and it will crash for each.. we gotta strip it..

I'll read the documentation n remove the stuff now

**Comment by Donnnno** [comment]
Ehhh, there's this guide how to test it, but you need like 150gb of disc space to test a build :s 
https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by Aman9das** [comment]
Yeah not feasible in my dad's computer as its windows n potato
We can create a request for help, ideally someone with everything already set-up.. but i think its better not to be too hopeful..

Anyway if this succeeds other icon packs can also be built on f-droid using this
