### ISSUE TITLE
Remove unnecisarry permissions

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#364]
List of all the permissions:
android.permission.ACCESS_NETWORK_STATE, 
android.permission.ACCESS_WIFI_STATE, 
android.permission.FOREGROUND_SERVICE, 
android.permission.INTERNET, 
android.permission.READ_EXTERNAL_STORAGE, 
android.permission.RECEIVE_BOOT_COMPLETED, 
android.permission.SET_ALARM, 
android.permission.SET_WALLPAPER, 
android.permission.WAKE_LOCK, 
android.permission.WRITE_EXTERNAL_STORAGE, 
android.permission.WRITE_SETTINGS, 
com.android.vending.BILLING, 
com.android.vending.CHECK_LICENSE

**Comment by Donnnno** [comment]
Do we need these with candybar?

android.permission.ACCESS_NETWORK_STATE,
android.permission.ACCESS_WIFI_STATE,
android.permission.FOREGROUND_SERVICE,
android.permission.INTERNET,
com.android.vending.BILLING,
com.android.vending.CHECK_LICENSE
android.permission.RECEIVE_BOOT_COMPLETED,
android.permission.SET_ALARM,
android.permission.SET_WALLPAPER,
android.permission.WAKE_LOCK,

**Comment by Aman9das** [comment]
The wallpapers and stuff

**Comment by Donnnno** [comment]
But how to remove them? :/

**Comment by Aman9das** [comment]
Umm.. its hard coded in the library..

Good thing i've been trying to remove the dependence on the library and add it by hand..

This is unfortunately pretty complicated though..

**Comment by joelchrono12** [comment]
But I wanted to have wallpapers :'c

Like, each collaborator gets to pick one :P

**Comment by Aman9das** [comment]
@joelchrono12 Yes that's a good idea, but the wallpapers are cloud based, is that what we want..

I think we can tweak the library to ship them offline someday..

**Comment by Aman9das** [comment]
Attempted this in the pull request, i have no idea how to check if its working well or not..

**Comment by Aman9das** [comment]
Can someone test if the fix is working properly?

**Comment by Donnnno** [comment]
In today's update, only these are still present:

- android.permission.FOREGROUND_SERVICE, 
- android.permission.READ_EXTERNAL_STORAGE, 
- android.permission.RECEIVE_BOOT_COMPLETED, 
- android.permission.WRITE_EXTERNAL_STORAGE, c
- om.android.vending.CHECK_LICENSE

Any idea why we would need RECEIVE_BOOT_COMPLETED?

I think we could also get CHECK_LICENSE out of the list

**Comment by Aman9das** [comment]
removed license checking

and i want to see arcticons after rebooting phone, so that is needed ✔️

**Comment by Donnnno** [comment]
check

**Comment by Donnnno** [comment]
FOREGROUND_SERVICE is for the widgets, I presume?

**Comment by Aman9das** [comment]
I have no idea, but i dont think it's malicious..

**Comment by Donnnno** [comment]
nah I think it's fine now.
