### ISSUE TITLE
Widget suggestions..

### ISSUE THREAD

**Issue by Aman9das** [Donnnno/Arcticons#366]
I am willing to add widgets arcticons style.
Any suggestions?

**Comment by Donnnno** [comment]
Not really a new widget idea, but maybe make the clocks clickable and link them to the clock app.

**Comment by Aman9das** [comment]
Done :)

**Comment by Donnnno** [comment]
Yush, besides that I personally don't use that many widgets. But if you can think of something, be my guest :^)

**Comment by Donnnno** [comment]
Hey, I noticed that the widget doesn't use the font anymore for me. Is that intentional?

**Comment by Donnnno** [comment]
Strange 

![Screenshot_20210920-121257_Nova7.png](https://user-images.githubusercontent.com/31142286/133986466-2439936c-0e3e-4017-b404-ff396a390c82.png)

**Comment by Donnnno** [comment]
Oh, and as for suggestions:

- click on the date to open the calendar app
- click on both clocks to open clock app (it doesn't work for me for some reason)

**Comment by Aman9das** [comment]
I dont know why it is'nt working, maybe its something about android version changes, because it works well in android 9

it should work now with the app font atleast, and umm.. if it doesnt work as intended i guess its better to just remove it

and maybe request the functionality upstream

**Comment by Aman9das** [comment]
> Oh, 
> - click on both clocks to open clock app (it doesn't work for me for some reason) 

Because we removed set alarm permission

**Comment by Donnnno** [comment]
Oh hahah, I feel so dumb right now

**Comment by Aman9das** [comment]
I realised recently too! Can you remove tools:node=remove part in libs/candybar/src/main androidmanifest file?

**Comment by Saijin-Naib** [comment]
If you're still taking requests, I'd love an arcticons font'd and icon'd version of the OpenWeather widgets, just so it fits in better.

Also, an Arcticons font'd and icon'd calendar and event list (that behave similar to default Google Calendar ones) would be amazing.

**Comment by Donnnno** [comment]
It would be better to make a widget suggestions page in the Discussions section I guess
