### ISSUE TITLE
[Feature Request] Different Icon Colours

### ISSUE THREAD

**Issue by Erithax** [Donnnno/Arcticons#37]
Option for black icons.
Option for any colour icons.
Option for icon shadow (on white/lightly coloured icons).

Any of these options would make the iconpack more usable on lighter backgrounds and/or fit people's themes better.

**Comment by Donnnno** [comment]
I've been thinking about that for a while too, dunno how to add it myself, but it might become easier when I've converted all icons to xml. See #19  for that progress

**Comment by aaronhatesregex** [comment]
Technically you can just use `sed` in a Bash script to batch invert or change the fill and stroke colors in those SVG files.

    #!/usr/bin/env bash
    # batch_invert_color.sh
    # Just a demo, it doesn't even work in color represented like #ffffff
    black="stroke:#fff"
    white="stroke:#000"
    for x in $*
    do
    sed -e "s/${white}/${black}/g" $x > temp$x
    mv temp$x $x
    done

You can pull the repo, cd to the `icons` folder and `./batch_invert_color.sh *.svg`. Then you can build the app yourself.

The similar thing should be feasible in Java / Kotlin (but it's on the user end instead) and you can take an another look at the Makefile in #25.

**Comment by austenadler** [comment]
Some minor updates if this is the script to be used. Will match `#fff`, `#ffff`, and `white`
```bash
#!/usr/bin/env bash
# batch_invert_color.sh
white="stroke\s*:\s*\(#fff\|#ffffff\|white\)"
# If you want to replace all stroke colors (won't match rgb()/hsl()/..., but will match #... and black/blue/...):
# ="stroke\s*:\s*#\?[[:alnum:]]\+"
black="stroke:#000" # can replace with any target color
for x in other/*.svg; do
	sed -i "s/${white}/${black}/Ig" "${x}"
done
```

**Comment by TBog** [comment]
> Option for black icons.
> Option for any colour icons.
> Option for icon shadow (on white/lightly coloured icons).

Are you talking about an option in the icon pack application to switch between your options?
Can you give an example of another app that does this?

**Comment by aaronhatesregex** [comment]
> Can you give an example of another app that does this?

IIRC, [Simple Thank You](https://github.com/SimpleMobileTools/Simple-Thank-You) (it's avaliable in Play Store and F-Droid too) allows user to customize icons of all the apps by [SimpleMobileTools](https://github.com/SimpleMobileTools/). No idea whether it is the example you want.

And if it does work, there is one drawback that the launcher needs some time to refresh the icons during which time they may seem to disappear. And it just sounds quite weird if all the icons (included in this icon pack) have that kind of behavior at the same time.

**Comment by Donnnno** [comment]
Hi, I'm working on a way to choose between black & white icons. Right now it works in-app only, but I'm hoping that there's a way to do this outside the app too.

I'm using @TBog's XML icons to accomplish this :^) 

![image](https://user-images.githubusercontent.com/31142286/123638371-667d3700-d81f-11eb-8873-59c62f08f531.png)

**Comment by TBog** [comment]
I don't think there is a way to do this without support from the launcher

**Comment by Donnnno** [comment]
Hmm, I was afraid of that. 
I was hoping on finding a way to choose between two sets of drawables when you apply the icon pack.

Still looks pretty cool in the app 😄

**Comment by binyamin** [comment]
What if you detect the right color (black/white) via the wallpaper?
Also, I understand that you want to provide a seamless solution for the icon colors. Currently, there's _no_ solution. It's impossible to use with a white wallpaper. Personally, I would provide an in-app option for the time being.

**Comment by Donnnno** [comment]
@binyamin Probably a launcher that forces dark icons on light mode would be amazing.

But for now the easiest solution without coding is a standalone dark icon version (witch I'm working on btw!)

![262dde9de2458f51.jpg](https://user-images.githubusercontent.com/31142286/128089526-bf02097b-c6b3-4023-9514-cf396310b802.jpg)

**Comment by TBog** [comment]
If you are using my [Tinybit Launcher](https://github.com/TBog/TBLauncher) you can module the color of the icons to any other color easily because the source is white.
This can only be done by the launcher, the icon pack has no ability to allow the user to choose.

**Comment by Donnnno** [comment]
@TBog that's a really cool & underrated feature! Will check it out tomorrow!

**Comment by Donnnno** [comment]
The solution for now would be creating different flavors of the icon pack, which I've done recently with the release of [Arcticons Light](https://f-droid.org/packages/com.donnnno.arcticons.light/ ).

**Comment by mubashir-rehman** [comment]
for reference to generate custom apks with user selected color for lines https://github.com/nikgapps/config

**Comment by Donnnno** [comment]
@Aman9das feel free to host it yourself in a new repo, (that's easier for me).
I can also create a new flavor if you want and include it in here.

Btw, I'm working on an Arcticons mini github site with some features like icon search. We can showcase it there too.

**Comment by mubashir-rehman** [comment]
https://github.com/nikgapps/deploy/blob/main/.github/workflows/Config_Deployment.yml

> for reference to generate custom apks with user selected color for lines https://github.com/nikgapps/config

**Comment by Donnnno** [comment]
For anyone interested in colored icons, I'd suggest installing [Icon Pack Studio](https://www.iconpackstudio.com/), select Arcticons as a base and then apply it with the color that you want! :^)
