### ISSUE TITLE
Arcticons Dark icon request

### ISSUE THREAD

**Issue by hobisi2781** [Donnnno/Arcticons#372]
[icon_request_18_09_2021_22_15_44.zip](https://github.com/Donnnno/Arcticons/files/7190323/icon_request_18_09_2021_22_15_44.zip)

PS: I love this app.

**Comment by Donnnno** [comment]
- [ ] 1DM
- [x] Camera
- [ ] DailyPic
- [ ] EasyJoin
- [ ] Fitify
- [x] Lawnchair
- [x] Lawnchair Settings
- [ ] Network Speed
- [ ] Oto Music
- [ ] Ox. En. Dict
- [ ] SpanishDict
- [ ] Training
- [ ] WO Mic
- [ ] World Map Quiz

PS: Thanks <3

**Comment by Donnnno** [comment]
The new icons, enjoy! (other icons already existed but are updated now) 


![image](https://user-images.githubusercontent.com/31142286/133906600-a0374388-c51a-4128-bdcc-2244b9c2ed53.png)

PS: If you like the icon pack, consider donating a few bucks to support the development :^)
