### ISSUE TITLE
F-Droid: Arcticons Dark is listed as "Arcticons Light"

### ISSUE THREAD

**Issue by dalaeance** [Donnnno/Arcticons#384]
Not sure is this has been reported as yet…

Arcticons Light shows up twice in F-Droid. However, when installing them, one reveals itself to be Arcticons Dark.

**Comment by Donnnno** [comment]
I know, it's related to this issue: #376

**Comment by Aman9das** [comment]
Its called "Triple-T metadata fuckup with F-droid" #376

**Comment by Donnnno** [comment]
It has a better title now

**Comment by dalaeance** [comment]
Hahaha! Thanks, and my bad. 

I missed the initial issue, #376. I think the new name will help prevent multiple reports.

**Comment by Donnnno** [comment]
Yup haha
