### ISSUE TITLE
(Not an) Icon Request

### ISSUE THREAD

**Issue by coxackie** [Donnnno/Arcticons#386]
So, I used the latest candybar version, and the app shows that I am missing icons for these four apps:
```
AdGuard
com.adguard.android/com.adguard.android.ui.MainActivity

FKM
com.franco.kernel/com.franco.kernel.activities.SplashActivity

Rightmove
com.rightmove.android/com.rightmove.android.modules.splash.SplashPageActivity

Seven
se.perigee.android.seven/com.perigee.seven.ui.activity.SplashActivity
```
(also attaching the zip in the end).

The weird part is that three of them (all except `Seven`) have actually Arct-icons, and they appear as they should. I am not sure whether there is some mistake in metadata. So this is _not_ an icon request (apart from `Seven`, which would be a simple "7", and appreciated if it gets included), but a check whether something weird is happening with the other three.

[icon_request_19_09_2021_17_05_57.zip](https://github.com/Donnnno/Arcticons/files/7192635/icon_request_19_09_2021_17_05_57.zip)

**Comment by dgcampbe** [comment]
My guess is that the activity names changed and we don't have the new ones in appfilter.xml file. I noticed that Google TV stopped working, too. I am going to make a pull request that *should* fix these.

**Comment by dgcampbe** [comment]
#387 should fix this (except for Seven since we don't seem to have that icon). Why these activity names changed is beyond me. 😛

**Comment by Aman9das** [comment]
Thanks!

**Comment by coxackie** [comment]
@dgcampbe I get that activity names may have changed, but why do I keep seeing the correct arcticon for these apps, and they are being flagged as absent?
