### ISSUE TITLE
Bugged icons

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#392]
Icons that don't work correctly:

**Dark:**

- NHS

**Light:**

- Habitica
- Qmanager
- Whereby
- Windy

Why are some icons in dark white or blue?
Because the there are tiny errors in the white icons. Instead of #ffffff they are something like #f4ffff

Will fix this later

**Comment by Aman9das** [comment]
Fixed.

**Comment by coxackie** [comment]
have any of these fixes been pushed? For example, NHS app still looks weird for me (H is indeed rendered without its right vertical line. I noticed it depends on the size of the icon - if the launcher supports larger sizes, it appears correct.)

**Comment by Donnnno** [comment]
Yes most of these are fixed! Check the latest release

**Comment by coxackie** [comment]
thanks, can confirm it is fixed. I had the last version, but it took some time to show the right icon. I guess they get cached and do not change immediately.

**Comment by Donnnno** [comment]
I think it depends per launcher.
