### ISSUE TITLE
Blue flavour!

### ISSUE THREAD

**Issue by Aman9das** [Donnnno/Arcticons#394]
![Screenshot_20210920_180636.jpg](https://user-images.githubusercontent.com/39594914/134003397-c9f98c24-ee3c-4102-af1f-0672edb95058.jpg)

- Just modify /other/white.sh
- Comment out rasterlight.sh in raster.sh
- run raster.sh for a few hours..
- build and install :)

**Comment by Donnnno** [comment]
Woah cool!

**Comment by joelchrono12** [comment]
We can give [Just New Designs](https://play.google.com/store/apps/dev?id=6871333323804023406) some competition lol

**Comment by Donnnno** [comment]
> 
> 
> We can give [Just New Designs](https://play.google.com/store/apps/dev?id=6871333323804023406) some competition lol

![image](https://user-images.githubusercontent.com/31142286/134056280-18d06e23-2a2f-4887-a035-0e4f0857cbb3.png)

**Comment by joelchrono12** [comment]
Honestly tho, his icon packs kind of inspired me to do my own icons, I never did tho, until I found Arcticons!

**Comment by dgcampbe** [comment]
We could take some inspiration from this pack: https://play.google.com/store/apps/details?id=com.jndapp.linex.white.iconpack
There are some interesting ideas here. I still prefer the more consistent design philosophy in arcticons (exclusively lines) and the icon for Reddit in the screenshots kinda looks like nightmare fuel IMHO.

**Comment by joelchrono12** [comment]
I actually got a lot.of those icon packs in twittwr giveaways, kinda good. But I think that our output is quite strong.

@Donnnno you should make some graphs showing the icon increase per update, would be pretty interesing.
Even comparing with other icon packs, just to see

**Comment by Donnnno** [comment]
@joelchrono12 I did something like that a while ago, still have that data somewhere:

![f4aaf1862ef992d3.jpg](https://user-images.githubusercontent.com/31142286/134127014-79a431c3-4828-4e44-842e-768e36bfad8c.jpg)

**Comment by Aman9das** [comment]
Release! I'll state everything i did in a guide :)

**Comment by Donnnno** [comment]
Cool! And congrats! But why not call it Arcticons Blue or something?

**Comment by Donnnno** [comment]
Oh, and you should probably sign your APK's!

**Comment by Aman9das** [comment]
Because people could want other blues..? It would better to not be fancy like apple, i feel.

**Comment by Donnnno** [comment]
Nah man, you should own it and just use blue or _royal blue_

Oh and some icon suggestions:

General app icon suggestion
![image](https://user-images.githubusercontent.com/31142286/134533019-41d01fea-21f4-463f-b24f-31481ae45b53.png)


With Arcticons enabled:
![image](https://user-images.githubusercontent.com/31142286/134532942-704e003a-29f2-42f2-88f9-9695c3da73e9.png)

**Comment by Aman9das** [comment]
Do you have xmpp? I need help

**Comment by Donnnno** [comment]
I can help you with that! 
But I don't use XMPP, you can contact me here, matrix, mail, fosstodon or discord.

**Comment by joelchrono12** [comment]
> I can help you with that!
> But I don't use XMPP, you can contact me here, matrix, mail, fosstodon or discord.

Hey guys we should make an arcticons matrix room, would be fun

**Comment by Donnnno** [comment]
Sure :)

#arcticons:matrix.org

**Comment by Aman9das** [comment]
ok i made a guide about the stuff i know at building the variants
at: https://github.com/Aman9das/Arcticons/blob/main/guides/Create_Variants_Guide.md

**Comment by Donnnno** [comment]
Anything you need from me for this?

**Comment by Aman9das** [comment]
Yes.. Could you follow the guide in /guides and tell what to do after that to change apk name and build signed apk..?

Im not able to do it.. :(

**Comment by Donnnno** [comment]
Oh, yeah right! I'll add it to my to-do list.
