### ISSUE TITLE
Appfilter problems..

### ISSUE THREAD

**Issue by Aman9das** [Donnnno/Arcticons#400]
@Donnnno I believe it's a lot to curate the icons and then check the appfilters..

A lot of us are drawing the icons, but the appfilters are missing for quite a few activities, it'd be better to have 1 person solely for checking the appfilters

I think that is just as important a contribution as adding icons

**Comment by Aman9das** [comment]
Also the appfilter at /other overwrites those at main/asset n main/res/xml as the script runs

**Comment by Donnnno** [comment]
Editing the appfilter can cost a lot of time, mainly because alphabetically putting everything in there is a pain to do.

But we have a sort script. The only problem with it right now, is that it removes the dynamic calendar lines when sorting.

Fixing that could make the process so much easier.

**Comment by Donnnno** [comment]
Anyways, I don't see this as a problem because we don't provide any liability. If there's an icon missing or it doesn't work, that isn't our problem. And it can be added in the next version most of the time
