### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by mubashir-rehman** [Donnnno/Arcticons#402]
[icon_request_21_09_2021_17_04_19.zip](https://github.com/Donnnno/Arcticons/files/7202875/icon_request_21_09_2021_17_04_19.zip)

**Comment by mubashir-rehman** [comment]
19 icon requests

**Comment by Aman9das** [comment]
trebleshot has updated their icon, i think we should the one with us too..

**Comment by joelchrono12** [comment]
working on this one

- [ ] 1by1
- [ ] 1lyrics
- [ ] bykeapartner
- [ ] easypaisa
- [ ] ex kernel manager
- [ ] hmanager
- [ ] ktweak
- [ ] stereo test
- [ ] media rescan
- [ ] phone
- [ ] sagernet
- [ ] scanmediaplz
- [ ] screenkap
- [ ] sharik
- [ ] trebleshot
- [ ] tshot debug
- [ ] uber driver
- [ ] unseen gallery
- [ ] some weird characters with a weird name

**Comment by Donnnno** [comment]
>  some weird characters with a weird name

😆 

I mostly look up the names in the appfilter code when I can't figure it out

**Comment by Donnnno** [comment]
Trebleshot doesn't exist anymore btw, and the current icon is fine

**Comment by joelchrono12** [comment]
I kinda didn't feel like making the couple icons missing lol

**Comment by Donnnno** [comment]
That's fine.
It be like that sometimes.
