### ISSUE TITLE
Material You Arcticons For Android 11 or lower

### ISSUE THREAD

**Issue by mubashir-rehman** [Donnnno/Arcticons#404]
This can be thought as a 1 to 1 copy of LineX app icons. Where there would be one primary color for lines and one or more secondary color.
The users can select the colors or can be generated from wallpaper(as to give Material You effects ) and then this would use the system implemented for #403 to generate new icon pack.
This is against the current philosophy/rules of Arcticons and should be closed but can be considered as another project.

**Comment by mubashir-rehman** [comment]
I appreciate the work of JustNewDesigns and love his icon packs. And I would love it to be done by him, too. It is his idea after all. But I like how icons change color in Material You and would love to see something from him for that but for older devices. on that note I am closing this issue cuz that was just a thought and morally not good.

**Comment by Donnnno** [comment]
Ah yeah, it's fine to suggest new ideas! 
I'm always open for it.

**Comment by Aman9das** [comment]
Icons change colour in Material you ?
