### ISSUE TITLE
How to screen recording using Vector Asset Creator

### ISSUE THREAD

**Issue by mubashir-rehman** [Donnnno/Arcticons#405]
Kindly provide a sample how to recording to use Vector Asset Creator.

**Comment by Donnnno** [comment]
@Aman9das provided a guide here: https://github.com/Donnnno/Arcticons/blob/main/Vector_Asset_Creator.md

I'm not familiar with it, but maybe there are some tutorials on youtube :^)

**Comment by Donnnno** [comment]
Also, can you move your questions to the discussions tab? 
https://github.com/Donnnno/Arcticons/discussions

**Comment by Aman9das** [comment]
Hey why did you close this, he was asking for a "how-to" screen recording

I'll record and publish
You should open this..

**Comment by mubashir-rehman** [comment]
i already tried making an icon with it. However, it was too complicated to be done. Also, I accidentally deleted a line that was difficult to draw. I am gonna try a simple one and record it too. Thanks anyways.

**Comment by Aman9das** [comment]
Yeah you can't draw difficult icons with vector asset creator, for example those with text, and you dont need to worry about stroke width and stuff as we'll set it properly on inkscape..

Thanks for helping out! You can try drawing a smiley for practice..

**Comment by Aman9das** [comment]
Yeah you can't draw difficult icons with vector asset creator, for example those with text, and you dont need to worry about stroke width and stuff as we'll set it properly on inkscape..

Thanks for helping out! You can try drawing a smiley for practice..

**Comment by mubashir-rehman** [comment]
Thanks for the heads up. I was trying to create the following icon.
![image](https://user-images.githubusercontent.com/51048830/134293373-8584ed1e-64e3-41c8-b75d-55eebeb91983.png)
It was almost finished but I saw the deleted line after moving so many steps ahead and it was beyond the undo limit. So, I gave up.

**Comment by Aman9das** [comment]
Just draw the train n the outline

**Comment by Aman9das** [comment]
Just draw the train n the outline

**Comment by Aman9das** [comment]
Just draw the train n the outline

**Comment by mubashir-rehman** [comment]
i will try it later. thanks

**Comment by Donnnno** [comment]
> Hey why did you close this

It's more a discussion topic instead of an issue.
