### ISSUE TITLE
Update v 2.2.5 changelog

### ISSUE THREAD

**Issue by mubashir-rehman** [Donnnno/Arcticons#407]
Kindly update changelog for v2.2.5 or add the current changes in next update changelog.
things i noticed:
- App UI
- Built-in Icon requests
- and of course more icons as always
Thanks!

**Comment by Donnnno** [comment]
Everything is already up-to-date, the new UI is a 2.1.8 thing: https://github.com/Donnnno/Arcticons/blob/main/CHANGELOG.md

Fun fact: my version numbering is based on the icon amount ;)

**Comment by mubashir-rehman** [comment]
my bad and thanks
