### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by hjr265** [Donnnno/Arcticons#41]
Icons for these two apps would be greatly appreciated.

```
<!-- Readrops -->
<item component="ComponentInfo{com.readrops.app/com.readrops.app.activities.SplashActivity}" drawable="readrops"/>
<!-- Steam Link -->
<item component="ComponentInfo{com.valvesoftware.steamlink/com.valvesoftware.steamlink.SteamShellActivity}" drawable="steamlink"/> 
```

![IMG_20210113_233312](https://user-images.githubusercontent.com/348107/104487803-c24c5e80-55f7-11eb-89a1-f169574a3e2f.jpg)

**Comment by Donnnno** [comment]
![image](https://user-images.githubusercontent.com/31142286/104513279-ae046380-55ef-11eb-9487-2a25e0c75e7b.png)

Created the icons, they should appear in the next update.
