### ISSUE TITLE
Automated CI/CD

### ISSUE THREAD

**Issue by mubashir-rehman** [Donnnno/Arcticons#410]
Kindly use github actions to test and build new versions and release on the fly to github and any other platform(telegram).
Following are examples that I could find:
- https://github.com/MuntashirAkon/AppManager/blob/master/.github/workflows/debug_build.yml
- https://github.com/trebleshot/android/blob/master/.github/workflows/android-test.yml

### Guide
https://medium.com/google-developer-experts/github-actions-for-android-developers-6b54c8a32f55

**Comment by Donnnno** [comment]
I like to build them myself, mostly once a week with android studio. For me, that makes more sense for the nature of this project. Weekly (or biweekly) with ~50 icons every time is a lot for icon packs.

Also I'm already having F-Droid, GitHub & GPlay to distribute the apk's on, that's more than enough for me :)

**Comment by Aman9das** [comment]
Can be closed.
