### ISSUE TITLE
Arcticons Dark Icon Request (5 icons)

### ISSUE THREAD

**Issue by marcoismobile** [Donnnno/Arcticons#435]
Request for 5 icons (Dark):

- ABN AMRO
- Bitpanda
- Bybit
- FTX Pro
- TradingView (New logo)

Thanks in advance (And thank you for the amazing icon pack!)

```
<!-- ABN AMRO -->
<item component="ComponentInfo{com.abnamro.nl.mobile.payments/com.abnamro.nl.mobile.payments.ui.activity.main.SplashActivity}" drawable="abnamro"/>
<!-- Bitpanda -->
<item component="ComponentInfo{com.bitpanda.bitpanda/com.bitpanda.bitpanda.ui.splash.SplashscreenActivity}" drawable="bitpanda"/>
<!-- Bybit -->
<item component="ComponentInfo{com.bybit.app/com.bytick.app.MainActivity}" drawable="bybit"/>
<!-- FTX Pro -->
<item component="ComponentInfo{com.ftxmobile.ftx/com.ftxmobile.MainActivity}" drawable="ftxpro"/>
<!-- TradingView -->
<item component="ComponentInfo{com.tradingview.tradingviewapp/com.tradingview.tradingviewapp.root.view.RootActivity}" drawable="tradingview"/>
```
[20210925_094236.zip](https://github.com/Donnnno/Arcticons/files/7229440/20210925_094236.zip)

**Comment by Donnnno** [comment]
Lots of banking and money icons!

Anyways I've completed your request, the icons will appear in the next release.

![image](https://user-images.githubusercontent.com/31142286/134771592-a9670081-0c4e-47c5-9396-eced66445a3f.png)

PS: Consider donating a few bucks to support the development of this icon pack, it takes a lot of time to create icons and maintain everything, thanks :^)

**Comment by marcoismobile** [comment]
@Donnnno Those where the 5 icons I was still missing, the other ones where covered by the massive collection already available :) And coincidental they where all finance related.

Thank you for the fast action!

**Comment by Donnnno** [comment]
No problem, glad you like them!
