### ISSUE TITLE
Request for Support of KISS Launcher

### ISSUE THREAD

**Issue by sasukeiscool** [Donnnno/Arcticons#441]

**Comment by Aman9das** [comment]
In the apply icon pack section? Sure will request upstream..

**Comment by Donnnno** [comment]
Candybar issue: https://github.com/zixpo/candybar/issues/55

**Comment by Donnnno** [comment]
It still works on KISS right? Just not the fancy apply from app setting.

**Comment by sasukeiscool** [comment]
> It still works on KISS right? Just not the fancy apply from app setting.
It works for me no problem.

**Comment by Donnnno** [comment]
I don't think KISS supports this, but I might be wrong.

**Comment by Donnnno** [comment]
Update: it should work: https://github.com/Neamar/KISS/issues/1801

**Comment by Donnnno** [comment]
Okay another update: KISS Doesn't support it, so unfortunately I can't implement it.
