### ISSUE TITLE
Some icons not working

### ISSUE THREAD

**Issue by Penaz91** [Donnnno/Arcticons#49]
Greetings, thank you for this great icon pack, there are some icons that seem to be present but are not shown on my xiomi redmi note 7.

Here are the details from turtl

```
<!-- Chrome -->
<item component="ComponentInfo{com.android.chrome/com.google.android.apps.chrome.Main}" drawable="chrome"/>
<!-- Duo -->
<item component="ComponentInfo{com.google.android.apps.tachyon/com.google.android.apps.tachyon.MainActivity}" drawable="duo"/>
<!-- Messaggi -->
<item component="ComponentInfo{com.android.mms/com.android.mms.ui.MmsTabActivity}" drawable="messaggi"/>
<!-- Telefono -->
<item component="ComponentInfo{com.android.contacts/com.android.contacts.activities.TwelveKeyDialer}" drawable="telefono"/>
```

"Messaggi" os the default sms app
"Telefono" is the dialer.

Thank you for your attention.

**Comment by Donnnno** [comment]
Hi, I've checked the files, everything should work in the next update! Let me know if it still doesn't work by then :)
