### ISSUE TITLE
Arcticons not appearing in the latest on F-Droid tab after update

### ISSUE THREAD

**Issue by Donnnno** [Donnnno/Arcticons#490]
Why tho :(

**Comment by joelchrono12** [comment]
Has this gotten fixed? kind of sad to not be as discoverable

**Comment by Donnnno** [comment]
Idk, I hope changelogs are visible again by changing it to this:
https://github.com/Donnnno/Arcticons/tree/main/app/src/dark/play/release-notes/en-US

But if that doesn't work, I probably have to install the F-Droid server to test it.

**Comment by Donnnno** [comment]
it's back!
