### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by marcdw1289** [Donnnno/Arcticons#5]
When this icon pack showed up on F-Droid I was so jazzed. Yes! Great work.

EteSync Notes
Iceraven
InviZible Pro
Mull
Pdf Viewer Plus
Phone Saver
SchildiChat
Send Reduced
Wallabag

[20201227_061207.zip](https://github.com/Donnnno/Arcticons/files/5745706/20201227_061207.zip)

**Comment by Donnnno** [comment]
Thanks! I'll see what I can do :) 

- [ ] EteSync Notes
- [ ] Iceraven
- [ ] InviZible Pro
- [ ] Mull
- [ ] Pdf Viewer Plus
- [ ] Phone Saver
- [ ] SchildiChat
- [ ] Send Reduced
- [ ] Wallabag

**Comment by Donnnno** [comment]
Some icons were already in there but needed to be updated, I created already a few, still have to create one for Schildi and Iceraven

![image](https://user-images.githubusercontent.com/31142286/103311978-00545a80-4a1c-11eb-9cc9-325a840cc940.png)

**Comment by Donnnno** [comment]
just released 1.1.1 with icons from this request!
