### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by T-Quill** [Donnnno/Arcticons#50]
Hello! I have an icon request here. I really like the clean minimalism of this icon pack, it's really nice. Thanks for making it!
[20210125_084143.zip](https://github.com/Donnnno/Arcticons/files/5870703/20210125_084143.zip)

**Comment by Donnnno** [comment]
Thanks, I'll take a look at it when I have some time :)

**Comment by T-Quill** [comment]
Thank you!

**Comment by Donnnno** [comment]
Created two new icons and updated the one for apkupdater:

![image](https://user-images.githubusercontent.com/31142286/107883777-42186200-6ef1-11eb-9564-2fee0ab08eeb.png)
