### ISSUE TITLE
Apps changing Icons

### ISSUE THREAD

**Issue by mdb571** [Donnnno/Arcticons#502]
Arcticons is showing this weird behaviour of apps changing icons randomly for me. These apps used to have their normal arcticons but now they've changed icons into the ones shown below.
![WhatsApp Image 2021-10-04 at 10 58 39](https://user-images.githubusercontent.com/55395092/135798825-b49f3d17-88ca-4447-99b9-2247f6f47608.jpeg)

**Comment by Donnnno** [comment]
Hmm that's weird..

**Comment by Aman9das** [comment]
Launcher? Does clicking apply icons button in the app help?

**Comment by mdb571** [comment]
Nope it doesn't do anything. This is how it is now, one of the apps have changed to their actual arcticon
![WhatsApp Image 2021-10-04 at 12 56 43](https://user-images.githubusercontent.com/55395092/135810524-76b85147-86ea-479c-abee-5a28188eda04.jpeg)

**Comment by Aman9das** [comment]
Then i think theirs issue in the actual appfilter or the drawable name..

**Comment by Donnnno** [comment]
I don't think it's an appfilter issue:
```
    <!-- Tutanota -->
    <item component="ComponentInfo{de.tutao.tutanota/de.tutao.tutanota.MainActivity}" drawable="tutanota" />
```

**Comment by Aman9das** [comment]
What is the launcher used?

**Comment by mdb571** [comment]
> What is the launcher used?

I'm on Color OS Launcher, its not yet listed on Arcticons. So I'm applying arcticons from the systems icon settings.
> Also does clearning app data and then apply icons button work?

idk why but this did the trick ! Now it back to normal
![WhatsApp Image 2021-10-04 at 13 49 48](https://user-images.githubusercontent.com/55395092/135817602-6bbca2ec-d8b1-45fa-8742-bc0c708b1df0.jpeg)

**Comment by Donnnno** [comment]
>  Donno what do you think of grouping the appfilter by version from now on?

I'm still more a fan of alphabetical. I use Ctrl+f all the time to search, makes things easier.

**Comment by Aman9das** [comment]
> > Donno what do you think of grouping the appfilter by version from now on?
> 
> I'm still more a fan of alphabetical. I use Ctrl+f all the time to search, makes things easier.

Same! The issue was false alarm, can be closed..

**Comment by Donnnno** [comment]
Glad to see clearing app data works!
