### ISSUE TITLE
[Packaging] APK File for IzzyOnDroid

### ISSUE THREAD

**Issue by aaronhatesregex** [Donnnno/Arcticons#54]
It is known to all that F-Droid usually lags behind on building apps for various reasons. 

I notice 1.3.0 release has a compiled .apk file, so I'm asking whether it would last, or just this one time. Arcticons now appears in [IzzyOnDroid F-Droid repo](https://apt.izzysoft.de/fdroid/index/apk/com.donnnno.arcticons?repo=main) but seems not activated since it requires static apk files for each release.

Quotes from [this page](https://android.izzysoft.de/repo/info) about `How do apps come into this repo?`:

> They are preferably hosted at Github. Code and .apk files must be available.
> .apk files are preferably located in the releases/ tree and are properly tagged. In this case, I can catch updates automatically.
> .apk size should not be too big. 2-5 MB are fine, up to 10 MB is acceptable. Above 10 MB are exceptions (must be a real good reason here), and my current „hard limit“ is 20 MB.

**Comment by Donnnno** [comment]
Uhm I had no idea the app was on IzzyOnDroid. I'm currently just focussing on a F-Droid & a GitHub release.

**Comment by aaronhatesregex** [comment]
> I'm currently just focussing on a F-Droid & a GitHub release.

IzzyOnDroid can be a third choice, so the user don't have to

1. periodically check GitHub and build the app themselves or
2. wait another week or two after the GitHub release only to scratch their head wondering why [the metadata](https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/com.donnnno.arcticons.yml) fetches the update but [the last build log](https://f-droid.org/wiki/index.php?title=com.donnnno.arcticons/lastbuild) is not the latest.

but can update the app more timely with F-Droid client or whatsoever third-party clients at the same time.

I'd appreciate it if you are more than generous to provide an apk file with each release, and if you don't want the app to be listed on IzzyOnDroid, maybe you can ask @IzzySoft to remove it.

**Comment by Donnnno** [comment]
I think it didn't get picked up last time because I had a typo in an older tag 1.2.9 and forgot to delete it.
something like this:

1.3.0
1.2.5
~1.2.9~ < this one shouldn't be there 
1.2.0
1.1.1
1.1.0

**Comment by Donnnno** [comment]
1.2.5 & 1.3.0 are both available on F-Droid now! I dunno what took so long, but I'm happy it updates again.

**Comment by IzzySoft** [comment]
Murphy had put his fingers in the build server, blocking it. We finally found where those fingers were and removed them today, then immediately kicked the process to run like "beer ahead, police behind". Worked.

**Comment by Donnnno** [comment]
Hehe nice! Thanks for the great work as always ;)
