### ISSUE TITLE
Mobile Legends icon update

### ISSUE THREAD

**Issue by murtezayesil** [Donnnno/Arcticons#541]
This request is __NOT__ urgent or priority. Take your time. This is just asking for a favor about an icon that looks out of place in my opinion.

Mobile Legends game has another icon (3 lanes M logo) for minimalistic or flat iconpacks. I believe it will look better than current icon which looks very busy.

![Screenshot_20211006-083250_Mobile_Legends_Bang_Bang](https://user-images.githubusercontent.com/24689015/136224289-a0825f3e-9fd4-467b-a8d0-fbb8c2e02f0f.png)
Above screenshot is taken while game was launching. I believe this M logo would look better in line form than current mixture of lines. Here is a forum thread regarding the M logo: https://forum.mobilelegends.com/forum.php?mod=viewthread&tid=80536

Mobile Legends: Bang Bang
com.mobile.legends/com.moba.unityplugin.MobaGameMainActivityWithExtractor
https://play.google.com/store/apps/details?id=com.mobile.legends

**Comment by Donnnno** [comment]
![image](https://user-images.githubusercontent.com/31142286/160251944-a61e9a99-f466-4fe9-b81b-18583d7050d3.png)

something like this then
