### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by warpedwood** [Donnnno/Arcticons#57]
Hi! Thank you very much for this beautiful icon pack. Here comes some icons:
[20210213_094708.zip](https://github.com/Donnnno/Arcticons/files/5976132/20210213_094708.zip)

**Comment by Donnnno** [comment]
Created these icons (simplified the mediapart one) some were already in the icon pack, so I updated those lines.

![image](https://user-images.githubusercontent.com/31142286/107883192-c49f2280-6eed-11eb-9987-2a021e319a8c.png)
![image](https://user-images.githubusercontent.com/31142286/107883194-c668e600-6eed-11eb-823e-62f5ad7b6f95.png)
