### ISSUE TITLE
Was support of the app dropped for older Android versions in the newest update?

### ISSUE THREAD

**Issue by creepertron95** [Donnnno/Arcticons#579]
I was wanting to update Arcticons Dark for an Android 7.1.1 device, past versions have worked, however the newest version of the app from F-Droid shows up as incompatible. I have checked the CandyBar version the latest version of the app uses (v1.13.0) and there's another theme (Delta, latest version) installed on the same device with the same exact CandyBar version. I was wondering if something changed that caused the app to be incompatible there. It does successfully install and run on my Android 11 phone though.

**Comment by Donnnno** [comment]
Good question, I'll have to look into that. 

Can you use the icons if you apply it from the launcher?

**Comment by Donnnno** [comment]
Maybe it's just a matter of changing the minimun sdk number, but I'll check if that breaks anything.

**Comment by Donnnno** [comment]
Arcticons should work with Android 7 again, changed some SDK numbers and tested it, found 0 problems :)
