### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by lisek-cytrusek** [Donnnno/Arcticons#6]
[iconsrequest.zip](https://github.com/Donnnno/Arcticons/files/5748409/iconsrequest.zip)
I hope I did it right \ (•◡•) / turtl was not working on my phone so i kind of tried to get the info through adb >_>. thanks for doing arcticons they are sooo pretty!!

**Comment by Donnnno** [comment]
Thanks!
Turtl isn't fully working for me either, can you provide screenshots of the icons?

**Comment by lisek-cytrusek** [comment]
Absolutely! Thank you for replying so fast. Here's a zip file with the original icons:
[iconsscreenshots.zip](https://github.com/Donnnno/Arcticons/files/5749213/iconsscreenshots.zip)
Also please note that the app with package name <mtakso> is now called <Bolt> (and this is what it's icon says)

**Comment by Donnnno** [comment]
PDF viewer & Whatsapp web did already have an icon, so I updated those lines, I've created one new icon for jakdojade: 

![image](https://user-images.githubusercontent.com/31142286/103310918-288e8a00-4a19-11eb-8a57-73a7a443a991.png)

These changes will arive next version (not 1.1.0 but 1.1.1 or 1.2.0)

**Comment by lisek-cytrusek** [comment]
That looks lovely, thank you!!!
Regarding the note about PDF viewer, think there might have been a wee mix up - I think I have sent the package_name + icon screenshot for the app called 'Bolt' (basically an uber alternative), not PDF Viewer. Please let me know if you see something else in my zip files and I will correct &reupload them (I have downloaded the zips myself and cannot see where the error could be :( ).

**Comment by Donnnno** [comment]
Nope, I don't see anything else in there. Can you open Turtl and view the app list? If that works you can make a screenshot of that as well like this: 

![signal-2020-12-30-122019](https://user-images.githubusercontent.com/31142286/103348222-a85c3900-4a99-11eb-9335-bdd543d1c97b.jpeg)

It's way easier for me to work with that.

**Comment by lisek-cytrusek** [comment]
Thank you for being so patient!
Here's the screenshot from turtl: 
![turtlscreenshot](https://user-images.githubusercontent.com/28781321/103370953-1ae30e00-4ac6-11eb-8540-080a18c9373d.jpeg)

**Comment by Donnnno** [comment]
just released 1.1.1 with icons from this request!
