### ISSUE TITLE
1.35 does not work / new icons not appear

### ISSUE THREAD

**Issue by michas0602** [Donnnno/Arcticons#62]
Hi, many thanks for your efforts, I recently installed your latest 1.35-apk -
unfortunately none of the new icons are displayed here. The ones from my request still look normal, all of them.

The old 1.20-version is completely uninstalled so I have definately activated 1.35.

**Comment by michas0602** [comment]
After a reboot and waiting a Moment, some of the new icons are shown now, so I think the problem was Trebuchet or just the speed.

Anyway, 3 icons are actually still missing atm from closed issues #47, 

"Verkaufen auf Etsy"
"Google Lens"
"Soundpicker" (Google)

**Comment by Donnnno** [comment]
Hey, there were some problems indeed! But they should be fixed now with the newest release (it has the same name), I'll check the 3 remaining icons when I have some time again

**Comment by Donnnno** [comment]
Oh, I checked real quick on my phone. The 3 remaining apps are in the app with the corresponding lines of code that I've received. Maybe you can manually pick them from your launcher ;)

**Comment by michas0602** [comment]
I think I found the problem, I try to attach some pictures.
It looks as if the Google-icons consits of 2 different icons, a large one and a small one. To me it looks as if in 1.35 the small ones have changed, but the large ones not:
![IMG_20210218_142016](https://user-images.githubusercontent.com/29848666/108363507-498f8200-71f5-11eb-8099-1991b6ad3c8c.jpg)
![IMG_20210218_142130](https://user-images.githubusercontent.com/29848666/108364426-56f93c00-71f6-11eb-9d9a-e992557bbbb5.jpg)
![IMG_20210218_142225](https://user-images.githubusercontent.com/29848666/108364441-5a8cc300-71f6-11eb-83a4-6477da51d38c.jpg)

But for Etsy I can find no such problem, also no icon by typing "Etsy" or "verkaufen" in the searchbox...there are two apps looking almost the same, are your sure both are there? 
![IMG_20210218_142402](https://user-images.githubusercontent.com/29848666/108364351-43e66c00-71f6-11eb-89cb-6865231af45c.jpg)

**Comment by Donnnno** [comment]
Hmm, interesting. If the Google icons aren't recognized there's not much I can do on that part. Maybe you can select them manually in your launcher.

Can you send the Verkaufen on etsy code again, so I can check?

**Comment by michas0602** [comment]
Sure:
[20210218_024948.zip](https://github.com/Donnnno/Arcticons/files/6003215/20210218_024948.zip)
The launcher (Lineage OS 17.1, Trebuchet) unfortunately has no further settings, just the option to select an icon pack as far as I can see

**Comment by Donnnno** [comment]
Ah, I fixed the etsy icon, it was missing that line. Unfortunately, I can't change widgets and how they look. I'm using Nova launcher to pick custom icons for apps, it's probably the best launcher out there.

**Comment by Donnnno** [comment]
Closing this issue because there's nothing I can do about widgets :)
