### ISSUE TITLE
[BUG] One app never shows on the "request icon" dialog

### ISSUE THREAD

**Issue by ghost** [Donnnno/Arcticons#623]
The request option inside the app is an awesome feature. I am facing the following issue with it: no matter how many apps don't have an icon, the Arcticons app shows all these apps, but always forgets one. 
If there is only one app that doesn't have an icon, no app at all is shown in the icon request activity.
It is however possible to select it by clicking on the "Select all" button.

I was able to reproduce this in both the light and dark versions.

## Screenshots

![Screenshot_20211024-021744_Arcticons_Dark](https://user-images.githubusercontent.com/90352798/138575304-798689c9-d5e9-4468-9727-0c5bb6e95aa7.png)
![Screenshot_20211024-021750_Arcticons_Dark](https://user-images.githubusercontent.com/90352798/138575312-2dd51cb7-5a46-4b9a-84f7-e99014080d5a.png)

**Comment by creepertron95** [comment]
This happens with the Arcticons app with me as well. This also occurs for me with other themes using Candybar, like the Delta Icon Theme as well, So I think it could have to do with Candybar.
