### ISSUE TITLE
Arcticons Dark Icon Request

### ISSUE THREAD

**Issue by dgcampea** [Donnnno/Arcticons#632]
[NASA Imagery Fetcher](https://f-droid.org/en/packages/com.beckhamd.nasaimageryfetcher/) - com.beckhamd.nasaimageryfetcher

[20211024_125745.zip](https://github.com/Donnnno/Arcticons/files/7425688/20211024_125745.zip)

**Comment by Donnnno** [comment]
This one is added in the latest release!
