### ISSUE TITLE
Icon Request for 5 apps (DKB the new app, Momox, Payback, etc.)

### ISSUE THREAD

**Issue by TobiasDev** [Donnnno/Arcticons#633]
[20211027_101006.zip](https://github.com/Donnnno/Arcticons/files/7426289/20211027_101006.zip)

**Comment by Donnnno** [comment]
Hi!
I wanted to notice you that your requested icons will appear in the next update of Arcticons.
Here's a quick preview:

![image](https://user-images.githubusercontent.com/31142286/150886661-de665ab5-e3ca-49fc-9ba8-733722888876.png)


PS: If you like the icon pack, consider donating a few bucks to support the development :^)
