### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by dragonhunter056** [Donnnno/Arcticons#66]
[20210221_021258.zip](https://github.com/Donnnno/Arcticons/files/6017511/20210221_021258.zip)

**Comment by Donnnno** [comment]
Hi, I've completed your request, some icons already existed like mix, mobilism, camera & 1 weather. So I added the corresponding lines of code to them. 
But I've also created some new ones, they should appear in the next update: 
Enjoy :)

![image](https://user-images.githubusercontent.com/31142286/108629094-a8a3ff80-745e-11eb-8b26-8c195fc7e2be.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.
