### ISSUE TITLE
Icon Request: Storytel, Kinder und Gift and CodeChecl

### ISSUE THREAD

**Issue by TobiasDev** [Donnnno/Arcticons#67]
[20210222_063826.zip](https://github.com/Donnnno/Arcticons/files/6019707/20210222_063826.zip)

**Comment by Donnnno** [comment]
Hi, I've created the icons, they should appear in the next update, enjoy :)

![image](https://user-images.githubusercontent.com/31142286/108685806-dfc4f000-74f4-11eb-837e-cb27cf312fed.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.

**Comment by TobiasDev** [comment]
I will donate a few bucks for sure! I looked for a donation option earlier but I couldn't see one. :)

**Comment by Donnnno** [comment]
Thank you!!
