### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Stormharn** [Donnnno/Arcticons#68]
[20210221_114220.zip](https://github.com/Donnnno/Arcticons/files/6019721/20210221_114220.zip)

**Comment by Donnnno** [comment]
Pfff, quite a huge request. I'll have a look at it when I have some time :)

**Comment by Stormharn** [comment]
No sweat, I just selected every icon that didnt already exist.
Here would be a smaller set of just the ones I use most often. Still has several apps but more focused than the original list. I appreciate all the work you have done its a great icon pack and being open soirce is just the icing on the cake.
[20210222_073414.zip](https://github.com/Donnnno/Arcticons/files/6022291/20210222_073414.zip)

**Comment by Donnnno** [comment]
Hi, thanks for the compliments!
I've managed to create every single one of them, it was quite a lot of work. Luckily some already existed.
Here are the new ones:

![image](https://user-images.githubusercontent.com/31142286/108733480-d3f61f80-752e-11eb-8eaa-53263109ae0e.png)
![image](https://user-images.githubusercontent.com/31142286/108733519-dc4e5a80-752e-11eb-99bb-fcb8e1d44339.png)
![image](https://user-images.githubusercontent.com/31142286/108733568-e7a18600-752e-11eb-85ac-8decbf371c82.png)
![image](https://user-images.githubusercontent.com/31142286/108733587-eff9c100-752e-11eb-8280-93dc901f73e9.png)
![image](https://user-images.githubusercontent.com/31142286/108733609-f5570b80-752e-11eb-91ae-bf0a908aa1d4.png)
![image](https://user-images.githubusercontent.com/31142286/108733689-06078180-752f-11eb-9438-5c2cc75c096e.png)

Enjoy!

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.
