### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by PetersProblem** [Donnnno/Arcticons#69]
[20210211_095737.zip](https://github.com/Donnnno/Arcticons/files/6022355/20210211_095737.zip)

Love your work! :)

**Comment by Donnnno** [comment]
Thanks! <3
Most of these icons already existed, so I updated those lines of code :) 
Here are the new ones:

![image](https://user-images.githubusercontent.com/31142286/108725134-59290680-7526-11eb-94ca-1f9fb89070d6.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.
