### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by 2br-2b** [Donnnno/Arcticons#73]
Hello!

Thank you so much for this icon pack! This is my first icon pack that I'm trying out, and I'm really impressed!

Here are the apps I use that aren't in the icon pack:

```
<!-- Auditor -->
<item component="ComponentInfo{app.attestation.auditor/app.attestation.auditor.AttestationActivity}" drawable="auditor"/>
<!-- Blue Line Console -->
<item component="ComponentInfo{net.nhiroki.bluelineconsole/net.nhiroki.bluelineconsole.applicationMain.MainActivity}" drawable="bluelineconsole"/>
<!-- Family Gem -->
<item component="ComponentInfo{app.familygem/app.familygem.Facciata}" drawable="familygem"/>
<!-- FindMyDevice -->
<item component="ComponentInfo{de.nulide.findmydevice/de.nulide.findmydevice.MainActivity}" drawable="findmydevice"/>
<!-- FluffyChat -->
<item component="ComponentInfo{chat.fluffy.fluffychat/chat.fluffy.fluffychat.MainActivity}" drawable="fluffychat"/>
<!-- Focal -->
<item component="ComponentInfo{fr.xplod.focal/org.cyanogenmod.focal.CameraActivity}" drawable="focal"/>
<!-- HTTP Shortcuts -->
<item component="ComponentInfo{ch.rmy.android.http_shortcuts/ch.rmy.android.http_shortcuts.activities.main.MainActivity}" drawable="httpshortcuts"/>
<!-- MemeTastic -->
<item component="ComponentInfo{io.github.gsantner.memetastic/net.gsantner.memetastic.activity.MainActivity}" drawable="memetastic"/>
<!-- MIT AI2 Companion -->
<item component="ComponentInfo{edu.mit.appinventor.aicompanion3/edu.mit.appinventor.aicompanion3.Screen1}" drawable="mitai2companion"/>
<!-- NoSurf for reddit -->
<item component="ComponentInfo{com.aaronhalbert.nosurfforreddit/com.aaronhalbert.nosurfforreddit.ui.main.MainActivity}" drawable="nosurfforreddit"/>
<!-- Omega Launcher -->
<item component="ComponentInfo{com.saggitt.omega/com.saggitt.omega.OmegaLauncher}" drawable="omegalauncher"/>
<!-- PDF Viewer -->
<item component="ComponentInfo{org.grapheneos.pdfviewer/org.grapheneos.pdfviewer.PdfViewer}" drawable="pdfviewer"/>
<!-- Podverse -->
<item component="ComponentInfo{com.podverse.fdroid/com.podverse.fdroid.MainActivity}" drawable="podverse"/>
<!-- TimeLimit -->
<item component="ComponentInfo{io.timelimit.android.aosp.direct/io.timelimit.android.ui.MainActivity}" drawable="timelimit"/>
<!-- Video Transcoder -->
<item component="ComponentInfo{protect.videoeditor/protect.videotranscoder.activity.MainActivity}" drawable="videotranscoder"/>
<!-- Vigilante -->
<item component="ComponentInfo{com.crazylegend.vigilante/com.crazylegend.vigilante.activities.MainActivity}" drawable="vigilante"/>
<!-- Weather -->
<item component="ComponentInfo{com.mbestavros.geometricweather/com.mbestavros.geometricweather.main.MainActivity}" drawable="weather"/>
```

Thank you for the time and for all of the work you put into this project!

**Comment by Donnnno** [comment]
Hi, thanks! Can you also include the icons? Otherwise, I can't create them!

**Comment by 2br-2b** [comment]
Sure! For some reason, I didn't see an option on Turtl to include this, but I'll find the and attach the icons in the next comment.

**Comment by 2br-2b** [comment]
Auditor
![Auditor](https://apt.izzysoft.de/fdroid/repo/icons/app.attestation.auditor.25.png)
Blue Line Console
![Blue Line Console](https://fdroid.tetaneutral.net/fdroid/repo/icons/net.nhiroki.bluelineconsole.14.png)
Family Gem
![Family Gem](https://apt.izzysoft.de/fdroid/repo/icons/app.familygem.19.png)
  FindMyDevice
![FindMyDevice](https://fdroid.tetaneutral.net/fdroid/repo/icons/de.nulide.findmydevice.6.png)
FluffyChat
![FluffyChat](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ffluffychat.im%2Fassets%2Fimages%2Ffavicon.png&f=1&nofb=1)
Focal
![Focal](https://fdroid.tetaneutral.net/fdroid/repo/icons/fr.xplod.focal.8.png)
HTTP Shortcuts
![HTTP Shortcuts](https://fdroid.tetaneutral.net/fdroid/repo/ch.rmy.android.http_shortcuts/en-US/icon_N2Fq81sL2hxnG-ruYap2gsn9q82UP2TBS5yVYubSfMY=.png)
MemeTastic
![MemeTastic](https://fdroid.tetaneutral.net/fdroid/repo/io.github.gsantner.memetastic/en-US/icon_7RAyalWuviikgvuSjJ-Zye1SWyVYhsHfd4yilxyTzXk=.png)
MIT AI2 Companion
![MIT AI2 Companion](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.LWfHhQCiduBYIkQJ4wOIxwAAAA%26pid%3DApi&f=1)
NoSurf for reddit
![NoSurf for reddit](https://fdroid.tetaneutral.net/fdroid/repo/com.aaronhalbert.nosurfforreddit/en-US/icon_3nhGQHTTJox5jM5c3vktQnaiz2jb3tw3Tvdrb7ntyEY=.png)
Omega Launcher
![Omega Launcher](https://apt.izzysoft.de/fdroid/repo/icons/com.saggitt.omega.118.png)
PDF Viewer
![PDF Viewer](https://raw.githubusercontent.com/GrapheneOS/PdfViewer/master/app/src/main/ic_launcher-web.png)
Podverse
![Podverse](https://fdroid.tetaneutral.net/fdroid/repo/com.podverse.fdroid/en-US/icon_mtzH2g7tPLEWTlfX2Utjv9ahClA-Rkl_omXnxbz_sCk=.png)
TimeLimit - Basically the same as Timelimit
![TimeLimit](https://fdroid.tetaneutral.net/fdroid/repo/io.timelimit.android.aosp.direct/en-US/icon_PaxylMiI-rzWjB0htPOybrteCvWUw53r2aMbnCc10FA=.png)
Video Transcoder
![Video Transcoder](https://fdroid.tetaneutral.net/fdroid/repo/protect.videoeditor/en-US/icon_tXO43YnYtOc6a6fq5cXrOSdyH0J0H-gTBUN1SSpWNMQ=.png)
Vigilante
![Vigilante](https://f-droid.org/repo/com.crazylegend.vigilante/en-US/icon_aI-f3bLk1BdSpQfDov2XQmHTjkK-2LSe607sFIoEFmM=.png)
Weather
![Weather](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwindowsprores.com%2Fwp-content%2Fuploads%2F2019%2F04%2FGeometric-Weather-for-PC-Windows-10-6432-bit-2019-Latest-Version.png&f=1&nofb=1)

Sorry for the variation in size - some images are from IzzyOnSoft's website, some are from Duckduckgo, and some are from github!

**Comment by Donnnno** [comment]
Thanks, I'll take a look at it when I have some time. But you just missed the new release (1.4.0)! There are some icons in there that you requested, but you have to wait awhile for the other ones ;)

**Comment by 2br-2b** [comment]
Absolutely! Take as much time as you need!

**Comment by Donnnno** [comment]
Hi, just finished this icon request! Here's a preview of the new icons, some were already in there.
They will appear in the next update 1.4.? (F-Droid is currently one version behind)
Enjoy!

![image](https://user-images.githubusercontent.com/31142286/109390223-99b2c680-7910-11eb-96c7-0f3632634851.png)

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.

**Comment by 2br-2b** [comment]
Thank you so much! I definitely want to support this, so I'll do what I can after Fdroid updates!
