### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by MrWhoseTheCodeGuy** [Donnnno/Arcticons#74]
Hi thanks for this wonderful icon pack. Please make some missing icons also.

Application Information

<item component="ComponentInfo{host.stjin.anonaddy/host.stjin.anonaddy.ui.SplashActivity}" drawable="anonaddy"/>

<item component="ComponentInfo{rikka.appops/rikka.appops.home.HomeActivity}" drawable="appops"/>

<item component="ComponentInfo{me.piebridge.brevent/me.piebridge.brevent.ui.BreventActivity}" drawable="brevent"/>

<item component="ComponentInfo{com.xaviertobin.noted/com.xaviertobin.noted.Activities.ActivitySignIn}" drawable="bundlednotes"/>

<item component="ComponentInfo{com.conducivetech.android.traveler/com.conducivetech.android.traveler.app.SplashScreenActivity}" drawable="flightstats"/>

<item component="ComponentInfo{cc.forestapp/cc.forestapp.applications.SplashActivity}" drawable="forest"/>

<item component="ComponentInfo{com.grofers.customerapp/com.grofers.customerapp.activities.ActivitySplashScreen}" drawable="grofers"/>

<item component="ComponentInfo{com.nextbillion.groww/com.nextbillion.groww.genesys.loginsignup.activities.LoginActivity}" drawable="groww"/>

<item component="ComponentInfo{com.gyandairy/com.app.gyandiarycustomer.register.ui.SplashActivity}" drawable="gyanfresh"/>

<item component="ComponentInfo{ml.docilealligator.infinityforreddit/ml.docilealligator.infinityforreddit.activities.MainActivity}" drawable="infinity"/>

<item component="ComponentInfo{com.brouken.player/com.brouken.player.PlayerActivity}" drawable="justplayer"/>

<item component="ComponentInfo{com.duy.calculator.free/com.duy.ncalc.calculator.ScientificCalculatorActivity}" drawable="ncalc"/>

<item component="ComponentInfo{com.omgodse.notally/com.omgodse.notally.activities.MainActivity}" drawable="notally"/>

<item component="ComponentInfo{com.asdoi.quicktiles/com.asdoi.quicksettings.SettingsActivity}" drawable="quicktiles"/>

<item component="ComponentInfo{xyz.myachin.saveto/xyz.myachin.saveto.ui.MainActivity}" drawable="saveto"/>

<item component="ComponentInfo{moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity}" drawable="shizuku"/>

<item component="ComponentInfo{com.pavelrekun.skit/com.pavelrekun.skit.containers.PrimaryContainerActivity}" drawable="skit"/>

<item component="ComponentInfo{com.adobe.spark.post/com.adobe.spark.view.main.SplashActivity}" drawable="sparkpost"/>

[20210224_081810.zip](https://github.com/Donnnno/Arcticons/files/6033056/20210224_081810.zip)

**Comment by MrWhoseTheCodeGuy** [comment]
<item component="ComponentInfo{host.stjin.anonaddy/host.stjin.anonaddy.ui.SplashActivity}" drawable="anonaddy"/>

<item component="ComponentInfo{rikka.appops/rikka.appops.home.HomeActivity}" drawable="appops"/>

<item component="ComponentInfo{me.piebridge.brevent/me.piebridge.brevent.ui.BreventActivity}" drawable="brevent"/>

<item component="ComponentInfo{com.xaviertobin.noted/com.xaviertobin.noted.Activities.ActivitySignIn}" drawable="bundlednotes"/>

<item component="ComponentInfo{com.conducivetech.android.traveler/com.conducivetech.android.traveler.app.SplashScreenActivity}" drawable="flightstats"/>

<item component="ComponentInfo{cc.forestapp/cc.forestapp.applications.SplashActivity}" drawable="forest"/>

<item component="ComponentInfo{com.grofers.customerapp/com.grofers.customerapp.activities.ActivitySplashScreen}" drawable="grofers"/>

<item component="ComponentInfo{com.nextbillion.groww/com.nextbillion.groww.genesys.loginsignup.activities.LoginActivity}" drawable="groww"/>

<item component="ComponentInfo{com.gyandairy/com.app.gyandiarycustomer.register.ui.SplashActivity}" drawable="gyanfresh"/>

<item component="ComponentInfo{ml.docilealligator.infinityforreddit/ml.docilealligator.infinityforreddit.activities.MainActivity}" drawable="infinity"/>

<item component="ComponentInfo{com.brouken.player/com.brouken.player.PlayerActivity}" drawable="justplayer"/>

<item component="ComponentInfo{com.duy.calculator.free/com.duy.ncalc.calculator.ScientificCalculatorActivity}" drawable="ncalc"/>

<item component="ComponentInfo{com.omgodse.notally/com.omgodse.notally.activities.MainActivity}" drawable="notally"/>

<item component="ComponentInfo{com.asdoi.quicktiles/com.asdoi.quicksettings.SettingsActivity}" drawable="quicktiles"/>

<item component="ComponentInfo{xyz.myachin.saveto/xyz.myachin.saveto.ui.MainActivity}" drawable="saveto"/>

<item component="ComponentInfo{moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity}" drawable="shizuku"/>

<item component="ComponentInfo{com.pavelrekun.skit/com.pavelrekun.skit.containers.PrimaryContainerActivity}" drawable="skit"/>

<item component="ComponentInfo{com.adobe.spark.post/com.adobe.spark.view.main.SplashActivity}" drawable="sparkpost"/>

**Comment by Donnnno** [comment]
Thanks, I'll take a look at it when I have some time. The newest update already has an icon for justplayer. Infinity also has one already but updated the corresponding lines of code.

**Comment by Donnnno** [comment]
Hi, just completed the icon request. Some icons already existed so I updated those and created new ones for the other icons.
Here's a preview of the new icons, Enjoy:

![image](https://user-images.githubusercontent.com/31142286/109427435-b9bab680-79f2-11eb-94ea-d5a429282d87.png)
![image](https://user-images.githubusercontent.com/31142286/109427439-bb847a00-79f2-11eb-819f-54115a613395.png)

I'll add them in the next update.

Ps. if you like them and want to support this icon pack, consider leaving a few bucks :) It can be very time-consuming to do this, thanks.
