### ISSUE TITLE
How to deal with some localized apps?

### ISSUE THREAD

**Issue by Rhodney** [Donnnno/Arcticons#78]
Some apps have the "drawable" property translated. As example the app [Digital Wellbeing](https://play.google.com/store/apps/details?id=com.google.android.apps.wellbeing) from Google have the name "Bem-estar digital" where I live.

Extracting the app data with Turtl I got the data bellow.

`<!-- Bem-estar digital -->`
`<item component=`
`"ComponentInfo{com.google.android.apps.wellbeing/com.google.android.apps.wellbeing.settings.LauncherActivity}"`
`drawable="bem-estardigital"/>`

I believe that in other countries, the property "drawable" is in English or in other languages. Can this cause some problem? How should I proceed when sending icons to these applications? Should I leave the property in my own language?

**Comment by Rhodney** [comment]
I believe I understand. "drawable" is the name of the image file to be fetched from resources. So it's better to use it in English to standardize. Also, if a new app can use an existing icon, just insert in drawable propertie the name of the existing resource image.

**Comment by Donnnno** [comment]
Hi! My preference goes to English app names :) But there are many languages used in the xml's.
