### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by michas0602** [Donnnno/Arcticons#79]
Hi,
after latest updates today, the Magisk-icon (now v22) disappeared - I assume its because they renamed the app? Not sure, but here is the Turtl-output.

[20210225_075744.zip](https://github.com/Donnnno/Arcticons/files/6045188/20210225_075744.zip)

And Ive also re-added "Verkaufen auf Etsy" again. Would be great if someone find a solution for this. Its the only missing icon here (and important to me / often in usage). 

In Lineage its unfortunately not possible to make manual changes to icons for Trebuchet and it does not make sense to change Trebuchet to me

Many thanks already

Edit: i've never seen your new "verkaufen auf Etsy" icon, but you have writteb that you are using the same icon as for the other app - would it be possible to add the word "sell" or "Verkaufen" to it when it works in future? Just to make them both differentiable.

**Comment by Rhodney** [comment]
@Donnnno . I take this one. I will do it in the next few days.

**Comment by Donnnno** [comment]
@Rhodney Thanks!

**Comment by Donnnno** [comment]
Fixed magisk already :)

**Comment by Rhodney** [comment]
@Donnnno As magisk changed the icon, I designed the new one, to, at your discretion, leave, modify or replace the old one. I recognize that this icon is far above my skills for now. 

I also created a slightly different icon for the "Sell on Etsy" app, as it is an app with a completely different purpose from the original Etsy, for buyers. I just put a dollar sign on the Etsy icon, remembering that you can make money through it.

![preview](https://user-images.githubusercontent.com/5544685/109539364-fb556b00-7a9f-11eb-88e4-82026c52e2b8.png)

**Comment by Donnnno** [comment]
Nice touch on the Etsy icon :)
Kinda worried that the magisk icon is too cluttered right now, but we'll see :) 

Thanks again @Rhodney !
