### ISSUE TITLE
Pikmin and League+ had their names and icons updated

### ISSUE THREAD

**Issue by Suburbanno** [Donnnno/Arcticons#794]
League+ > Riot Mobile

<item component="ComponentInfo{com.riotgames.mobile.leagueconnect/com.riotgames.mobile.leagueconnect.ui.MainActivity}" drawable="league_" />
![image](https://user-images.githubusercontent.com/13632826/141601938-b377e8e2-a4b9-4c36-8566-161f74a4e9a2.png)

Pikmin > Pikmin Boom

<item component="ComponentInfo{com.nianticlabs.pikmin/com.nianticproject.ichigo.IchigoUnityPlayerActivity}" drawable="pikmin_bloom" />
![image](https://user-images.githubusercontent.com/13632826/141601959-e85770af-ccb7-4127-8c2b-5dafedfd140b.png)

**Comment by Suburbanno** [comment]
https://iconpusher.com/package/com.nianticlabs.pikmin
https://iconpusher.com/package/com.riotgames.mobile.leagueconnect

**Comment by Donnnno** [comment]
Name & icon updates are not super important, here. The most important thing is that the appfilter stays the same, and it did that :)
