### ISSUE TITLE
Line Width

### ISSUE THREAD

**Issue by rednaz1337** [Donnnno/Arcticons#8]
Hi, great looking icon pack!
While creating some missing icons I noticed something:

The `CONTRIBUTING.md` file says the line width has to be 1 **pt**, however the line width of the icons in this pack is 1 **px** which is 0.75 pt in Inkscape.

**Comment by Donnnno** [comment]
Hi, Thanks for taking the time to contribute!
I'm using illustrator (it says 1pt there), the measurement is different somehow in inkscape.
I think if you're using a line width of 1 px it's fine :)

**Comment by rednaz1337** [comment]
Yes, 1px works fine. 👍
