### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by MonsterSwagger** [Donnnno/Arcticons#81]
[20210226_094013.zip](https://github.com/Donnnno/Arcticons/files/6048561/20210226_094013.zip)

**Comment by Rhodney** [comment]
@Donnnno  As you already have several requests, I also take this one. I will do that in the next few days.

**Comment by Donnnno** [comment]
@Rhodney thanks!! I've already applied the existing icons for music & infinity :)

**Comment by MonsterSwagger** [comment]
Both infinity's and music player's icon is not being applied so I included in this list.

**Comment by Donnnno** [comment]
Yeah, I noticed that too & fixed that already ;)

**Comment by Donnnno** [comment]
Opencvmanager's icon is already created by @RuffaWuffa in his last PR so no need to create that one too :)

**Comment by MonsterSwagger** [comment]
Cheers

**Comment by Rhodney** [comment]
The preview for the missing icons:

![preview](https://user-images.githubusercontent.com/5544685/109728078-4c468b80-7b94-11eb-8e42-730443b5ee03.png)

**Comment by Donnnno** [comment]
Lookin' great again!
