### ISSUE TITLE
Poco launcher not detecting

### ISSUE THREAD

**Issue by Gottarocket** [Donnnno/Arcticons#82]
I am using the poco launcher on miui 12 I have tried paid and free icons and when installed it will detect icon pack on pocolauncher . Since they are closed source  I dont feel like they would reply to this so have added issue here. Is there any changes to make so the launcher can detect or will you add it on next update . Thanks

**Comment by Donnnno** [comment]
Hi, I have absolutely no idea how these things work, so sorry about that. Maybe someone else knows... As for now I suggest switching to a different launcher ;) Nova launcher is great.

**Comment by tuch96** [comment]
...and Open Launcher work perfect! (F-Droid Version)

**Comment by Donnnno** [comment]
Great!

**Comment by Donnnno** [comment]
Had the same problem with POCO launcher on this phone. Maybe I should take a look what's making it not recognizable as an icon pack.

**Comment by Donnnno** [comment]
Okay it should work now if anyone likes to use POCO launcher ;)
