### ISSUE TITLE
Magisk not recognised (?)

### ISSUE THREAD

**Issue by spinoza-dat** [Donnnno/Arcticons#84]
**Steps to replicate:**
1) Update Magisk Manager to version 22.0 (22000).
2) Open any launcher with Arcticons.

**Expected behaviour:** Magisk Manager is still shown with the Arcticons icon.
**What happens instead:** Magisk Manager is now shown with the original icon and not the Arcticons one.

**Won't fix:** resetting custom icons, cleaning the cache of both launcher and Arcticons and rebooting the apps does nothing. If you set it up manually and reset custom icons, it will show again the original icon.

Maybe it's a matter of package name? I don't know the previous one, but now it's com.topjohnwu.magisk.

I tested this on a Zuk Z2 Pro with Android 9 on two Lawnchair-based launchers and Kiss Launcher.

It's not a big issue, since I can set it up manually, but it would be nice if it was fixed.

**Comment by Donnnno** [comment]
Yes, I'm aware of this issue. It's because of the new Magisk version. I'll fix it in the next version :)
