### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by nalinalini** [Donnnno/Arcticons#87]
<item component="ComponentInfo{com.tribyte.iTutor2/com.tribyte.iTutor2.MainActivity}" drawable="aakashitutor"/>

<item component="ComponentInfo{com.samsung.android.app.contacts/com.samsung.android.contacts.contactslist.PeopleActivity}" drawable="contacts"/>

<item component="ComponentInfo{com.samsung.android.forest/com.samsung.android.forest.launcher.LauncherActivity}" drawable="digitalwellbeing"/>

<item component="ComponentInfo{com.ultramegatech.ey/com.ultramegatech.ey.PeriodicTableActivity}" drawable="elementary"/>

<item component="ComponentInfo{in.gov.epathshala/in.gov.epathshala.activity.SplashActivity}" drawable="epathshala"/>

<item component="ComponentInfo{com.sec.android.app.samsungapps/com.sec.android.app.samsungapps.SKSamsungMainActivity}" drawable="galaxystore"/>

<item component="ComponentInfo{com.samsung.android.themestore/com.samsung.android.themestore.activity.Launcher}" drawable="galaxythemes"/>

<item component="ComponentInfo{com.abhyas.nta.com/com.embibe.app.activities.SplashActivity}" drawable="nationaltestabhyas"/>

<item component="ComponentInfo{aakash.neet.past_year_papers/com.meritnation.chat.modules.app_init_auth.controller.SplashActivity}" drawable="neetchallenger"/>

<item component="ComponentInfo{com.hardcodecoder.pulsemusic/com.hardcodecoder.pulsemusic.activities.main.SplashActivity}" drawable="pulsemusic"/>

<item component="ComponentInfo{com.unacademyapp/com.unacademy.consumption.unacademyapp.SplashActivity}" drawable="unacademy"/>

**Comment by nalinalini** [comment]
> 
> <item component="ComponentInfo{com.tribyte.iTutor2/com.tribyte.iTutor2.MainActivity}" drawable="aakashitutor"/>
> 
> <item component="ComponentInfo{com.samsung.android.app.contacts/com.samsung.android.contacts.contactslist.PeopleActivity}" drawable="contacts"/>
> 
> <item component="ComponentInfo{com.samsung.android.forest/com.samsung.android.forest.launcher.LauncherActivity}" drawable="digitalwellbeing"/>
> 
> <item component="ComponentInfo{com.ultramegatech.ey/com.ultramegatech.ey.PeriodicTableActivity}" drawable="elementary"/>
> 
> <item component="ComponentInfo{in.gov.epathshala/in.gov.epathshala.activity.SplashActivity}" drawable="epathshala"/>
> 
> <item component="ComponentInfo{com.sec.android.app.samsungapps/com.sec.android.app.samsungapps.SKSamsungMainActivity}" drawable="galaxystore"/>
> 
> <item component="ComponentInfo{com.samsung.android.themestore/com.samsung.android.themestore.activity.Launcher}" drawable="galaxythemes"/>
> 
> <item component="ComponentInfo{com.abhyas.nta.com/com.embibe.app.activities.SplashActivity}" drawable="nationaltestabhyas"/>
> 
> <item component="ComponentInfo{aakash.neet.past_year_papers/com.meritnation.chat.modules.app_init_auth.controller.SplashActivity}" drawable="neetchallenger"/>
> 
> <item component="ComponentInfo{com.hardcodecoder.pulsemusic/com.hardcodecoder.pulsemusic.activities.main.SplashActivity}" drawable="pulsemusic"/>
> 
> <item component="ComponentInfo{com.unacademyapp/com.unacademy.consumption.unacademyapp.SplashActivity}" drawable="unacademy"/>
>

**Comment by nalinalini** [comment]
<item component="ComponentInfo{com.tribyte.iTutor2/com.tribyte.iTutor2.MainActivity}" drawable="aakashitutor"/>

<item component="ComponentInfo{com.samsung.android.app.contacts/com.samsung.android.contacts.contactslist.PeopleActivity}" drawable="contacts"/>

<item component="ComponentInfo{com.samsung.android.forest/com.samsung.android.forest.launcher.LauncherActivity}" drawable="digitalwellbeing"/>

<item component="ComponentInfo{com.ultramegatech.ey/com.ultramegatech.ey.PeriodicTableActivity}" drawable="elementary"/>

<item component="ComponentInfo{in.gov.epathshala/in.gov.epathshala.activity.SplashActivity}" drawable="epathshala"/>

<item component="ComponentInfo{com.sec.android.app.samsungapps/com.sec.android.app.samsungapps.SKSamsungMainActivity}" drawable="galaxystore"/>

<item component="ComponentInfo{com.samsung.android.themestore/com.samsung.android.themestore.activity.Launcher}" drawable="galaxythemes"/>

<item component="ComponentInfo{com.abhyas.nta.com/com.embibe.app.activities.SplashActivity}" drawable="nationaltestabhyas"/>

<item component="ComponentInfo{aakash.neet.past_year_papers/com.meritnation.chat.modules.app_init_auth.controller.SplashActivity}" drawable="neetchallenger"/>

<item component="ComponentInfo{com.hardcodecoder.pulsemusic/com.hardcodecoder.pulsemusic.activities.main.SplashActivity}" drawable="pulsemusic"/>

<item component="ComponentInfo{com.unacademyapp/com.unacademy.consumption.unacademyapp.SplashActivity}" drawable="unacademy"/>

**Comment by nalinalini** [comment]
<item component="ComponentInfo{com.tribyte.iTutor2/com.tribyte.iTutor2.MainActivity}" drawable="aakashitutor"/>

<item component="ComponentInfo{com.samsung.android.app.contacts/com.samsung.android.contacts.contactslist.PeopleActivity}" drawable="contacts"/>

<item component="ComponentInfo{com.samsung.android.forest/com.samsung.android.forest.launcher.LauncherActivity}" drawable="digitalwellbeing"/>

<item component="ComponentInfo{com.ultramegatech.ey/com.ultramegatech.ey.PeriodicTableActivity}" drawable="elementary"/>

<item component="ComponentInfo{in.gov.epathshala/in.gov.epathshala.activity.SplashActivity}" drawable="epathshala"/>

<item component="ComponentInfo{com.sec.android.app.samsungapps/com.sec.android.app.samsungapps.SKSamsungMainActivity}" drawable="galaxystore"/>

<item component="ComponentInfo{com.samsung.android.themestore/com.samsung.android.themestore.activity.Launcher}" drawable="galaxythemes"/>

<item component="ComponentInfo{com.abhyas.nta.com/com.embibe.app.activities.SplashActivity}" drawable="nationaltestabhyas"/>

<item component="ComponentInfo{aakash.neet.past_year_papers/com.meritnation.chat.modules.app_init_auth.controller.SplashActivity}" drawable="neetchallenger"/>

<item component="ComponentInfo{com.hardcodecoder.pulsemusic/com.hardcodecoder.pulsemusic.activities.main.SplashActivity}" drawable="pulsemusic"/>

<item component="ComponentInfo{com.unacademyapp/com.unacademy.consumption.unacademyapp.SplashActivity}" drawable="unacademy"/>

**Comment by Donnnno** [comment]
Still empty  ¯\_(ツ)_/¯
