### ISSUE TITLE
Reddit Icon doesnt change

### ISSUE THREAD

**Issue by PaladinAOE2** [Donnnno/Arcticons#94]
There is a Reddit icon in the pack but it doesn't automatically changed so I had to manually go into nova settings. I think you should fix this. I did not change the Reddit icon pack manually before.

**Comment by Donnnno** [comment]
Hi, can you follow the icon request guide? and add the info here?

Icon Requests

This app doesn't have an icon request feature, so you'll have to do the following steps.

    Install Turtl which can extract the icons and class names of your apps.
    Grant the storage access permission to Turtl in your system settings, this will allow it to save the zip file (Only required in Android 6 "Marshmallow" or newer, older versions grant this permission on installation).
    Open Turtl and follow the process to save the new zip file to your phone.
    Make an issue titled "Icon Request" and attach the zip file.

If Turtl is not working on your device, you can also use Applications Info or any equivalent app to collect the package name of the app ($PACKAGE_NAME) and the main activity name of the app ($ACTIVITY_NAME) launchable in Applications Info with no errors. Work is being done to simplify this process.uests

**Comment by Donnnno** [comment]
reminder

**Comment by Saijin-Naib** [comment]
com.reddit.frontpage
Launcher.default

**Comment by Donnnno** [comment]
I need at least the whole line of code to apply it, you can gather it with turtl

**Comment by Saijin-Naib** [comment]
From the turtl XML

<item component="ComponentInfo{com.reddit.frontpage/launcher.default}" drawable="reddit"/>
