### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by m-0lly** [Donnnno/Arcticons#945]
*Info*

Could you pls add these two

https://github.com/deceptions/no

https://f-droid.org/en/packages/com.perol.asdpl.play.pixivez.libre/

Thx!
---

**Comment by Donnnno** [comment]
Hi! New icon requests are currently closed for the time being! 
(the pixivez one will probably be added soon because it's in other requests too)

**Comment by m-0lly** [comment]
> Hi! New icon requests are currently closed for the time being! (the pixivez one will probably be added soon because it's in other requests too)

Kool, thx!
