### ISSUE TITLE
More icons styles

### ISSUE THREAD

**Issue by Donkey-Doug** [Donnnno/Arcticons#970]
Would it be possible to have more icon styles? For example, would you fill the current icons to get something like this:

![whicons-white-icon-pack-android](https://user-images.githubusercontent.com/50382414/146421120-a66dd826-1d46-4b0e-aea9-752cde8f206b.jpg)

Or possibly also add more color options.

**Comment by Donnnno** [comment]
You should take a look at Frost for that!

**Comment by Donkey-Doug** [comment]
Yeah, frost is abondonned.

**Comment by Donnnno** [comment]
Unfortunately, yeah. We're focussing on lines here, changing it back to fill icons would be too much work for us and isn't our goal.

You can always fork the project ;)

**Comment by baitmooth** [comment]
[Snow](http://github/baitmooth/snow) here I try to go on with frost. It uses the icons already in the pack + my last PR.
It may be on f-droid soon, you can built it yourself until then.
