### ISSUE TITLE
Icons are blurry in Lawnchair

### ISSUE THREAD

**Issue by Donkey-Doug** [Donnnno/Arcticons#971]
![Screenshot_20211216-184339_Lawnchair_1](https://user-images.githubusercontent.com/50382414/146422283-ab36b3c0-948a-4805-97a2-06194750f3a6.png)

All icons from this icon pack are blurry on my phone.

Android version: 10 (SDK 29)
Device: Xiaomi Mi 9T Pro
Google Play services: not available

**Comment by Donnnno** [comment]
Weird, the icons are 256x256px, that should be way above what's needed.

**Comment by Donkey-Doug** [comment]
Let me know if you need more info to diagnose the problem.

**Comment by Donnnno** [comment]
Screen resolution?

**Comment by Donnnno** [comment]
Idk it may be your phone, our icons do have a high enough resolution.

![image](https://user-images.githubusercontent.com/31142286/146432023-63d06710-6d57-4f80-bb76-dbde0e4b6b33.png)

Does it differ with another launcher?

**Comment by Quantenzitrone** [comment]
# 6.39" (diagonally) AMOLED Full Screen Display
Resolution: 2340 x 1080 FHD+ 403 PPI
Brightness: 600nit (HBM) / 430nit (typ)
High contrast: 60000:1 (min) | Color Gamut: NTSC 103.8% (typ)

**Comment by Donkey-Doug** [comment]
It seems to be a lawnchair-specific problem. (lawnchair is a launcher app).

**Comment by Quantenzitrone** [comment]
The picture is 175 x 1080 pixels.
The full screen resolution is used to draw the icons:
![image](https://user-images.githubusercontent.com/74491719/146441314-0b2ad2c6-8155-4ec8-b8d3-88f3d7a33d52.png)
It's the same on my phone.

**Comment by Donkey-Doug** [comment]
The picture was a screenshot I cut.

**Comment by Quantenzitrone** [comment]
What scale do you have your icons on in Lawnchair?

**Comment by Donkey-Doug** [comment]
![Screenshot_20211216-210635_Lawnchair_1](https://user-images.githubusercontent.com/50382414/146441850-f62995d1-9401-4990-b5c2-ab0daacba777.png)

**Comment by Donkey-Doug** [comment]
Icon size 65%.

**Comment by Quantenzitrone** [comment]
Send a screenshot of 100% so we can compare

**Comment by Donkey-Doug** [comment]
![Screenshot_20211216-211244_Lawnchair](https://user-images.githubusercontent.com/50382414/146442555-e7ccc49c-e3d5-45e3-b1f6-0eab94e0f6d6.png)

**Comment by Quantenzitrone** [comment]
![image](https://user-images.githubusercontent.com/74491719/146442557-4d18d8c8-8c0c-4f32-aa77-7c51b1159e63.png)
here is mine on 100%

**Comment by Quantenzitrone** [comment]
Your icons are still smaller on 100%
weird

**Comment by Donkey-Doug** [comment]
Oh sorry, it is not 100%. I will update

**Comment by Donkey-Doug** [comment]
Your firefox is sharper.

**Comment by Quantenzitrone** [comment]
Yeah I don't know man. I tried with different icon sizes on my phone, but I can't replicate that.

**Comment by Quantenzitrone** [comment]
I counted the pixels. If you set the icon size to 114 or 115%, does that make it better? This should make your icons be very similar to the size of mine.
Though by doing the reverse and setting my icons to 87 or 88%, they are both a bit smaller or larger than your icons.
Is this blurry?:
![image](https://user-images.githubusercontent.com/74491719/146447951-88f2e548-49c9-463a-b071-8054e5cd602e.png)

**Comment by Donnnno** [comment]
Okey I’m starting to notice the blurriness at 115%
But I'm having some trouble how this works,... I mean, 256px x 5 = 1280px when you place the icons next to each other, that should be more enough for the icons to stay sharp.

**Comment by Donkey-Doug** [comment]
> I counted the pixels. If you set the icon size to 114 or 115%, does that make it better? This should make your icons be very similar to the size of mine. Though by doing the reverse and setting my icons to 87 or 88%, they are both a bit smaller or larger than your icons. Is this blurry?: ![image](https://user-images.githubusercontent.com/74491719/146447951-88f2e548-49c9-463a-b071-8054e5cd602e.png)

not blurry

**Comment by Donkey-Doug** [comment]
I tried several icon sizes and they are always blurry. The problems does not seem related to icon scale.

**Comment by Donnnno** [comment]
Seems to be a lawnchair issue, so I'd suggest you open an issue there! https://github.com/LawnchairLauncher/lawnchair/issues

Maybe I'm blind, but Nova looks much sharper compared to lawnchair when I enlarge the icons: 

![image](https://user-images.githubusercontent.com/31142286/146467871-bec34331-3439-4725-a733-f58175a83846.png)

**Comment by Donnnno** [comment]
Gonna close this because we can't do anything about it. If you want to get it fixed, open up an issue at the lawnchair repo!
