### ISSUE TITLE
svg list differs from drawables

### ISSUE THREAD

**Issue by TBog** [Donnnno/Arcticons#98]
After running
`find ./Arcticons/icons/ -type f -printf "%f\n" | sort | tr -d ".svg" >~/temp/icons.txt`
and
`find ./Arcticons/app/src/main/res/drawable-hdpi/ -type f -printf "%f\n" | sort | tr -d ".png" >~/temp/hdpi.txt`

The two resulting lists differ. Is this expected?
`diff ~/temp/icons.txt ~/temp/hdpi.txt`

**Comment by Donnnno** [comment]
Hmm, I noticed that too there are 3 icons that are missing in the /icons folder. Should take a look at it.
I think the eBay icon is one of them if I remember it correctly.

**Comment by Donnnno** [comment]
Just checked, the three missing icons are:

- accubattery
- binance
- boost

**Comment by TBog** [comment]
are there some that have a different name?
my diff returned a lot of differences

**Comment by Donnnno** [comment]
Hmm, I don't think so, there are 1422 drawables right now, and I've added the 3 icons, so there are 1422 icons in the /icons folder too.
