### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by coxackie** [Donnnno/Arcticons#984]
Don't know if you are still accepting "manual" requests, but here it is:
```
<!-- AlfredCamera -->
<item component="ComponentInfo{com.ivuu/com.ivuu.BrandingActivityCompat}" drawable="alfredcamera"/>
```
Icon at
https://play.google.com/store/apps/details?id=com.ivuu

Many thanks!

**Comment by Donnnno** [comment]
New icon requests are currently closed due to the many there are already.
