### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by baitmooth** [Donnnno/Arcticons#991]
*Info*

- [ ] FeinstaubWidget
- [ ]  Freifunk-Karte 
- [x] Kalender (LineageOS default)
- [x] Kalender (simplemobiletools)

---

[20220112_033744.zip](https://github.com/Donnnno/Arcticons/files/7855358/20220112_033744.zip)

**Comment by Donnnno** [comment]
What launcher are you using? Both calendqrs should work

**Comment by baitmooth** [comment]
> What launcher are you using? Both calendqrs should work

I use open launcher. Which is not really supported. But the only one that fits my needs.

**Comment by Donnnno** [comment]
Ah yes, this is an open launcher issue: https://github.com/Donnnno/Arcticons/issues/100

**Comment by baitmooth** [comment]
> Ah yes, this is an open launcher issue: #100 & [OpenLauncherTeam/openlauncher#653](https://github.com/OpenLauncherTeam/openlauncher/issues/653)

Thanks for pointing to this issues. For now I switched to lawnchair. Which lacks some features but is on the other hand more stable.

**Comment by Donnnno** [comment]
done 
![image](https://user-images.githubusercontent.com/31142286/150201941-6630d145-aba8-439d-8e3f-281cdfb22f8d.png)
