### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Phate6660** [Donnnno/Arcticons#992]
It would be awesome if we could get an OpenMW icon!
I would love to contribute, but to be honest I'm not that graphically inclined.
So I'm leaving this here in the hopes of someone picking this up. :D

**Comment by Donnnno** [comment]
If you'll use icon request and upload the zip here, we can take a look at it ;)

https://github.com/Kaiserdragon2/IconRequest/releases/

**Comment by Phate6660** [comment]
My bad. I completely forgot you guys had a system set up for this.

**Comment by Phate6660** [comment]
I used IconRequest for the above. I didn't find any way to send something, but there was a copy option.

**Comment by Donnnno** [comment]
You can save a zip file if you use the second option and upload it here. We need the icon too :)

**Comment by Donnnno** [comment]
Normally, we have the build in icon request function, but I disabled that one for the time being.

**Comment by Phate6660** [comment]
[IconRequest_13012022_181258.zip](https://github.com/Donnnno/Arcticons/files/7866562/IconRequest_13012022_181258.zip)

**Comment by Phate6660** [comment]
Sorry about the wait. Today has been a bit hectic and I forgot to check this issue.

**Comment by Donnnno** [comment]
No problem, we still have 216 other request to work on 🙃

**Comment by Donnnno** [comment]
Hi!
I wanted to notice you that your requested icons will appear in the next update of Arcticons.
Here's a quick preview: 

![image](https://user-images.githubusercontent.com/31142286/150201317-6a18c391-2d2c-405d-a387-27ab54fa2ac9.png)

 PS: If you like the icon pack, consider donating a few bucks to support the development :^)
