### ISSUE TITLE
Built in icon request feature

### ISSUE THREAD

**Issue by Donkey-Doug** [Donnnno/Arcticons#994]
What happend to the built in icon request feature.

It is not present anymore:
![Screenshot_20220115-224622_Arcticons_Dark](https://user-images.githubusercontent.com/50382414/149638719-40db92ac-bdca-40c8-a5fd-5f1d6704a1be.png)

**Comment by Donkey-Doug** [comment]
Found the new (seperate) tool. Please update readme.

**Comment by Donnnno** [comment]
Hi @Donkey-Doug , I think the amount of already open requests speaks for itself. 
I turned the icon request function off because we couldn't handle the load.
